### ISSUE TITLE
Smoother zooming out and in of character (camera)

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#101]
Zooming in and out with MOUSE3 doesn't look smooth, could be improved.

**Comment by Try** [comment]
Not 100% about how exactly camera use to behave in original game - marked as "help wanted"

**Comment by progward** [comment]
Well, when you use scroll with your mouse, which usually happens in small steps incrementally if you know what I mean, then the camera moves exactly according do this. It's a very "hard" animation, goes from 0 to 1 in an instant, instead of a smooth transition. So even if your mouse scrolls from 0-1 in an instant, the ingame camera should do it in smaller steps 0.1, 0.2, 0.3 to 1. You scroll with your mouse and let go of it, the camera ingame should move a little longer after you let go, fading off a bit. Else the smooth camera movement is probably not possible. 

Trying my best to explain it lol, a native english speaker would probably do a better job at this.

**Comment by Nindaleth** [comment]
Can't speak to the "original" original, I play the release community-patched to work on modern systems, which also does some modifications to the controls, as I can run only that on my system. Only saying as a disclaimer that something in the patches might have changed the camera handling.

However, the camera handling in that version is perfect, it still fulfills expectations of a gamer in 2020. Original Gothic could be played keyboard-only, using one hand, which is awesome. While I like that I can take a sip of water without pausing the game, I absolutely need there to be a proper mouse look nowadays. Like @progward says, the camera movement is smooth, even fluid, and it has a certain ending momentum to it. If you "swing" the camera around with the mouse, it quite quickly accelerates to a certain speed, then it rotates with that speed, after you finish swinging the mouse, the rotation slows down quite a bit, but there's a bit of momentum kept, only smoothly slowing down to a halt. I agree it's not easy to describe using words, haha.

The biggest difference of OpenGothic camera compared to that right now is that it gives an impression of being limited to 10 FPS or something - the game itself seems to run nicely, but the camera movement is choppy.

**Comment by Nindaleth** [comment]
An addition - the camera seems limited to something more like 20-30 FPS (sorry, the 10 FPS estimate was incorrect and far too harsh), compared to the original I find it too sensitive in the vertical motion and not sensitive enough in the horizontal motion.

**Comment by Try** [comment]
OK, let's break this down:
  1. "if your mouse scrolls from 0-1 in an instant, the ingame camera should do it in smaller steps 0.1, 0.2, 0.3 to 1"
  this is clear to me - each mouse event does fixed increment to camera zoom, have a patch ready for it
  2. " impression of being limited to 10 FPS or something "
  @Nindaleth is it a camera movement or npc rotation?
  Camera is delta-t based, so it should be smooth, but I'm not sure about player rotation

**Comment by Nindaleth** [comment]
I'm not sure I understand the difference, can I rotate the camera without rotating the player? I can tell, standing on the same spot in G2 and OG, that in OG I can see the little camera jumps even with ~30 FPS, while in G2 the camera just flows. That's when I'm looking left and right, might that be impacted by the player rotation?

Here's a video comparison (8 MB): [camera_movement.zip](https://github.com/Try/OpenGothic/files/5721747/camera_movement.zip)

**Comment by progward** [comment]
> 
> 
> I'm not sure I understand the difference, can I rotate the camera without rotating the player? I can tell, standing on the same spot in G2 and OG, that in OG I can see the little camera jumps even with ~30 FPS, while in G2 the camera just flows. That's when I'm looking left and right, might that be impacted by the player rotation?
> 
> Here's a video comparison (8 MB): [camera_movement.zip](https://github.com/Try/OpenGothic/files/5721747/camera_movement.zip)

When you hold "r" and look to the left and the right the head of the player should move with the camera in OG Gothic 2. If that helps.

**Comment by Nindaleth** [comment]
> When you hold "r" and look to the left and the right the head of the player should move with the camera in OG Gothic 2. If that helps.

Oh, that's good to know, thanks! It doesn't make any difference in smoothness, though.

I see that abbreviating OpenGothic to OG might quickly get ambiguous in English since the OG abbreviation is already used commonly for something else; I'll try to avoid that.

**Comment by Try** [comment]
> Here's a video comparison (8 MB): camera_movement.zip

Right, OpenGothic missing any kind of threshold on rotation speed - just finished a patch for it

> I'm not sure I understand the difference, can I rotate the camera without rotating the player? 

You controlling the hero, by mouse or keyboard. Camera follows hero position/rotation with some speed.
Effect is very noticeable, when moving - camera will catch-up to player only few second after movement is finished.

**Comment by Nindaleth** [comment]
Would it also be possible to decrease the sensitivity of vertical camera movement? I find it hard to look left/right without also looking up/down in OpenGothic (involuntarily, because I also very slightly move the mouse forward/backward in addition to left/right); I don't have that problem in the original.

I don't mean limiting the angular velocity per second, rather increasing the distance I have to physically move the mouse in that axis while keeping the rotation the same (if that makes sense).

**Comment by Nindaleth** [comment]
If I switch myself back on-topic and focus only on the zooming away from/closer to the character, there is a minor difference still between the (patched) original and OpenGothic. In both, if I rotate the mouse wheel by one notch, the amount of zoom gained/lost is very similar, no problem here.

The difference is, in OpenGothic the camera is at a certain zoom level, then the mouse wheel switches to the next notch, then the camera is switched to another level of zoom almost instantly (linear interpolation over 2 frames). In the original, there is a lot more tweening to the zoom level change, it's a non-linearly interpolated slide taking place over the next 20 frames - maybe a few more, the frame-to-frame difference at the end is getting imperceptible to me.

**Comment by Try** [comment]
> If I switch myself back on-topic and focus only on the zooming away from/closer to the character

Cool, but please update to at least 25cd34b revision - lately I made big amount of changes to on camera collision.

**Comment by Nindaleth** [comment]
My comment was based on [f81d3e5](https://github.com/Try/OpenGothic/commit/f81d3e5), but I'll try out the new one and report. I appreciate there's been a regular stream of improvements to camera handling over the last few weeks.

**Comment by Nindaleth** [comment]
Tested with 25cd34b - as far as following player when running or jumping, I like the current camera very much. When turning or zooming in and out, that fluidity is not there yet.

BTW, I applaud the camera collision work, I did a very quick test and previously problematic spots are now flawless!

**Comment by Eulenmensch93** [comment]
Compared the camera movement and zoom between open Gothic and the GoG version.
The camera zoom seems to be pretty close, the step distance for every mouse wheel input feels the same, the only noticeable difference for me is that the original (GoG version) seems to apply a ease in ease out calculation instead of a linear interpolation for the camera movement.
The makes the zooming feel much more smooth if only a single mouse wheel input is used, because the camera movement does not start and stop as hard.

For the camera rotation the difference is much more noticeably, especially if the character is running and a quick 180° turn is performed.
In the original the camera seems to be glued to the back of the character, so the character is in center of the camera most of the time, in open gothic the character seems to stop in one place and the character is running shortly without the camera following.

The second problem is hard to describe, I will try to make some some footage of both game version if possible.

**Comment by Try** [comment]
closing, since camera is adjusted to original game in #161
