### ISSUE TITLE
No animation for picking up items and looting

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#102]

**Comment by Try** [comment]
@progward  thanks for bug-reports 👍 

Reason: feature is not implemented
Implementation status:
Data decoding at prototype stage
  - ZenLoad::zCMorphMesh - mesh itself
  - ZenLoad::zCMorphMesh::aniList - list of animations

What is to-be-done:
  - Morph shading support in graphics-engine (not sure about software-design at this moment)
  - Daedalus API

**Comment by Try** [comment]
Animation is implemented;
TBD: add api for Daedalus script.

Entry points:
* Npc_GetHeightToItem
* Npc_GetDistToItem
* AI_TakeItem
* AI_GotoItem

**Comment by Try** [comment]
Done in 38857a2
