### ISSUE TITLE
No speaking animation (mouth not moving)

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#103]

**Comment by Try** [comment]
@progward  thanks for bug-reports 👍 

Reason: feature is not implemented
Implementation status:
Data decoding at prototype stage
  - ZenLoad::zCMorphMesh - mesh itself
  - ZenLoad::zCMorphMesh::aniList - list of animations

What is to-be-done:
  - Morph shading support in graphics-engine (not sure about software-design at this moment)
  - Daedalus API

**Comment by Try** [comment]
Done:
  All morph animation, including face animations, are working.
  Implementation supports up to 3 animation layers to be used simultaneously(can be expanded up to four, if need to).
  Added entry-point `Mdl_StartFaceAni`, for script.
  `Mdl_ApplyRandomFaceAni` - not added (game doesn't use it anyways)
