### ISSUE TITLE
Bodies of all npcs are transparent

### ISSUE THREAD

**Issue by okkindel** [Try/OpenGothic#109]
The bodies of all npc in the game are transparent.
System: Linux Mint 20
I am attaching the console logs and a screenshot:

> GPU = Intel(R) UHD Graphics (CML GT2)                                                                         
> Depth format = 14 Shadow format = 6                                                                           
> Info: ZEN: Reading world...                                                                                   
> Info: oCWorld reading chunk: MeshAndBsp                                                                       
> Info: ZEN: Reading mesh...                                                                                    
> Info: Reading mesh '' (Version: 265)                                                                          
> Info: Found 260696 vertices                                                                                   
> Info: ZEN: Done reading mesh!                                                                                 
> Info: oCWorld reading chunk: VobTree                                                                          
> Info: oCWorld reading chunk: WayNet                                                                           
> Info: Loading 1 freepoints                                                                                    
> Info: Loading 3402 edges                                                                                      
> Info: Done loading edges!                                                                                     
> no texture?!                                                                                                  
> unable to load animation "NW_MORPH_FISH_02.MMS"                                                               
> unable to load skeleton "NW_MORPH_FISH_02.MMS"                                                                
> unable to load animation "NW_MORPH_FISH_01.MMS"
> unable to load skeleton "NW_MORPH_FISH_01.MMS"
> unable to load animation "NW_MORPH_SKATE_01.MMS"
> unable to load skeleton "NW_MORPH_SKATE_01.MMS"
> unable to load sound fx: OW_BIRD11
> Info: Reading 20826 blocks
> /media/mhajduk/TOSHIBA EXT/GAMES/GOTHIC/OpenGothic/lib/ZenLib/daedalus/DATFile.h(281):[T& Daedalus::PARSymbol:
> :getValue(size_t, void*) [with T = int; size_t = long unsigned int]] DaedalusVM: base address of C_Class is nu
> llptr: C_NPC.AIVAR
> /media/mhajduk/TOSHIBA EXT/GAMES/GOTHIC/OpenGothic/lib/ZenLib/daedalus/DATFile.h(281):[T& Daedalus::PARSymbol:
> :getValue(size_t, void*) [with T = int; size_t = long unsigned int]] DaedalusVM: base address of C_Class is nu
> llptr: C_NPC.AIVAR

![image](https://user-images.githubusercontent.com/3685425/103156097-90d53580-47a5-11eb-9e8e-e8aaa508882c.png)

Taking this opportunity, thanks for a great job! I am watching the project and I am delighted with your commitment and I think it will soon be the default way of playing Gothic for many 💪🏻.

**Comment by Try** [comment]
Hi, @okkindel and thanks for bug-report!

I'm not 100% sure, but most likely it's a regression by 1378921.
Can you please check d2f1da7(the parent commit), if it works as expected ?

**Comment by okkindel** [comment]
Yup, it works perfectly :+1:

**Comment by Try** [comment]
Fixed:
  * add automatic buffer size deduction in `Tempest::Uniforms::set` 
  * OpenGothic source updated accordingly
