### ISSUE TITLE
Linux - Crash on Starting New Game or Loading Save

### ISSUE THREAD

**Issue by d10sfan** [Try/OpenGothic#115]
This appears to be related to this commit: https://github.com/Try/OpenGothic/commit/a9db3ba71b7d393d4175ba4e832916be35ff8828

The last successful commit I tried was 202f847

When I attempt to launch a new game or load an existing save, the game crashes. gdb shows the following trace:

~~~
Thread 1 "Gothic2Notr" received signal SIGSEGV, Segmentation fault.
0x000055555568ebdb in MenuRoot::keyUpEvent (this=0x7fffffffc2a0, e=...)
    at /__w/packages/packages/engines/opengothic/source/Game/ui/menuroot.cpp:116
~~~

**Comment by Try** [comment]
Right, thanks for reporting @d10sfan !

It's very unfortunate to find this only after release. I will to publish a new hot fix today.

**Comment by d10sfan** [comment]
Thanks, I built that and it looked like it worked.
