### ISSUE TITLE
Test DEVICE_LOCAL | HOST_VISIBLE memory heap

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#122]
Since this heap become more common I've decided to enable it in engine.
Unfortunately my GTX960M hardware does not support it (yet?), so I need some help with testing.

Testing: 
 1. verify that app does not crash
 2. check if there any visible performance improvement
 
Commit: c83f922
File/Line: vallocator.cpp:120

```c++
  uint32_t props[2] = {};
  uint8_t  propsCnt = 1;
  if(bufHeap==BufferHeap::Upload && usage==MemUsage::UniformBuffer) {
    propsCnt = 2;
    props[0] = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;  <-- HERE
    props[1] = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
    }
  else if(bufHeap==BufferHeap::Upload)
    props[0] = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
  else if(bufHeap==BufferHeap::Static)
    props[0] = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
  else if(bufHeap==BufferHeap::Readback)
    props[0] = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;

  for(uint8_t i=0; i<propsCnt; ++i) {
    VDevice::MemIndex memId = provider.device->memoryTypeIndex(memRq.memoryTypeBits,VkMemoryPropertyFlagBits(props[i]),VK_IMAGE_TILING_LINEAR);
    ^ VERIFY that memId.typeId is valid for i==0, when DEVICE_LOCAL | HOST_VISIBLE is requested.
    if(memId.typeId==uint32_t(-1))
      continue; 

    ret.page = allocMemory(memRq,memId.heapId,memId.typeId);
    if(!ret.page.page)
      continue;

    if(!commit(ret.page.page->memory,ret.page.page->mmapSync,ret.impl,ret.page.offset,
               mem,count,size,alignedSz)) {
      throw std::system_error(Tempest::GraphicsErrc::OutOfHostMemory);
      }
    return ret;
    }
```

**Comment by axel-dd** [comment]
Hi Try, first I want to thank you for your exzellent work on OpenGothic. I love this game. I grew up with it.

I compiled the current master d97d79f in Release mode. No crashes or bad performance so far. Let me know how I can help you testing this more in detail.

### system info

```
[System]
OS:              Manjaro Linux 20.2.1 Nibia
Arch:            x86_64
Kernel:          5.10.15-1-MANJARO
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: GeForce GTX 1070 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 460.39
OpenGL Core:     4.6.0 NVIDIA 460.39
OpenGL ES:       OpenGL ES 3.2 NVIDIA 460.39
Vulkan:          Supported
```

### vulkan info
[vulkaninfo.zip](https://github.com/Try/OpenGothic/files/5977952/vulkaninfo.zip)

**Comment by Try** [comment]
Hi, @axel-dd ! Thanks a lot for report!

> Let me know how I can help you testing this more in detail.

In principle, if it work on GTX 1070, then it works. One more thing you can do to verify it is to run the game in Debug mode and check how `vallocator.cpp` behaves:

a) Put break-point on vallocator.cpp:121
b) Once break-point fires, put next break-point on line 138
c) Once 138 line is reached - verify that `i==0`

^ `i==0` basically mean that memory was allocated from the first try, and first try is `DEVICE_LOCAL | HOST_VISIBLE`

**Comment by axel-dd** [comment]
done, no crash i was always zero.
tested in Debug and Release

**Comment by Try** [comment]
@axel-dd Thanks!
