### ISSUE TITLE
Bug or not yet implemented - G2 notr campfires not interactive, cannot use.

### ISSUE THREAD

**Issue by czarnyafgan** [Try/OpenGothic#150]

**Comment by Try** [comment]
Hi, @czarnyafgan !
Campfire, you mean campfire with frying pan or with scavenger-grill?
Both working for me in vanilla, possibly yet another issue related to mods?

**Comment by czarnyafgan** [comment]
Hi. campfire with frying pan, I will test it once again and let you know.

**Comment by Nindaleth** [comment]
Campfire with frying pan works on the current `master`.
