### ISSUE TITLE
Crash with no call frames available

### ISSUE THREAD

**Issue by Oblivionevil** [Try/OpenGothic#155]
After the intro Video it crash 

GPU = AMD Radeon RX 6900 XT
Depth format = 13 Shadow format = 5
Info: ZEN: Reading world...
Info: oCWorld reading chunk: MeshAndBsp
Info: ZEN: Reading mesh...
Info: Reading mesh '' (Version: 265)
Info: Found 260696 vertices
Info: ZEN: Done reading mesh!
Info: oCWorld reading chunk: VobTree
Info: oCWorld reading chunk: WayNet
Info: Loading 1 freepoints
Info: Loading 3402 edges
Info: Done loading edges!
unable to load sound fx: ENV_Night_TonsOfInsects
unable to load sound fx: OW_BIRD11
Info: Reading 20826 blocks

---crashlog(std::terminate)---
GPU: AMD Radeon RX 6900 XT
[no call frames available]

**Comment by Try** [comment]
Hi, @Oblivionevil and thanks for reporting!

Unfortunately it hard to say what exactly went wrong,without stacktrace, but at least this case is a good reason to review crash-logger and improve it

**Comment by Oblivionevil** [comment]
Fixed with new amd vulkan driver

**Comment by Try** [comment]
Cool! Thank you @Oblivionevil !
