### ISSUE TITLE
[Linux] Error while running make

### ISSUE THREAD

**Issue by Mufabo** [Try/OpenGothic#156]
error: null argument where non-null required (argument 2) [-Werror=nonnull]
  674 |   const bool all = (slot==nullptr || slot[0]=='\0');
      |                           ^~~~~~~
/home/mufabo/secondhdd/OpenGothic/game/game/inventory.cpp:687:19: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  687 |   if(all || slot==nullptr || stateSlot.slot==slot) {
      |                   ^~~~~~~
/home/mufabo/secondhdd/OpenGothic/game/game/inventory.cpp: In member function ‘void Inventory::putAmmunition(Npc&, size_t, std::string_view)’:
/home/mufabo/secondhdd/OpenGothic/game/game/inventory.cpp:700:50: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  700 |     owner.setAmmoItem(MeshObjects::Mesh(),nullptr);
      |                                                  ^
/home/mufabo/secondhdd/OpenGothic/game/game/inventory.cpp: In member function ‘void Inventory::implPutState(Npc&, size_t, std::string_view)’:
/home/mufabo/secondhdd/OpenGothic/game/game/inventory.cpp:716:51: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  716 |     owner.setStateItem(MeshObjects::Mesh(),nullptr);
      |                                                   ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:505: CMakeFiles/Gothic2Notr.dir/game/game/inventory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:543: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Try** [comment]
Hi, @Mufabo and thanks for report!

Look like transition from `char*` to `string_view` wasn't 100% perfect.
I have fixed what was possible to find manually (unfortunately MinGW doesnt have nonnull warning) - let me know, you face more issues

**Comment by Mufabo** [comment]
/home/mufabo/secondhdd/OpenGothic/game/gothic.cpp: In member function ‘void Gothic::startSave(Tempest::Texture2d&&, std::function<std::unique_ptr<GameSession>(std::unique_ptr<GameSession>&&)>)’:

/home/mufabo/secondhdd/OpenGothic/game/gothic.cpp:343:36: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  343 |   implStartLoadSave(nullptr,false,f);
      |                                    ^

/home/mufabo/secondhdd/OpenGothic/game/gothic.cpp: In member function ‘void Gothic::implStartLoadSave(std::string_view, bool, std::function<std::unique_ptr<GameSession>(std::unique_ptr<GameSession>&&)>)’:

/home/mufabo/secondhdd/OpenGothic/game/gothic.cpp:354:21: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  354 |   loadTex = banner==nullptr ? &saveTex : Resources::loadTexture(banner);
      |                     ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:609: CMakeFiles/Gothic2Notr.dir/game/gothic.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:545: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Mufabo** [comment]
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp: In member function ‘void MdlVisual::setSlotAttachment(MeshObjects::Mesh&&, std::string_view)’:
/home/fatih/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp:142:12: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  142 |   if(bone==nullptr || skeleton==nullptr)
      |            ^~~~~~~
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp: In member function ‘void MdlVisual::setSlotItem(MeshObjects::Mesh&&, std::string_view)’:
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp:191:12: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  191 |   if(bone==nullptr || skeleton==nullptr)
      |            ^~~~~~~
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp: In member function ‘void MdlVisual::dropWeapon(Npc&)’:
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp:287:53: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  287 |   auto it = npc.world().addItem(itm->clsId(),nullptr);
      |                                                     ^
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp: In instantiation of ‘void MdlVisual::rebindAttaches(MdlVisual::Attach<View>&, const Skeleton&, const Skeleton&) [with View = MeshObjects::Mesh]’:

/home/mufabosecondhdd/OpenGothic/game/graphics/mdlvisual.cpp:762:30:   required from here
/home/mufabo/secondhdd/OpenGothic/game/graphics/mdlvisual.cpp:777:17: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  777 |     if(mesh.bone==nullptr)

**Comment by Mufabo** [comment]
OpenGothic/game/graphics/mesh/animationsolver.cpp: In member function ‘const Animation::Sequence* AnimationSolver::solveFrm(std::string_view) const’:

OpenGothic/game/graphics/mesh/animationsolver.cpp:421:12: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  421 |   if(name==nullptr || name[0]=='\0')
      |            ^~~~~~~

cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:752: CMakeFiles/Gothic2Notr.dir/game/graphics/mesh/animationsolver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:545: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Mufabo** [comment]
OpenGothic/game/world/focus.cpp: In member function ‘std::string_view Focus::displayName() const’:
OpenGothic/game/world/focus.cpp:37:10: error: null argument where non-null required (argument 2) [-Werror=nonnull]
   37 |   return nullptr;
      |          ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:1506: CMakeFiles/Gothic2Notr.dir/game/world/focus.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:545: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Mufabo** [comment]
OpenGothic/game/world/objects/interactive.cpp: In member function ‘std::string_view Interactive::posSchemeName() const’:

OpenGothic/game/world/objects/interactive.cpp:391:10: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  391 |   return nullptr;
      |          ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:1558: CMakeFiles/Gothic2Notr.dir/game/world/objects/interactive.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:543: CMakeFiles/Gothic2Notr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Mufabo** [comment]
Are those errors easy to fix ? Maybe I can fix them myself

**Comment by Try** [comment]
Yes, should be relative easy to fix.
Root cause for all of them is switch from `const char*` to `string_view`. For old code `nullptr` use to be valid value, but not anymore.

Basically you can replace lines like:
`return nullptr; -> return ""`
`func(nullptr) -> func("")`
`str==nullptr || str[0]=='\0' -> str.empty()`

Only complex case is `std::snprintf`, but it should be already fixed everywhere.
