### ISSUE TITLE
Camera movement is headache-inducing

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#161]
I really am not able to describe what is wrong with the camera movements exactly (looking around with your mouse moving left or right), but it absolutely is not like in the original. 

Maybe this "fading" of the camera takes a bit too long, when you move your mouse, it shouldn't take a whole second for the camera to move with it, after you stopped moving the mouse. That for example.

**Comment by Try** [comment]
Camera in Gothic is tricky thing to get done:
  a) Vanilla has `CCamSys` for script api, with some leverage of control of camera behavior.
  b) `CCamSys` is poorly documented, leaving a lot to guess about how original game works.

I'm trying my best when guessing, but after a while eyesight becomes blurry. At this point literally can't see differences any more.
I'm marking this ticket as help wanted, for now.

**Comment by kuzy000** [comment]
I experimented with `CCamSys` values in the original game. And it looks like OpenGothic has a different camera algo.

For example, in the original game, the camera always looks at the target without any interpolation regardless of `CCamSys`. But the target follow the character smoothly. You can view it with `TOGGLE CAMDEBUG` console command.

I think next week I will make a pull request along with a description.

**Comment by Try** [comment]
@kuzy000 

>  But the target follow the character smoothly.

That is basically what OpenGothic does, by managing `Camera::state` and `Camera::dest`. From my point of view, the problem is in fact that we do it differently than original game.

Anyway looking forward for your pull-request :)

**Comment by ThielHater** [comment]
Couldn't you apply smoothing to the camera movement? I think this would help in general.

**Comment by Try** [comment]
> Couldn't you apply smoothing to the camera movement?

That was always in here

**Comment by Try** [comment]
Testing camera in original game:

https://user-images.githubusercontent.com/122894/135159958-a54fbc4a-fc4a-4ef0-9f90-b86337702dad.mp4

By the look of things:
1. Camera `focus` point is following player with linear speed, but with time lag (~0.5 sec)
2. Camera `origin` is driven by CCamSys settings, no interpolation here
2. Camera direction is depend on angle between `focus` and origin `points`
