### ISSUE TITLE
Improve camera when looting dead enemies

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#162]

**Comment by Try** [comment]
Hi, @progward !
What kind of animation do you mean? In vanilla there was no looting animation, when player loots monster or npc.

**Comment by progward** [comment]
Oh damn, you're right. That's embarrassing. But still something feels off when looting. Probably it's the camera kind of twitching around weirdly. I think in the original the camera behaves a bit differently. Camera gets reset in a smooth movement behind the character.

**Comment by Try** [comment]
Closing as duplicate of #161
