### ISSUE TITLE
Peasants piling up at Khorinis harbour

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#163]
Not sure how to better describe this. There are a lot of Khorinis citizen gathering (colliding) in the harbour of Khorinis, see attached screenshot. It appears as though they are walking in opposite directions on the same path and colliding.
![grafik](https://user-images.githubusercontent.com/86957596/124805635-10fe0400-df5c-11eb-879a-e47a55a15a0d.png)

**Comment by Try** [comment]
The problem appears to be quite complex:
  1. collision Bboxes are not exactly same as in vanilla 
  2. the bouncing behavior is not implemented
  3. PERC_MOVENPC is not implemented

I'll start with well understood \/not implemented stuff before addressing this "Khorinis harbour" case

**Comment by Abendlied** [comment]
I meanwhile did notice that this happens quite often, can easily be observed e.g. during militia guard exchange in the morning, both millitia guards collide during the exchange. 
It seems like the original game scripts have defined very specific walking paths for the NPCs relying on evasive capabilities, I think that is the bouncing behaviour. If that is not yet implemented in the engine, it is clear why this happens.

**Comment by Try** [comment]
Fixed: bouncing is still inexact, but it works good enough.
Tested by watching a day cycle in town on high speed.
