### ISSUE TITLE
Finalize quest-log support

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#172]
At this moment only topics can be seen, and only by clicking.
Needed:
- [x] Content view
- [ ] Scroll
 
![изображение](https://user-images.githubusercontent.com/122894/126843465-f14b0f4e-46d7-4b03-ab8e-099859b17738.png)

**Comment by bwajsowicz** [comment]
Hello @Try ! You can assign me to this issue - I'm working on it right now :)
