### ISSUE TITLE
Book stand not visible for fire mage quest

### ISSUE THREAD

**Issue by OrangeEye** [Try/OpenGothic#174]
The book stand in the libary of the fire mages is not visible and not interactable. It is required to read them as part of the quest series to become a fire mage.
![grafik](https://user-images.githubusercontent.com/36265644/126905594-60da5abd-bcae-4340-8dea-ab97d9fd3f26.png)

**Comment by Try** [comment]
Hi, @OrangeEye and thanks for bug reporting!

The issue was related to file-name resolving(again). Now should be fixed, since 7823951 you can continue with your save-game.
