### ISSUE TITLE
make failed at vcommandbuffer.cpp.o

### ISSUE THREAD

**Issue by OrangeEye** [Try/OpenGothic#175]
[error.txt](https://github.com/Try/OpenGothic/files/6881471/error.txt)
I followed the build guide for linux and got an error at the make step. 

I'm using cmake version 3.21.0

`[ 60%] Building CXX object lib/Tempest/Engine/CMakeFiles/Tempest.dir/gapi/vulkan/vcommandbuffer.cpp.o
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp: In function ‘VkAccessFlags layoutToAccess(VkImageLayout)’:
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:531:10: error: ‘VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL’ was not declared in this scope
     case VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:531:10: note: suggested alternative: ‘VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL’
     case VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:532:10: error: ‘VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL’ was not declared in this scope
     case VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:532:10: note: suggested alternative: ‘VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL’
     case VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:533:10: error: ‘VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL’ was not declared in this scope
     case VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:533:10: note: suggested alternative: ‘VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL’
     case VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:534:10: error: ‘VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL’ was not declared in this scope
     case VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lasse/Schreibtisch/Gothic/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vcommandbuffer.cpp:534:10: note: suggested 
[error.txt](https://github.com/Try/OpenGothic/files/6881468/error.txt)
alternative: ‘VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL’
     case VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
lib/Tempest/Engine/CMakeFiles/Tempest.dir/build.make:647: recipe for target 'lib/Tempest/Engine/CMakeFiles/Tempest.dir/gapi/vulkan/vcommandbuffer.cpp.o' failed
make[2]: *** [lib/Tempest/Engine/CMakeFiles/Tempest.dir/gapi/vulkan/vcommandbuffer.cpp.o] Error 1
CMakeFiles/Makefile2:908: recipe for target 'lib/Tempest/Engine/CMakeFiles/Tempest.dir/all' failed
make[1]: *** [lib/Tempest/Engine/CMakeFiles/Tempest.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Try** [comment]
Hi @OrangeEye !

What is your vulkan sdk version? You need to use at least 1.2.170 (or just latest).

**Comment by OrangeEye** [comment]
Ah, I didn't knew vulkan sdk was required. After installing it, it worked and also your bug fix with the books for the fire mages.

Thanks a lot!
