### ISSUE TITLE
v1.0.1123 About 20% of FPS loss compared to v1.0.1035 

### ISSUE THREAD

**Issue by czarnyafgan** [Try/OpenGothic#176]
Hello. I don't know if that's an issue, but I observe about 20% of FPS loss in newest version compared to older one. it's like 60 FPS compared to 73-75 FPS The loading times also seem to slow down a bit.

**Comment by Try** [comment]
Yes, that was already spotted: there was a performance issue related to physics; should be better on next release

**Comment by Try** [comment]
Should be fixed now, in 1.0.1177 release
