### ISSUE TITLE
Support for non Vulkan graphic cards 

### ISSUE THREAD

**Issue by gbudny** [Try/OpenGothic#190]
Hi

I build it on Ubuntu on my old Mac mini server 2010 with Geforce 320M, but I can't run because  this graphic card doesn't support Vulkan.

Why this project has completely different hardware requirements than the original game?

 I see Vulkan as the great option. However I think it shouldn't be the only option when user wants to run this game on the older computer.

**Comment by Try** [comment]
Hi, @gbudny !
Your question was partially answered here: #188 . In short: for old hardware we got vanilla, for modern machines we have OpenGothic, with better graphics, dynamic physics and other features.

About Vulkan:
There is API-abstraction layer in this project, that enables switch between api's (currently Vulkan/DirectX12/Metal). Each of those 3 api's are feature command-buffers, descriptor set's and gpu-compute, yet non of it is available in OpenGL 2.1 on your GPU.
