### ISSUE TITLE
Reproducible crash on Radeon 550

### ISSUE THREAD

**Issue by Eulenmensch93** [Try/OpenGothic#201]
Hi Tyr,

I switched from a Nvdia graphics card to a Radeon, and after installing Vulkan support for it on my system I got the game to start.
But after seeing the loading screen for about 0.5 seconds, I get a null pointer exception.
Looks like Tempest::Detail::VDevice::Queue::submit calls into the vulkan library, but the parameters are not initialized completely (at least that is my guess).

Since I do see the loading screen, I would assume it is not a general problem with my hardware or vulkan support.
And I also tried to build and run the last version I worked with for the dialog fix, to make sure that it is not a newly introduced problem.

Seems like I am not able to upload a core file here, so here is a screen shot of my gdb session (Binary build on commit f7e0e56a493a7bc7f1d4f257cd629b762ec18fdd with debug symbols to get a usable stack trace).

![image](https://user-images.githubusercontent.com/51380483/137627066-ea72dacd-d8b4-4531-96ef-f000588c5d32.png)

I would have expected that at least the pointer to the command buffers should be initialized in the struct?

If you need more information or debug information, feel free to tell me what I can do for you.

**Comment by Eulenmensch93** [comment]
Does not seem to fix the issue.

I will try to debug a bit more if I have the time in the next few days.
Also I had an error in the parameters of the program (loaded the wrong save file name), now I even see the main menu.
So rendering works to some degree, but the crash log is still identical :)

**Comment by Try** [comment]
OK, one line wasn't enough. Basically `imgCount` and `views.size()` are messed up.
Here is a popper patch: fa38456
