### ISSUE TITLE
Lobart farm entity misplacement

### ISSUE THREAD

**Issue by PolyMeilex** [Try/OpenGothic#205]
![img](https://user-images.githubusercontent.com/20758186/139558467-f9614092-21fc-4797-81ef-9d3db3bd0c7e.png)

Both collision box and model for this entity is somehow wrong. I was trying to figure out how did that heaped but failed so far, so I'm just opening an issue.

**Comment by Try** [comment]
Now on dev, animation is in some sort of work-in-progress state.
I remember, there was a issue with book on one of my commits, but should be good already

**Comment by PolyMeilex** [comment]
> Yes, the book stand is animated object :)

That's surprising, that explains why I failed to debug this, I would never think about that
