### ISSUE TITLE
Localization(?)

### ISSUE THREAD

**Issue by Asethon** [Try/OpenGothic#206]
Is the list of supported languages ​​the same as in the original version of the game?
I think it's no secret that Gothic is quite popular, apart from Germany, in Eastern European countries, especially in Poland and Russia.  Will there be any problems installing, for example, the Russian language into the game?

**Comment by Try** [comment]
Hi, @Asethon !

OpenGothic supports native, for vanilla gothic, (OU.dat) translation files, so answer to first question is yes. 
Also I've tested, a while ago, Russian and German languages on steam (+ru localization from Akella) - works fine for me.
