### ISSUE TITLE
MDS parse error

### ISSUE THREAD

**Issue by Reveares** [Try/OpenGothic#232]
I'm using for my project your version of ZenLib. While implementing mds animation parsing there seems to be an error with ZenLib. Well to be more precise the error is in the original `Wolf.mds` because in the following snippet
`````txt
	// Strafing
			ani			("t_FistRunStrafeL"			1	"t_FistRunStrafeL"		0.1	0.1	M.	"Wol_Jump_M01.asc"		F	61	77)
			{
			 	*eventSFX	(62	"WOL_AMBIENT_SHORT"	EMPTY_SLOT	)
				*eventSFXGrnd	(72	"Turn	)
			}
			ani			("t_FistRunStrafeR"			1	"t_FistRunStrafeR"		0.1	0.1	M.	"Wol_Jump_M01.asc"		F	81	97)
``````

`"Turn` is missing it's ending `"` tag. Not sure if this is different on other Gothic versions. But it seems like Gothic has no problem with parsing it. ZenLib also doesn't produce an error, but only loads some animations due to the messed up `"` tag.

Debugging `ZenLoad::MdsParser` reveals that the gfx `m_Name` is in fact `Turn\t)\r\n\t\t\t}\r\n\t\t\tani\t\t\t(` so it stops on the next found `"` tag.

I found this bug because for example the `s_Eat` ani was missing in my animation list.
Before digging deeper into the problem I wanted to ask if someone is aware of this problem and if it is handled in OpenGothic.
Adding the missing `"` tag to the mds fixes the problem of course, but the real fix would be to adjust ZenLib.

**Comment by Try** [comment]
Hi, @Reveares !

I'm guessing that 'wolf.mds' comes from Gothic1, right? In that can can confirm that G1 has this typo and our version of ZenLib doesn't handle that case well.

Strictly speaking '*eventSFXGrnd	(72	"Turn	)' is a syntax violation, but the problem is that it is vanilla content, and it's expected to work.

Proposed solution: disallow multiline string literals

**Comment by Reveares** [comment]
This typo exists in G1 and G2, atleast for the `wolf.mds`.
Thanks for fixing the problem so fast. Can confirm that this resolves the issue.
