### ISSUE TITLE
Keeping jump key pressed "freezes" character

### ISSUE THREAD

**Issue by ChristophHaag** [Try/OpenGothic#233]
Version 66f7c48713688607f05024bd8dd3b546282b409a, linux. Default jump key is alt and if I keep it pressed after the jump, the character is "frozen" like this until the jump key is released.

![Screenshot_20220101_171021](https://user-images.githubusercontent.com/781076/147854832-35a12aec-0de2-49b1-92cd-74fb563163ed.jpg)

I don't remember what the original behavior was, either go back to "walking mode" and ignore the pressed jump key until it is released and pressed again, or keep continuously jumping.

**Comment by Try** [comment]
> I don't remember what the original behavior was,

Testing now on steam: 
1. holding `jump` results in sequence of multiple jumps.
2. jumping in water results in jump-up animation
