### ISSUE TITLE
player and enemies can be catapulted high into the air

### ISSUE THREAD

**Issue by ChristophHaag** [Try/OpenGothic#234]
This has happened with the one goblin at the small starter lake, but it is probably easier to reproduce with the fence at the farm a little bit further on the way.

If you jump onto the fence in a way that traps the character, it seems you are supposed to get a gentle nudge upwards that dislodges you. If you keep the jump key pressed it is easy to keep stuck for longer (see #233) and it seems the longer you are stuck, the more force is applied to you and with some bad luck you are catapulted extremely high, which of course kills you on landing.

Intentionally getting stuck on the fence per #233 makes it easier to reproduce but I am quite sure it is not necessary and that you can get stuck in a way that gets you catapulted with a normal jump too.

**Comment by ChristophHaag** [comment]
I could still reproduce this btw, here caught on video https://www.youtube.com/watch?v=QghGdWmUoXM

**Comment by Try** [comment]
I've changed some math/constants to make effect more robust
d2c96da should fix issue from video

**Comment by ChristophHaag** [comment]
Thanks it's better now. I managed to get one strong push to the side, but I didn't manage to get killed or lose HP from a fall anymore, and that's the most important thing.
