### ISSUE TITLE
A single tree that is swaying way too much

### ISSUE THREAD

**Issue by ChristophHaag** [Try/OpenGothic#235]
At the farm at the beginning of the game. This tree:
![Screenshot_20220101_171059](https://user-images.githubusercontent.com/781076/147855061-6936764a-b171-4bca-ae8e-8975a1c3ee18.jpg)

**Comment by CaydenNostalrius** [comment]
same with about 50% of the trees right outside Xardas' tower. Just start a new game and you will immediately see a tree swinging through the tower :D

**Comment by Try** [comment]
Cant reproduce, this is how it looks on my setup (Steam+Eng):

https://user-images.githubusercontent.com/122894/150882015-cc814b8b-7c19-4658-84c8-641ceb6f6a9b.mp4

Note to myself:
Current implementation ignores *.ini file setup, need to fix that.
```
zWindEnabled=1
; ... enables (1) or disables (0) in-game wind for objects/trees etc. improves performance (especially on slow cpu's) (default: 1)

zWindCycleTime=4
zWindCycleTimeVar=2
zWindStrength=70
zWindStrengthVar=40
zWindAngleVelo=0.9
zWindAngleVeloVar=0.8
```

**Comment by ChristophHaag** [comment]
Just updated to latest master ae43fd1a4c9d151631da3d04f23fe7411a624db6, still happens here: https://youtu.be/bUAZ35Uqb24

on linux with gothic 2 steam version

**Comment by Try** [comment]
Hi, @ChristophHaag 
Can you specify language of the game (since steam ships slightly different builds, depend of translation)? Thanks!

**Comment by ChristophHaag** [comment]
german

**Comment by okkindel** [comment]
polish, stand alone (not steam) version has same issue.

**Comment by Try** [comment]
I've tried to run german, grerman(clean install), polish(steam) to no avail: trees are still behave same as in  https://github.com/Try/OpenGothic/issues/235#issuecomment-1020658926

Is there anything else, that can affect you setup? Any mods installed?

I've made attempt to review code: similar effect can happen, if world-file is damaged and has non-valid wind type. 982b823d - should help with that.

**Comment by ChristophHaag** [comment]
Hm I think that one tree is stopped doing it, but unfortunately it broke a whole lot of other trees https://www.youtube.com/watch?v=8PRQ1bAmX74

**Comment by Try** [comment]
Since I have a hard time reproducing, can you take a look on wind processing?
Here:
```c++
void ObjectsBucket::updatePushBlock(ObjectsBucket::UboPush& push, ObjectsBucket::Object& v) {
  ...
  if(v.wind!=ZenLoad::AnimMode::NONE) {
    ...
    switch(v.wind) {
      case ZenLoad::AnimMode::WIND:
        // tree
        a *= v.windIntensity; // on my instance value is always 0.3 
        a *= 0.1f;
        break;
      case ZenLoad::AnimMode::WIND2:
        // grass
        a *= v.windIntensity; // on my instance value ranges 0 ... 0.001 
        a *= 5.f;
        break;
      case ZenLoad::AnimMode::NONE:
      default:
        // error
        a *= 0.f;
        break;
      }
    push.pos[1][0] += scene.windDir.x*a;
    push.pos[1][2] += scene.windDir.y*a;
    }
```
We might need to disable `windIntensity`, if this value is not consistent across different game installments

**Comment by Try** [comment]
Potentially here can be same issues as in 206244c / 8f325376.
In ZenLib bit-packaging was used together with `pragma pack` - that produce unexpected data layout on apple/clang, So can be same here - depend of compiler.
