### ISSUE TITLE
The running attack sometimes (more often than not) stops the character.

### ISSUE THREAD

**Issue by fhanrath** [Try/OpenGothic#239]
When performing a running attack the character stops sometimes.

https://user-images.githubusercontent.com/33193081/148700926-9b820fbd-a9c3-4924-9f69-b065d3de0151.mp4

This occurs in both, G1 and 2 control schemes. With the G1 scheme I wasn't able to do a normal running attack. Additionally the attack sound seems to play twice and sometimes the character does a normal attack afterwards.

https://user-images.githubusercontent.com/33193081/148701135-262a104c-a82e-4cd3-8dd6-8249beaed3d6.mp4

In both videos I just pressed w to run forward for the entire duration and did one mouseclick for each running attack.

**Comment by Try** [comment]
Manage to reproduce:
Animation stops only, if G1 controls are disabled.
with G1 controls enable - works fine
