### ISSUE TITLE
68% compiling amd64 Ubuntu-Mint 19 FAIL.

### ISSUE THREAD

**Issue by dj--alex** [Try/OpenGothic#242]
https://youtu.be/qav70UVDjfI
Im just do steps from github page.
Linux Mint 19.3 kernel 5.15, Nvidia 495, RTX 3060 

Sorry only video. 
I tries compile linux version and tries use windows version under wine. All fails.  Trying run .exe through steam but failed. 

Please add release .deb for all Mint/Debian/Ubuntu/Steam OS users
Temporary release better than NO release.

**Comment by Try** [comment]
Hi, @dj--alex !

I've check-out the video:
Build error is not shown - it's hidden by following messages in terminal. Please send full compilation log, if you not sure what error it is.

For wine - it show "gothic not found", means path to game is not valid. On your setup should be something, like:
`Gothic2Notr -g "/media/user/PC1-DAT/Game/Gothic II" `

> Please add release .deb for all Mint/Debian/Ubuntu/Steam OS users
Temporary release better than NO release.

I know, it's just something that needs to be done.

**Comment by dj--alex** [comment]
Okay - here is it - https://pastebin.com/S53sp3W9

as alternative
i try command - wine Gothic2Notr.exe -g "/media/user/PC1-DAT/Game/GothicII"
titles with authors of game if run it without seeing anything - is works. 
works only titles of authors. 

But i get Black screen and no game.  i have logs buy is seems useless

**Comment by Try** [comment]
It seems your build issue is due to old version of vulkan-sdk:
```
/media/user/PC1-DAT/Game/Gothic II/openg_linux/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vdevice.h:238:5: error: ‘PFN_vkCmdPipelineBarrier2KHR’ does not name a type; did you mean ‘PFN_vkCmdPipelineBarrier’?
     PFN_vkCmdPipelineBarrier2KHR          vkCmdPipelineBarrier2KHR       = nullptr;
```
You need to install at least version 1.2.170.0 to build the game.
