### ISSUE TITLE
Ubuntu vulkan-sdk documentation

### ISSUE THREAD

**Issue by RvNovae** [Try/OpenGothic#255]
Hello, I had some trouble building earlier on.
I did manage to resolve it thanks to https://github.com/Try/OpenGothic/issues/252#issuecomment-1039618250.

Following the instructions on the lunarg website, I got it to build on Ubuntu 20.04 after issuing these commands:

```bat
wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
sudo apt update
sudo apt install vulkan-sdk
```

Perhaps this kind of information could be added to the build instructions in the documentation?

**Comment by okkindel** [comment]
Yeah, it helped me a lot. We should add it to README @Try

**Comment by Try** [comment]
Added instructions about latest sdk
