### ISSUE TITLE
Aim of this project is not clear

### ISSUE THREAD

**Issue by Pandiora** [Try/OpenGothic#26]
Hey there,

this might be a noob question but I wanted to ask what's the goal of your project. This project got mentioned on reddit and worldofplayers and by REGoth devs and I'm unsure what to expect. You write DX11 can't be run with this "client-app" but you will provide some graphical features like shadows it seems. I wonder if this could compete with DX11 mod and if it would be as good or better performance-wise.

Here in short what I would expect of a reimplementation:
- better performance, so game could be run on modern hardware w/o bottlenecking
- graphical features like shadows, grass, HBAO, tesselation and so on
- cross-platform playability or at least smooth to be run on W10

Greets

**Comment by Try** [comment]
Hi!
I have two answers for your main question: short and long.
In short: aim of the project to fix my small issue - original Gothic2 doesn't work run properly on my laptop.

Long: first step is to to develop reliable, feature-complete game/game-engine for gothic.
From that 'checkpoint' we, as gothic community, can start to look forward for advanced features, like:
- Better game physic
- Linux/Mac support
- Better world-editor
- Script interactive debugger
- < Your feature > - just fork it

Performance-wise: performance is at second priority at this point. 
CPU performance is already quite good, need to do some work on GPU. Anyway, for now I have 40fps in Khorinis, and 60 on other locations. And there still a lot of room for optimizations.

Graphics-wise: there still much to do, but project has everything it need to became even better then dx11-mod: I have all info about materials and world in general, and Vulkan is more advanced then DX11.

**Comment by Pandiora** [comment]
Thanks for your answer, appreciated.

Sadly I don't think I could be of much help, especially when it comes to adding new features, since I'm not such a good coder and never worked in game development.

I'm still looking for alternatives and even better polished reworks of Gothic I & II and ended up here. :laughing: It's quite interesting how REGoth, OpenGothic and DX11 (this one might not be right in this comparison) compete and I hope this competition leads to even more improvements. For me (I'm still owning R9 280) Gothic II bottlenecks my GPU (with DX11) and there are still unpleasant graphical bugs. You're very self-confident depending Vulkan, but that's the spirit. Maybe one day I can play Gothic II in HD on my Linux Notebook utilizing Proton. (I can, but the performance is bad with Ryzen 3500 [APU])

You're relatively far it seems and if you need some help at testing or anything else, let me know. I will need to spend more time to understand how all the APIs and such work together and what you guys are actually doing.

**Comment by Pandiora** [comment]
I'm closing this for now, since the aim of your project and ideas for the future should be clear now.
