### ISSUE TITLE
GPU driven rendering

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#266]
Goal of this ticket to prototype, implement and test GPU-driven rendering.

GPU driven allowed for better quality of invisible geometry culling, and can potentially reduce CPU load.

Current idea:
 1. Take task/mesh shader as baseline
 2. Test on native hardware
 3. Implement backport for Vulkan1.0 hardware, if idea works

Implementation detail (so far):
  - [x] Pack object into instanced-calls (full bucket for task-capable, only visible for everyone else)
  - [x] Repack landscape into clusters of 64 vertices + 126 primitives (NVIDIA [guideline](https://developer.nvidia.com/blog/introduction-turing-mesh-shaders/))
  - [x] Use bounding sphere(one per meshlet) to cull geometry in main pass
  - [ ] Add visibility cone culling for shadow-pass
  - [x] HiZ ?

Baseline:
![изображение](https://user-images.githubusercontent.com/122894/167929524-6a2c322a-76df-4fbf-806b-06517b08b74f.png)

Main-pass 1.51ms
Shadows 0.35 + 0.85
RayTracing pass 2.27 ms

**Comment by Try** [comment]
Meshlet packing:
![изображение](https://user-images.githubusercontent.com/122894/167931974-2b6aee24-3220-46b8-93d8-6376158d0776.png)

Note: non-landscape objects are black

**Comment by Try** [comment]
![изображение](https://user-images.githubusercontent.com/122894/168431380-e17350df-c24b-4e9f-b8a6-78512714fdde.png)

Main-pass 1.81 ms
Shadows 0.32 + 0.71
Drawcall decreased by ~700 calls.

With meshshader execution barrier becomes an issue: `shadow` -> `main pass` barrier takes 1ms
For now works slightly slower than CPU culling,

**Comment by Try** [comment]
Note:
It seems `gl_PrimitiveIndicesNV` can be limiting factor in a way:

In spec `gl_PrimitiveIndicesNV[]` must have size that matches exactly `max_primitives*triangles`, and unfortunately never more.

For mesh block-compression scheme it world be way better to have out-of-bounds access on this array(or option to redeclarate it with bigger size)

**Comment by Try** [comment]
![изображение](https://user-images.githubusercontent.com/122894/168493743-44b42597-49da-4763-870a-98f39674944e.png)

With pack-algorithm fixup:
Main-pass 1.36 ms
Shadows 0.34 + 0.67

**Comment by Try** [comment]
Some progress on task shader:
![изображение](https://user-images.githubusercontent.com/122894/168923699-cdc2b996-f660-4ae9-9925-1eff5f741c2f.png)

Main pass actually became slower, but good part is draw-call count:
now whole frame takes 85 draw-calls instead of 2.3k.

**Comment by Coockie** [comment]
Is this a optimisation for new hardware like Nvidia Turing and Ampere and AMD RDNA2?

**Comment by Try** [comment]
@Coockie this iteration - yes only for latest hardware. Once culling algorithm is more-less complete and numbers are good we will expand to older hardware.

The way I'm planning to backport mesh shaders to Vulkan1.0 is based on this idea: https://tellusim.com/mesh-shader-emulation/

Basically set of compute-shaders + draw-indirect + software binner

**Comment by Try** [comment]
Who needs task shading? Just draw more meshlets:
![изображение](https://user-images.githubusercontent.com/122894/169109306-05ce7c11-7766-4379-a54d-d5f5cf3d86c1.png)

So far best iteration:
  * 85 drawcalls in total
  * main-pass 1.32
  * shadow1 - 0.67
  * shadow0 - 0.30

**Comment by Try** [comment]
Add meshlets for skinned meshes:
![изображение](https://user-images.githubusercontent.com/122894/169715067-f0e49af8-2d05-4aa4-acb3-2a7870aa1388.png)

Not great, not worse, timings, except for draw-call count. Basically looking forward to HiZ support

**Comment by Try** [comment]
Initial HiZ: only 32x32 tile size generated, with no mip-map chain for now
Main-pass: 1.1
![изображение](https://user-images.githubusercontent.com/122894/170844498-60e8c24d-85e7-4f72-a4d2-8ddb6e5e4ff0.png)

**Comment by Try** [comment]
Progress in HiZ. Overdraw:

* Without:
![изображение](https://user-images.githubusercontent.com/122894/171446037-ae2f8f50-1064-4b69-8105-bf080ce1c2ef.png)

* With:
![изображение](https://user-images.githubusercontent.com/122894/171446071-72298c3a-f544-4b05-80fd-388d3773694b.png)

Small waley behind the farm(center) and stuff occluded by mountain(left) was removed

Still there is performance issue: reading HiZ with textureGather(mip=0)/texelFetch*4 is not performant.

**Comment by Try** [comment]
Wrapping up for now:
System-trace profiler shows very odd numbers: rendering is faster, but barriers are terribly large (~1ms see above). Frame profiler shows else picture. According to frame-profiler meshlets 12% faster.

In the end of the day: base-fps = 170, mesh fps = 204. So meshlets are good.

Meshlets:
![изображение](https://user-images.githubusercontent.com/122894/173185621-e3c5c6ca-ced6-4484-879e-e0294ce42c96.png)
Drawcalls:
![изображение](https://user-images.githubusercontent.com/122894/173185736-d9613866-ce93-4310-a941-7cdec76592bc.png)

|    | Meshlets  | Drawcalls  |  
|---|---|---|
| Fps  |  204 | 170  |  
|  Triangles | 102316  | 3184884 |  
|  Drawcalls | 19 | 4766 |  

Sys-trace:
![изображение](https://user-images.githubusercontent.com/122894/173185865-40e9243f-4018-4968-a66e-7ae480b4a6ee.png)
(Note: no idea what nsight displays as draw-call count. it's definitely not 19. Probably it's pipeline switches)

**Comment by Try** [comment]
Overdraw visualization:
Baseline:
![изображение](https://user-images.githubusercontent.com/122894/173187105-8bf75526-140e-4867-8230-5aa281e6a47b.png)
Meshlets:
![изображение](https://user-images.githubusercontent.com/122894/173187122-34502038-3209-4c01-b2b3-cdd7d43b57d5.png)
