### ISSUE TITLE
Missing VOB documentation

### ISSUE THREAD

**Issue by lmichaelis** [Try/OpenGothic#267]
Hey there,
I noticed that you're missing documentation about some VOBs in [the wiki](https://github.com/Try/OpenGothic/wiki/VOBS-&-Triggers). Since I've been working on a proper file format Wiki (I can't find a complete one anywhere) I've been [tinkering](https://github.com/lmichaelis/phoenix) a bit. Here are all missing/broken definitions I'm aware of; I hope it helps in some way :)

Note that I've added some comments where necessary. You might want to remove them before adding these definitions to the Wiki.

### zCVob
**Added lots of missing fields**
```cpp
struct zCVob {
    string presetName;
    bBox   bbox3DWS;
    zMAT3  trafoOSToWSRot;
    zVEC3  trafoOSToWSPos;
    string vobName;
    string visual;
    bool   showVisual;
    enum   visualCamAlign;

#ifndef GOTHIC2
    bool cdStatic;
    bool cdDyn;
    bool staticVob;
    bool dynamicShadow;
#elif
    enum  visualAniMode;
    float  visualAniModeStrength;
    float  vobFarClipZScale;
    bool  cdStatic;
    bool  cdDyn;
    bool  staticVob;
    bool  dynamicShadow;
    float  zBias;
    bool  isAmbient;
#endif
    };
```

### oCMobInter
**`rewind` was missing!**
```cpp
struct oCMobInter : oCMOB {
    int    stateNum;
    string triggerTarget;
    string useWithItem;
    string conditionFunc;
    string onStateFunc;
    bool   rewind;
    };
```

### oCMobDoor
```cpp
struct oCMobDoor : oCMobInter {
    bool locked;
    string keyInstance;
    string pickLockStr;
    };
```

### zCPFXControler
```cpp
struct zCPFXControler : zCVob {
    string pfxName;
    bool   killVobWhenDone;
    bool   pfxStartOn;
    };
```

### zCVobAnimate
```cpp
struct zCVobAnimate : zCVob {
    bool startOn;
    };
```

### zCVobLensFlare
```cpp
struct zCVobLensFlare : zCVob {
    string lensflareFX;
    };
```

### zCVobLight
```cpp
struct zCVobLight : zCVob {
    string lightPresetInUse;
    enum   lightType;
    float   range;
    color  color;
    float   spotConeAngle;
    bool   lightStatic;
    enum   lightQuality;
    string lensflareFX;
    
    // all below only apply if lightStatic == true
    bool   turnedOn;
    string rangeAniScale;
    float   rangeAniFPS;
    bool   rangeAniSmooth;
    string colorAniList;
    float   colorAniFPS;
    bool   colorAniSmooth;

#ifdef GOTHIC2
    bool canMove;
#endif
    };
```

### zCVobSound
**`sndType` is called `sndMode`!**
```cpp
struct zCVobSound : zCVob {
    float  sndVolume;
    enum   sndMode;
    float  sndRandDelay;
    float  sndRandDelayVar;
    bool   sndStartOn;
    bool   sndAmbient3D;
    bool   sndObstruction;
    float  sndConeAngle;
    enum   sndVolType;
    float  sndRadius;
    string sndName;
    };
```

### zCZoneZFog
```cpp
struct zCZoneZFog : zCVob {
    float fogRangeCenter;
    float innerRangePerc;
    color fogColor;
#ifdef GOTHIC2
    bool fadeOutSky;
    bool overrideColor;
#endif
    };
```

### zCZoneZFogDefault
```cpp
struct zCZoneZFogDefault : zCZoneZFog {};
```

### zCZoneVobFarPlane
```cpp
struct zCZoneVobFarPlane : zCVob {
    float vobFarPlaneZ;
    float innerRangePerc;
    };
```

### zCZoneVobFarPlaneDefault
```cpp
struct zCZoneVobFarPlaneDefault : zCZoneVobFarPlane {};
```

### zCCodeMaster
**Here `triggerTargetFailure` and `untriggerCancels` were in the wrong order! You should check the appropriate C++ code-section if this is done there as well!**
```cpp
struct zCCodeMaster : zCVob {
    string   triggerTarget;
    bool     orderRelevant;
    bool     firstFalseIsFailure;
    string   triggerTargetFailure;
    bool     untriggerCancels;
    string[] slaveVobName;
    };
```

### oCCSTrigger
**This also exists but has the same fields as `zCTrigger`**
```cpp
struct oCCSTrigger : zCVob {
    string  triggerTarget;
    uint8_t flags;
    uint8_t filterFlags;
    string  respondToVobName;
    int     numCanBeActivated;
    float   retriggerWaitSec;
    float   damageThreshold;
    float   fireDelaySec;
    };
```

### zCMover
**Issue: `moveSpeed`, `posLerpType`, `speedType` and `keyframes` only apply if the `numKeyframes` read immediately beforehand is greater than 0**

### zCTriggerList
```
struct zCTriggerList::Entry final {
    string triggerTarget{id};
    float  fireDelay{id};
    };
// Fire delay is not implemented 
struct zCTriggerList : zCTrigger {
    int32   listProcess;
    Entry[] list;
    };
```

### zCTriggerWorldStart
```cpp
struct zCTriggerWorldStart : zCVob {
    string triggerTarget;
    bool fireOnlyFirstTime;
    };
```

### zCMessageFilter
```cpp
struct zCMessageFilter : zCVob {
    string triggerTarget;
    enum onTrigger;
    enum onUntrigger;
    };
```

### oCTouchDamage
```cpp
struct oCTouchDamage : zCVob {
    float damage;
    bool Barrier;
    bool Blunt;
    bool Edge;
    bool Fire;
    bool Fly;
    bool Magic;
    bool Point;
    bool Fall;
    float damageRepeatDelaySec;
    float damageVolDownScale;
    enum damageCollType;
    };
```

### zCTriggerUntouch
```cpp
struct zCTriggerUntouch : zCVob {
    string triggerTarget;
    };
```

### zCCSCamera
```cpp
struct zCCamTrj_KeyFrame : zCVob {
    float time;
    float angleRollDeg
    float camFOVScale
    enum motionType
    enum motionTypeFOV
    enum motionTypeRoll
    enum motionTypeTimeScale
    float tension
    float bias
    float continuity
    float timeScale
    bool timeIsFixed
    zMAT4 originalPose;
    };

struct zCCSCamera : zCVob {
    enum camTrjFOR;
    enum targetTrjFOR;
    enum loopMode;
    enum splLerpMode;
    bool ignoreFORVobRotCam;
    bool ignoreFORVobRotTarget;
    bool adaptToSurroundings;
    bool easeToFirstKey;
    bool easeFromLastKey;
    float totalTime;
    string autoCamFocusVobName;
    bool autoCamPlayerMovable;
    bool autoCamUntriggerOnLastKey;
    float autoCamUntriggerOnLastKeyDelay;
    int numPos;
    int numTargets;

    // Quirk: these are sub-objects of the `zCCSCamera:zCVob` object
    zCCamTrj_KeyFrame[] frames;
    };
```

**Comment by lmichaelis** [comment]
Actually sorry, I forgot two Vobs you missed:

### zCEarthquake
```cpp
struct zCEarthquake : zCVob {
    float radius;
    float timeSec;
    zVEC3 amplitudeCM;
    };
```

### zCMoverControler
```cpp
struct zCMoverControler : zCVob {
    string triggerTarget;
#ifndef GOTHIC2
   enum moverMessage;
#elseif
   byte moverMessage;
#endif
    int gotoFixedKey;
    };
```

**Comment by Try** [comment]
Hi, @lmichaelis , and thanks for report!

Atm I'm on a road - will proper review, once at home.
Quickly checked C++ side:
* zCVobSound - outdated doc, mismatch in c-name and parsed name
* oCMobInter, zCCodeMaster, oCCSTrigger, zCMover - missing doc

So yeah wiki is somewhat outdated.
Also cool project https://github.com/lmichaelis/phoenix, that you mention. Intent is to replace old ZenLib with new, better written library? Curious because I'm not quite happy with ZenLib legacy-code.

**Comment by lmichaelis** [comment]
It would be cool if we could integrate. It would be a lot of work but if you're interested, I can look into it :> I love fixing up systems and making them better.

`phoenix` is supposed to be a safer and more complete implementation of ZenLib especially in regards to the Daedalus VM. I also provide a bunch of tools to exporting and analyzing files which I intend to expand on as well.

For example `pxscrdump` can display symbols and bytecode of compiled Daedalus scripts for which I intend to write a compiler too:

![image](https://user-images.githubusercontent.com/20187490/170017433-81659a0f-cfcb-4b4e-99ce-c1918323a7ae.png)

![image](https://user-images.githubusercontent.com/20187490/170020573-63cebd9c-a9bf-4d3b-8de6-67840a7dd0f9.png)

**Comment by Try** [comment]
Finally updated the doc!
Thanks again for noticing.

> It would be cool if we could integrate. It would be a lot of work but if you're interested, I can look into it :> 

Feel free to create followup ticket ;) On my side very welcome - diversification is important for open-source project
