### ISSUE TITLE
Crash with Gothic II (GOG)

### ISSUE THREAD

**Issue by ThielHater** [Try/OpenGothic#27]
When I try to start OpenGothic, the window opens and closes a second later. This is all what's written into crash.log:

> ---crashlog(ExceptionFilter)---
GPU: 
0x00486ce2: CrashLog::dumpStack(char const*) in C:\open_gothic\bin\Gothic2Notr.exe
0x00486ac9: __ZL16exceptionHandlerP19_EXCEPTION_POINTERS@4 in C:\open_gothic\bin\Gothic2Notr.exe
0x7640a4eb: UnhandledExceptionFilter in C:\WINDOWS\System32\KERNELBASE.dll
0x76f8302c: RtlCaptureStackContext in C:\WINDOWS\SYSTEM32\ntdll.dll
0x76f465fd: RtlGetAppContainerNamedObjectPath in C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by Try** [comment]
Hm, it's going to be tough to find out what really happen.
Only thing clear - this is native-exception and crash before construction of MainWindow. Need to find way to collect stack for this case.

@ThielHater  is it possible for you to build&run debug version of game? If yes - stacktrace is going to be very helpful. Thanks!

**Comment by ThielHater** [comment]
I tried building it, first edd-dbg failed and then MoltenTempest. Why is it so hard for some projects to make sure, that the latest version of their code can at least be build? That's beyond me, sorry.

> In file included from C:/Users/Pierre/Desktop/OpenGothic/lib/MoltenTempest/Engine/include/Tempest/VertexBuffer:1:0,
                 from C:\Users\Pierre\Desktop\OpenGothic\lib\MoltenTempest\Engine\2d\paintdevice.h:5,
                 from C:\Users\Pierre\Desktop\OpenGothic\lib\MoltenTempest\Engine\2d\paintdevice.cpp:1:
c:\users\pierre\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:30: error: 'vector' in namespace 'std' does not name a template type
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                              ^~~~~~
c:\users\pierre\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:36: error: expected ',' or '...' before '<' token
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                                    ^
c:\users\pierre\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h: In member function 'void Tempest::VertexBufferDyn<T>::update(int)':
c:\users\pierre\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:90: error: 'v' was not declared in this scope
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                                                                                          ^
lib\MoltenTempest\Engine\CMakeFiles\MoltenTempest.dir\build.make:76: recipe for target 'lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/2d/paintdevice.cpp.obj' failed
mingw32-make.exe[2]: *** [lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/2d/paintdevice.cpp.obj] Error 1
CMakeFiles\Makefile2:475: recipe for target 'lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/all' failed
mingw32-make.exe[1]: *** [lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by ThielHater** [comment]
I tried building it, first edd-dbg failed and then MoltenTempest. Why is it so hard for some projects to make sure, that the latest version of their code can at least be build? That's beyond me, sorry.

> In file included from C:/Users/MyUsername/Desktop/OpenGothic/lib/MoltenTempest/Engine/include/Tempest/VertexBuffer:1:0,
                 from C:\Users\MyUsername\Desktop\OpenGothic\lib\MoltenTempest\Engine\2d\paintdevice.h:5,
                 from C:\Users\MyUsername\Desktop\OpenGothic\lib\MoltenTempest\Engine\2d\paintdevice.cpp:1:
c:\users\MyUsername\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:30: error: 'vector' in namespace 'std' does not name a template type
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                              ^~~~~~
c:\users\MyUsername\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:36: error: expected ',' or '...' before '<' token
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                                    ^
c:\users\MyUsername\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h: In member function 'void Tempest::VertexBufferDyn<T>::update(int)':
c:\users\MyUsername\desktop\opengothic\lib\moltentempest\engine\graphics\vertexbuffer.h:43:90: error: 'v' was not declared in this scope
     void   update(const std::vector<T>& v)                    { return this->impl.update(v.data(),0,v.size()*sizeof(T)); }
                                                                                          ^
lib\MoltenTempest\Engine\CMakeFiles\MoltenTempest.dir\build.make:76: recipe for target 'lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/2d/paintdevice.cpp.obj' failed
mingw32-make.exe[2]: *** [lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/2d/paintdevice.cpp.obj] Error 1
CMakeFiles\Makefile2:475: recipe for target 'lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/all' failed
mingw32-make.exe[1]: *** [lib/MoltenTempest/Engine/CMakeFiles/MoltenTempest.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by Try** [comment]
It's just missing includes - typical for c++ codebase. 
You using ming64, right?

**Comment by Try** [comment]
manage to reproduce similar build issues with mingw7.3_x64

**Comment by ThielHater** [comment]
I took a look at your appveyor.yml and it mentions "mingw530_32". Therefore I tried compiling OpenGothic with mingw v6.3 x86 which isn't exactly the same but one major version difference - what could possibly go wrong? :D

Thank for the fixes, I was able to successfully build OpenGothic with mingw 7.3 x64 as you suggested. This is the log's content:

`---crashlog(SIGABRT)---
GPU: 
0x00000000005d37f9: dbg::call_stack<64u>::collect(unsigned int) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004b253f: CrashLog::dumpStack(char const*) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004b23be: signalHandler(int) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00007ffdb9acae8b: raise in C:\WINDOWS\System32\msvcrt.dll
0x00007ffdb9acf28b: abort in C:\WINDOWS\System32\msvcrt.dll
0x00000000004b23e6: terminateHandler() in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000006fc57288: ZN10__cxxabiv111__terminateEPFvvE in C:\Users\MyUsername\Desktop\OpenGothic\bin\libstdc++-6.dll
0x000000006fcff503: ZSt9terminatev in C:\Users\MyUsername\Desktop\OpenGothic\bin\libstdc++-6.dll
0x000000006fd07d92: _cxa_throw in C:\Users\MyUsername\Desktop\OpenGothic\bin\libstdc++-6.dll
0x000000006b48f9d9: ZN7Tempest5RFile8implOpenEPKw in C:\Users\MyUsername\Desktop\OpenGothic\bin\libMoltenTempest.dll
0x000000006b48f8d6: ZN7Tempest5RFileC1EPKDs in C:\Users\MyUsername\Desktop\OpenGothic\bin\libMoltenTempest.dll
0x000000006b48f92e: ZN7Tempest5RFileC2ERKNSt7__cxx1112basic_stringIDsSt11char_traitsIDsESaIDsEEE in C:\Users\MyUsername\Desktop\OpenGothic\bin\libMoltenTempest.dll
0x0000000000469ae3: Gothic::createVm(char16_t const*) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000000040e77c: FightAi::FightAi(Gothic&) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x0000000000468012: Gothic::Gothic(int, char const**) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000000048d9a7: main in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004013c7: __tmainCRTStartup in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004014fb: mainCRTStartup in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00007ffdb9827974: BaseThreadInitThunk in C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffdbc10a271: RtlUserThreadStart in C:\WINDOWS\SYSTEM32\ntdll.dll
`

**Comment by Try** [comment]
> what could possibly go wrong?
Seems 2 thing is went wrong:
1) -g <path/to/gothic2>- you have specifier path to original gothic (for scripts and assets)
2) I have to develop a way to inform user about path mismatch.

**Comment by ThielHater** [comment]
I'm sorry, but I think you've come to the wrong conclusion. Your run.bat points to Gothic 2 from Steam while I've installed Gothic 2 from GOG.com and of course I modified the path accordingly!

However, I just noted that the dir path in your run.bat doesn't end with a backslash but mine does. So I removed it and the stacktrace changed:

> ---crashlog(SIGSEGV)---
GPU: 
0x00000000005d37f9: dbg::call_stack<64u>::collect(unsigned int) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004b253f: CrashLog::dumpStack(char const*) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004b23be: signalHandler(int) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000005aa427: _gnu_exception_handler in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00007ffdbc12fd56: _C_specific_handler in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffdbc14477f: _chkstk in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffdbc0a4bef: RtlWalkFrameChain in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffdbc1434ee: KiUserExceptionDispatcher in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffdbc0a9a9d: RtlEnterCriticalSection in C:\WINDOWS\SYSTEM32\ntdll.dll
0x000000000058f47d: __PHYSFS_platformGrabMutex in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x0000000000588ecf: doMount in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000005891f3: PHYSFS_mount in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x0000000000583e99: VDFS::FileIndex::loadVDF(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x0000000000583d49: VDFS::FileIndex::loadVDF(std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000000049ae84: Resources::Resources(Gothic&, Tempest::Device&) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000000048f067: MainWindow::MainWindow(Gothic&, Tempest::VulkanApi&) in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x000000000048d9f2: main in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004013c7: __tmainCRTStartup in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00000000004014fb: mainCRTStartup in C:\Users\MyUsername\Desktop\OpenGothic\bin\Gothic2Notr.exe
0x00007ffdb9827974: BaseThreadInitThunk in C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffdbc10a271: RtlUserThreadStart in C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by Try** [comment]
> what could possibly go wrong?
Seems 2 thing is went wrong:
1) -g <path/to/gothic2>- you have specifier path to original gothic (for scripts and assets)
2) I have to develop a way to inform user about missing/invalid path to gothic.

**Comment by ThielHater** [comment]
Did you intentionally copy your comment?

**Comment by Try** [comment]
> Did you intentionally copy your comment?

Hm, not intentional - weird.

Anyway, I've read your stack-trace, from https://github.com/Try/OpenGothic/issues/27#issuecomment-537451298 - game crashes at `EnterCriticalSection`, while loading gothic *.vdfs archives.

Hard to say what really happened. Lets assume winapi is 100% correct, that means argument for `EnterCriticalSection` is invalid. It can be in case, if PHYSFS_init somehow failed.

Can you, please check value of `stateLock`(null or not), at phyfs.c/1689.
Thanks!

**Comment by ThielHater** [comment]
OpenGothic tries to load "[G2]/Data/Speech_Addon_Patch.vdf", which is the first file in the list, and stateLock is NULL as you expected. I'm sorry for the late reply but I had to figure out how to debug your project in Visual Studio first.

**Comment by ThielHater** [comment]
It's actually a bug in physfs, I send them a pull request.

**Comment by ThielHater** [comment]
I guess you should change the source of the physfs submodule: https://github.com/REGoth-project/physfs/pull/1#issuecomment-538135598

**Comment by Try** [comment]
> It's actually a bug in physfs
I've update physfs library&ZenLib
Thanks, for your help!
