### ISSUE TITLE
Mouse Y-axis inversion does not work [Linux]

### ISSUE THREAD

**Issue by FoobarTheFatPenguin** [Try/OpenGothic#270]
I compiled the current GIT code on Linux Mint 20.3 without issues, but quickly ran into a problem when trying to play the game: The mouse Y-axis is always the wrong way around.

It is always: You move the mouse forward, the camera looks up. It should be: You move the mouse forward, the camera looks down. Like flying an airplane: You push the stick forward and the nose of the plane goes down, not up.

There is a setting in the game's options to invert the mouse look which *should* fix this, but it has no effect in OpenGothic. When I run the same Gothic 2 installation in WINE, the settings works. When I run it in OpenGothic, it does not work.

System: AMD Ryzen 5 3600, NVidia GTX 1060, Linux Mint 20.3, kernel 5.13, Xorg 7.7, using proprietary NVidia drivers 470.

**Comment by Try** [comment]
Hi. @FoobarTheFatPenguin !

You are right, OpenGothic didn't support `camLookaroundInverse` - fixed
