### ISSUE TITLE
Chests refilled after a save loaded

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#277]
Steps to reproduce:

1. Open a chest
2. Empty the chest (Grab items into your bag)
3. Close chest (step back)
4. Save game
5. Exit game
6. Start game
7. Load save
8. Open chest

Observed: Items are in chest again
Expected: No items in chest

**Comment by Try** [comment]
Hi, @AlexJakeGreen !

Thanks for the report, fixed.
