### ISSUE TITLE
Weapon moveset switch bug

### ISSUE THREAD

**Issue by Madzzc** [Try/OpenGothic#286]
At the moment you can switch between two weapon movesets. Onehanded and twohanded. If you will hold a weapon with onehanded moveset, and then equipped through inventory a weapon with twohanded moveset, the moveset won't change and you will hold a twohanded weapon like if it was a onehanded weapon. Same applies to twohanded weapons. 
   
   Don't know if this bug was in the original gothic game, but it sure is in opengothic.
   
   Version of opengothic: 1.0.1574
   
   Video showcasing the bug: [youtube](https://youtu.be/NASBwopOCjw)

**Comment by Try** [comment]
Hi, @Madzzc !

Right, this part of opengothic  is incomplete one. In vanilla, it's no allowed to use inventory, while in fight, so issue doesn't exist.

**Comment by Try** [comment]
fixed by  #317
