### ISSUE TITLE
Error while running the Gothic

### ISSUE THREAD

**Issue by dolphin221** [Try/OpenGothic#29]
> ---crashlog(SIGABRT)---
GPU: ?
0x00493376: CrashLog::dumpStack(char const*) in ...\bin\Gothic2Notr.exe
0x00493211: signalHandler(int) in ...\bin\Gothic2Notr.exe
0x769c83c1: raise in C:\Windows\System32\msvcrt.dll
0x769cc84b: abort in C:\Windows\System32\msvcrt.dll
0x00493236: CrashLog::setup() in ...\bin\Gothic2Notr.exe
0x6fe59399: ZN10__cxxabiv111__terminateEPFvvE in ...\bin\libstdc++-6.dll
0x00475de8: _main in ...\bin\Gothic2Notr.exe
0x004013e2: ___tmainCRTStartup in ...\bin\Gothic2Notr.exe
0x754a0419: BaseThreadInitThunk in C:\Windows\System32\KERNEL32.DLL
0x7764662d: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll
0x776465fd: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll

**Comment by Try** [comment]
Hi, thanks for crash-report!
Looks like invalid gothic path exception. 
Have you specified '-g' parameter to run it?
Is there any errors in 'log.txt' file?

**Comment by dolphin221** [comment]
I have specified '-g' parameter to run it but it doesn't run. And these are all errors that i found in 'log.txt'. May it be problem of my having installed non Steam version of Gothic?

**Comment by Try** [comment]
> May it be problem of my having installed non Steam version of Gothic?

While support for G1 is not guarantied, it shouldn't crash at least. Also it's very odd to not have anything else in log.txt.
Formally valid 'gothic-path' should contain '/Data' and '_work/Data' subdirs. I assume it's true for non-steam setup as well.

OK, plan 'B' then: I've made a new build with extended logging: https://github.com/Try/OpenGothic/releases/tag/gothic-win32-v1.0.198

**Comment by dolphin221** [comment]
I think I found the root of the problem. The fact is that the game is launched through the .bat file (see screenshot below)
[root folder](https://drive.google.com/open?id=1ppLF4cJp84bO6CZTAu9ExUHDT9KC28rz)
['System/' folder ](https://drive.google.com/open?id=1yrrYHxQPdFjoBhqFMoQBaz36pMIkzq1Q)

**Comment by dolphin221** [comment]
And something else I forgot to mention, when starting up, an error initially appeared that there is no **volcano-1.dll**, but I downloaded this file from the Internet and after that there was an error that I already reported. I do not know whether this volcano-1.dll related to errors

**Comment by Try** [comment]
> I think I found the root of the problem. 

Your screenshots are more confusing, then explanatory :)
Have you manage to run the game, after all?

Also short note:
 * It's fine to run game with *.bat, if your work-dir is same directory where Gothic2Notr.exe located.
 * Where is *.exe of original game - doesn't mater
 * vulkan-1.dll - the vulkan graphics driver( usually pre-installed on modern system )

**Comment by dolphin221** [comment]
No, i haven't run the game but the error log changed a bit:

unable to read .ini file

---crashlog(std::system_error(No device))---
GPU: ?
0x004935a6: CrashLog::dumpStack(char const*) in ...\bin\Gothic2Notr.exe
0x004932b5: terminateHandler() in ...\bin\Gothic2Notr.exe
0x6fe59399: ZN10__cxxabiv111__terminateEPFvvE in ...\bin\libstdc++-6.dll
0x6b6da987: ZN7Tempest9VulkanApi4ImplC1Eb in ...\bin\libMoltenTempest.dll
0x6b6799d6: ZN7Tempest9VulkanApiC2ENS_8ApiFlagsE in ...\bin\libMoltenTempest.dll
0x00475e19: _main in ...\bin\Gothic2Notr.exe
0x004013e2: ___tmainCRTStartup in ...\bin\Gothic2Notr.exe
0x75a90419: BaseThreadInitThunk in C:\Windows\System32\KERNEL32.DLL
0x7784662d: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll
0x778465fd: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll

---crashlog(SIGABRT)---
GPU: ?
0x004935a6: CrashLog::dumpStack(char const*) in ....\bin\Gothic2Notr.exe
0x00493211: signalHandler(int) in ....\bin\Gothic2Notr.exe
0x76e683c1: raise in C:\Windows\System32\msvcrt.dll
0x76e6c84b: abort in C:\Windows\System32\msvcrt.dll
0x004932ba: terminateHandler() in ...\bin\Gothic2Notr.exe
0x6fe59399: ZN10__cxxabiv111__terminateEPFvvE in ...\bin\libstdc++-6.dll
0x6b6da987: ZN7Tempest9VulkanApi4ImplC1Eb in ...\bin\libMoltenTempest.dll
0x6b6799d6: ZN7Tempest9VulkanApiC2ENS_8ApiFlagsE in ...bin\libMoltenTempest.dll
0x00475e19: _main in ...\bin\Gothic2Notr.exe
0x004013e2: ___tmainCRTStartup in ...\bin\Gothic2Notr.exe
0x75a90419: BaseThreadInitThunk in C:\Windows\System32\KERNEL32.DLL
0x7784662d: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll
0x778465fd: RtlGetAppContainerNamedObjectPath in C:\Windows\SYSTEM32\ntdll.dll

AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Try** [comment]
OK, this crashlog is much better now:
`---crashlog(std::system_error(No device))---`
That's mean you have no vulkan-capable device, with driver.

You have mention before:
> ... volcano-1.dll, but I downloaded this file from the Internet

This probably wasn't the best idea - you should just install the driver.
* NVidia has a driver for your win7: https://developer.nvidia.com/vulkan-driver
* AMD - I don't know

**Comment by Try** [comment]
closed: not a bug

**Comment by developer239** [comment]
@Try Why is there "guide" for running on MacOS then?
