### ISSUE TITLE
Pyrokar, Francis dialog option not available

### ISSUE THREAD

**Issue by thokkat** [Try/OpenGothic#292]
After passing the trial of fire the option letting Dyrian stay in the monastery is not available.

---

If you knock down Francis to get the key for Gregs hut and talk to him later while he's sawing you get stuck. It appears that the dialog box isn't popping up.

**Comment by Try** [comment]
Hi @thokkat !

Need a save file to investigate this case

PS:
Merged with other similar ticket.

**Comment by thokkat** [comment]
I knew a save game would be helpful for investigation but in my infinite wisdom i overwrote the ones where i still was a novice. However here's the save file for the Francis case

[save_slot_5.zip](https://github.com/Try/OpenGothic/files/9500046/save_slot_5.zip)

**Comment by Try** [comment]
> After killing the 3rd dragon and asking Oric

State of script variables:
![изображение](https://user-images.githubusercontent.com/122894/189496753-7907bf6c-7c97-4834-90ed-bad14926a434.png)

Script code bug by the look of it: Orik hasn't give info about fire-dragon to you, so option is available. But there is a second level check: before outputting dialog line script check that if dragon is still alive. And he is not.

**Comment by thokkat** [comment]
Did a quick check and yeah i messed up the order, killed fire instead of rock.

**Comment by thokkat** [comment]
Pyrokar's dialog options are only available if you have the corresponding quest. You need to take Dyrian's spell to trigger it, whereas the quests for the other two novices trigger right when they tell about their problem. An inconsistency in the script.
