### ISSUE TITLE
Weapon not unequipped if a temp bonus is removed

### ISSUE THREAD

**Issue by thokkat** [Try/OpenGothic#294]
if you get the required strength to equip a sword by the help of a temporary bonus like an amulet, the sword is not unequipped if you remove the amulet.

**Comment by thokkat** [comment]
Hey @Try i got it working with this change

```
diff --git a/game/game/inventory.cpp b/game/game/inventory.cpp
index e042790..e3ed647 100644
--- a/game/game/inventory.cpp
+++ b/game/game/inventory.cpp
@@ -864,7 +864,7 @@ void Inventory::invalidateCond(Npc &owner) {
 
 void Inventory::invalidateCond(Item *&slot, Npc &owner) {
   if(slot && !slot->checkCond(owner))
-    slot=nullptr;
+    unequip(slot,owner);
   }
 
 void Inventory::autoEquip(Npc &owner) {
```

Maybe also auto-equip the then best usable weapon with respect to the higher weapon skill percentage in case you aren't aware of being unarmed?

Not directly related to the above but why are there invalidate functions for stuff other than weapons? Since none of these have an attribute requirement, so they can never be invalidate. Except runes, but circles of magic can't be increased temporarily.
Ok now that i think about it, mods in the future could make use of it possibly.

**Comment by Try** [comment]
Hi, @thokkat !

Yep, thanks for bugfix!

> invalidate functions for stuff other than weapons? 

Technically script allows equip requirements for practically anything - so checking all items
