### ISSUE TITLE
Runes and spells can't be assigned to a specific key

### ISSUE THREAD

**Issue by thokkat** [Try/OpenGothic#297]
It currently doesn't work to press a number key like 4 on a rune/spell in your inventory to assign that key to the rune/spell.

**Comment by AlexJakeGreen** [comment]
Try to click on the spell in inventory, the key will be automatically assigned
![Screenshot from 2022-09-08 11-10-10](https://user-images.githubusercontent.com/3207095/189070506-5758519d-afe4-4425-b329-69ff007d46b3.png)

**Comment by thokkat** [comment]
I know. Number keys just grant a bit more convenience. Assigning your spell to your favorite number is easier and this also works if all numbers are in use. Currently you have to unassign one first which is a bit tedious.
