### ISSUE TITLE
Torchfire is not centered

### ISSUE THREAD

**Issue by thokkat** [Try/OpenGothic#298]
![Opengothic_Torchfire](https://user-images.githubusercontent.com/100468436/188525107-e19b44e2-4f49-4237-946c-28fcf9f72fa2.png)

Edit: some Torchfires are invisible in the castle
![Torch_invisible](https://user-images.githubusercontent.com/100468436/189503438-92f36519-c69f-4019-b603-d7f49fff50b2.png)

**Comment by AlexJakeGreen** [comment]
I observed the same for fire spells too, the fireball is shifted left
![Screenshot from 2022-09-08 12-35-54](https://user-images.githubusercontent.com/3207095/189089027-ec4c7b5a-b0c5-407c-b996-b5ce251f7e59.png)

**Comment by Try** [comment]
Tested wall torches in vanilla:
![изображение](https://user-images.githubusercontent.com/122894/212748330-eb406f2d-05a2-40b0-afe1-86e0138b6941.png)

Spells are fixed(cb75bf74):
![изображение](https://user-images.githubusercontent.com/122894/212748806-2586ddf4-380d-4725-87b8-b0b592bf3840.png)

**Comment by Try** [comment]
So, only visibility problem can be confirmed:
visible when not suppose to and vise-versa
