### ISSUE TITLE
Ranged weapon does not deal a damage

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#300]
I observed that arrows do not make damage if the distance to a monster is longer than a length of sword, i.e. bows make damage only in close combat. I tried to shoot a few rats, they start to attack immediately after an arrow was shot, but no damage was made.

**Comment by matthiakl** [comment]
I can't confirm the issue, maybe your bow skills are too low?

**Comment by Try** [comment]
Hi @matthiakl !

For me bow and cross-bow works fine. What are you character stats?

**Comment by AlexJakeGreen** [comment]
![Screenshot from 2022-09-08 23-23-05](https://user-images.githubusercontent.com/3207095/189218670-accbd58b-4da6-431c-aeb2-2d6c5a386858.png)
For some reason range damage is not dealt at all. Monsters start to attack, but that's all. Only when they are close to the character then bow makes damage. If this is because of low stats, maybe, there's an information at which stats levels it starts to deal a damage...

**Comment by Try** [comment]
> If this is because of low stats, maybe

Bow range is calculated as:
```
MaxBowRange = 3500
range = MaxBowRange * pow(BowSkill, 2)
```
At ~30% range should become decent enough

**Comment by AlexJakeGreen** [comment]
Thanks for the info. Looks like need to improve stats. I'll try to build a pure bowman and then return with observations soon.

**Comment by AlexJakeGreen** [comment]
I have rechecked and yes, the bow starts working well when level is a bit higher. With 30% bow level the hunting works well.
Thanks for the clarification.
