### ISSUE TITLE
Broken sound script for sheep

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#306]
Mostly a minor thing but doesn't hurt to mention. Probably a part of #246.

There is a bit of issue that any sheep you meet has a trouble being quiet. In original version, an average sheep walks around, eats grass and bleats from time to time. Here we have that sheep would be bleating nonstop during walking animation.

**Comment by Try** [comment]
The way sheep and many other npc do work, regards to sounds:
in each animation there are event-tags, which state at what frame - what sound effect should be executed.

Sound "Beeee!" is called "SHP_AMBIENT",  and executed at:

Animation "S_FISTWALKL"(numFrames=21), frame 11 - walking animation
Animation "S_FISTWALK" (numFrames=51),  frame 10 - idle animation

Probably this is not really intended behavior, as emitting "Beee" every 21 frames is over the top a bit. Yes I can't say why exactly sheep doesn't span sound in original (or is it?)

**Comment by Dehela** [comment]
If it helps, some video samples of a sheep in original and OpenGothic:

[Original](https://streamable.com/o8rzbb)
[OpenGothic](https://streamable.com/58vsan)

**Comment by Try** [comment]
After analyzing videos and looking into vanilla: appears, that sheep itself is fine, but in opengothic sound has no distance attenuation.
