### ISSUE TITLE
A few of "unable to load sound fx"

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#307]
I have spotted a few instances of sound effects not being loaded (according to log output). You get those during loading of some save file or starting a new game.

```
unable to load sound fx: ENV_NIGHT_TONSOFINSECTS
unable to load sound fx: OW_BIRD11
```

Also getting this after first opening video, though to be fair it is indeed missing in most of game versions (checking steam depots, I can see it only in German and Polish versions) and not OpenGothic fault, just listing for the sake of completeness:

```
unable to play video: "Addon_Title.BIK"
```

**Update**: A few more but didn't pay attention when. Probably that's enough, going to skip if I get more.

```
unable to load sound fx: SWIMWAVES
unable to load sound fx: PICKLOCK_UNLOCK
```

**Comment by Try** [comment]
Testing:
`ENV_NIGHT_TONSOFINSECTS` is requested by one of Vob's and truly does not exists 

`OW_BIRD11` exists, but refer non existing sound file: "bird_11.wav"
Same for `SWIMWAVES`, `PICKLOCK_UNLOCK`.

Closing - not an engine bug
