### ISSUE TITLE
Sengrath's corpse has no crossbow in the inventory

### ISSUE THREAD

**Issue by thokkat** [Try/OpenGothic#309]
...thus you can't finish Udar's quest. In original NotR you can loot his trader inventory instead of the usual "loot inventory" and get the crossbow.

**Comment by Try** [comment]
Some thoughts:

    Sengrath is a merchant
    Merchant inventory is cleared automatically in ZS_DEAD
    Mission items (ITEM_MISSION) should not be cleared, but his cross-box is not marked as ITEM_MISSION

My current view on this: if npc is killed by script ZS_DEAD should not be called then. Need to check with vanilla here: does Sengraths goods are still on him?

**Comment by thokkat** [comment]
From youtube Let's plays it looks like he has his normal inventory and everything you sold to him but not his sword

**Comment by Try** [comment]
> and everything you sold to him but not his sword.

Atm(after [b80f2b0](https://github.com/Try/OpenGothic/commit/b80f2b0615842e2644f0d813b86d9c19d43e935f)) OpenGothic will show sword as well. It's likely that equipped stuff should not be shown at all (`Inventory::Iterator::skipHidden`), but need to verify

**Comment by thokkat** [comment]
Looks good 
![Screenshot_20220925_160902](https://user-images.githubusercontent.com/100468436/192148072-3115ab56-7762-4a7c-9a13-2b5308950d94.png)
