### ISSUE TITLE
Walking sound is missing in magic stance

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#315]
If you switch to magic stance (not sure what to call it, when you can press action button and get a spell produced), running like that would produce no sound. You still get it if you try turning around on same spot.

**Comment by Try** [comment]
Now an engine bug:
ground sounds(GFX) are not defined for this (run forward with magic in hand) animation. Same can be reproduced in original game as well.

**Comment by Dehela** [comment]
Indeed. I am surprised I didn't notice it in original game, or most likely I forgot about it.

From what I can see/understand, the issue is not with the engine itself but game resources and scripts, so there is nothing to fix in OpenGothic.
