### ISSUE TITLE
No inventory scrolling with mouse wheel

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#316]
While it is minor issue, I realized how much I relied on mouse scroll for inventory in original version, it feels quite inconvenient without it.

**Comment by Try** [comment]
Scrolling is implemented and works on my windows/mac machines.

What OS do you use?

**Comment by Dehela** [comment]
Linux (Debian 11.5). I think I can use mouse wheel anywhere else (like camera position, or scrolling in menus), only inventory scroll seem to be missing so I have to use WASD for that.

**Comment by Nindaleth** [comment]
If by scrolling you mean moving the "highlighted item" selection in inventory, then I can confirm that doesn't work on Linux.

**Comment by Try** [comment]
Here is relevant piece of code:
```c++
void InventoryMenu::mouseWheelEvent(MouseEvent &e) {
  if(state==State::Closed) {
    e.ignore();
    return;
    }

  if(state==State::LockPicking)
    return;

  if(e.delta>0)
    for(int i=0;i<e.delta/120;++i){
      moveUp();
      }
  else if(e.delta<0)
    for(int i=0;i<-e.delta/120;++i){
      moveDown();
      }
  adjustScroll();
  }
```
Could it be due to `e.delta/120` ?

**Comment by Nindaleth** [comment]
You're right, good call. `e.delta/100` works as expected on my system (highlight moves vertically until reaching the last/first row, then moves horizontally until reaching the last/first item of the inventory).

**Comment by Try** [comment]
Correct fix is probably to change engine-level X11 abstraction to match windows behavior:

> The wheel rotation will be a multiple of WHEEL_DELTA, which is set at 120. 
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousewheel

**Comment by Nindaleth** [comment]
One more finding - changing `i<e.delta/120` to `i<=e.delta/120` also helps on Linux.

**Comment by Try** [comment]
> One more finding - changing i<e.delta/120 to i<=e.delta/120 also helps on Linux.

Done it slightly different: game now accumulates `scrollDelta` across all `mouseWheelEvent`s
