### ISSUE TITLE
Overgrown chandelier chains in Monastery

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#321]
These chains are in dire need of some trimming. And yes, it's not just a visual issue, you can't pass through them.

![1](https://user-images.githubusercontent.com/111627003/190612416-975d3e39-f56a-4e03-8a42-62564386b288.jpg)

**Comment by Try** [comment]
Hi, @Dehela !

Those chandelier are not an engine issue: they have been put there by level designed. In vanilla you can't see them, as basement is not loaded in memory, when player stands on ground floor

**Comment by Dehela** [comment]
Hm, sounds somewhat similar to earthquake thing, with issues caused by the world being fully rendered. Is there some way to handle it or has to be postponed till later?

**Comment by Try** [comment]
That are similar, but not similar enough things:
Generally plan is to build engine that can run fast as-is without distance based tricks.

For AI it's generally fine, except places, where we have poorly written scripts, other than that - fine. 
In theory, Saturas case can be fixed at `tickRoutine` in quick and dirty way:
```c++
void Npc::tickRoutine() {
  ...
  /*HACK: don't process far away Npc*/
+ if(aiPolicy==Npc::ProcessPolicy::AiFar2)
- if(aiPolicy==Npc::ProcessPolicy::AiFar2 && routines.size()==0)
    return;
```

For Level streaming, well we just don't do it. And recreating streaming-like mechanism for the sake of fixing bad content is not part of the plan.

**Comment by Dehela** [comment]
I see. Then some standalone patcher for game resources would be required for this and similar cases.

Anyway, this ticket can be closed then.
