### ISSUE TITLE
NPCs can stand on water surface

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#322]
A bit of Jesus role-playing. Here this guard is angry at me so whenever I try to stand on solid ground, he would attempt to chase me and end up swimming; and he will stand on water if I get to water myself or distance from him.

![1](https://user-images.githubusercontent.com/111627003/190633596-97db0f9b-d91b-4ed2-bce1-9ee2b5f54b76.jpg)

**Comment by Try** [comment]
Closing as duplicate of #320  - there is no difference between humans and other living creatures on engine side
