### ISSUE TITLE
Windowed mode on Linux

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#337]
There are two bugs when running the game in a window on Linux:

* window title is "Tempest.Window"
* mouse cursor is always visible in the screen center and it oscillates around the center if moving the mouse (mouse control works normally otherwise)

**Comment by Dehela** [comment]
On this topic, running the game in window mode (with -window parameter), mouse movement is actually not captured. I can move mouse cursor around but in-game camera doesn't react to it at all. If I try to hold left mouse, it would start reacting to mouse movement but in different way (move camera to see your character at different angles).

**Comment by Nindaleth** [comment]
Interestingly, I don't suffer from that on X11. Are you running Wayland or X11? While I don't think it should matter (XWayland layer should handle it), your mouse movement issue sounds similar to what affects Steam Deck that runs the game in Gamescope Wayland compositor.

**Comment by Dehela** [comment]
X11. Normal keyboard controls seem to be perfectly fine, only mouse is treated as if game window is not focused.

**Comment by Try** [comment]
>  I can move mouse cursor around but in-game camera doesn't react to it at all. 

This is intentional. Windowed mode is designed for debugging. Basically I need a reproducible screenshoots between runs to debug shaders

> window title is "Tempest.Window"

Window title is not implemented in engine :D 
Feel free to PR: something that work on Linux and does nothing on Mac/Windows is fine with me.

> mouse cursor is always visible in the screen center and it oscillates around the center if moving the mouse

This seems like a bug: basically cursor in your case behaves, as in full-screen mode but remain visible. Maybe there is a issue with `isFullscreen`.

**Comment by Dehela** [comment]
> This is intentional. Windowed mode is designed for debugging.

Might be good to have that note for window mode, so other players wouldn't be confused about it :)

**Comment by Nindaleth** [comment]
> Maybe there is a issue with `isFullscreen`.
I can't verify right now, but you're probably right as I still have that Steam Deck-related hackfix present even on my desktop :see_no_evil: I guess with that hackfix removed I'll have it same as does @Dehela 

> Might be good to have that note for window mode
I have unrelated README.md PR in works, I'll add the note.

@Try are there any other debugging-only switches? I mean 100% useless to players - switches such as -g1 and -g2 or -dx12 (which I'll document too) are primarily debugging, but a user may still want to use them and profit from them.

**Comment by Dehela** [comment]
Sounds like this issue could be closed at this point.

**Comment by Try** [comment]
Added an engine ticket to implement `setWindowTitle`
https://github.com/Try/Tempest/issues/40
