### ISSUE TITLE
Sneaking issues

### ISSUE THREAD

**Issue by sirsteve1** [Try/OpenGothic#343]
When sneaking, there seem to be some problems in item interaction an fighting.

- [x] Taking items is not possible when sneaking 
- [x] Bowhunting + Sneaking makes troubles. In sneaking mode the bow is always pulled but it is impossible to shoot an arrow.
- [x] When sneaking close to sleeping people they wake up though they should continue sleeping

**Comment by sirsteve1** [comment]
The bowing and spell focussing is now completely screwed up. I don't know if this is due to the sneaking issue fix or based on the switch to phoenix (have no idea about pheonix in general). 

Problems:
- When using the bow it does not focus at all anymore when there is an enemy to focus on. The bow is bend and instantly reset to rebend it, thus no arrow can be shot. This problem was beforehand only when sneaking, now it is both when sneaking and when standing normally.
- When focussing an npc, the focus switches as soon as another enemy comes closed. Also it is not possible anymore to select the focus via the arrow keys, as it was before. That is also a problem when having an npc as companion, as when the helper runs towards the enemy for attack it moves into the focus and gets shot (when using a spell, bow doesn't work anyways).
- When attacking an enemy via spell, it is not possible anymore to further attack after the first shot. I need to let go of all keys, then focus again and re-attack. Makes multiple shots very cumbersome, which is very important for stronger enemys.

**Comment by Try** [comment]
Hi, @sirsteve1, thanks for testing !

I've tested locally - animation still is a bit off, yet should be playable now

**Comment by sirsteve1** [comment]
Tested the first two issues, they do work well. When sneaking close to people they are still waking up, which makes the thief guild quest quite hard.

**Comment by Try** [comment]
All issues should be fully fixed now
