### ISSUE TITLE
Build against system libraries to prevent package conflicts on Arch Linux

### ISSUE THREAD

**Issue by CReimer** [Try/OpenGothic#344]
Hi,

I need some help creating a PKGBUILD for this. Some concern was raised because opengothic conflicts with several system libraries.

To make it work, I need to disable compilation and instead enable linking against the system library (bullet, libsquish and physfs).
I'm not so great at understanding CMake. I just need some pointers on what flags I need to set to make this work as expected.

Thanks

Christopher

**Comment by lmichaelis** [comment]
Hi @CReimer,
if the issue you're having is really just about conflicting libraries then normally it should be enough to remove the corresponding `add_submodule` and `include_directories` directives. They are nicely layout out here:

https://github.com/Try/OpenGothic/blob/0158df885324bc7b953b46729b8f226745aa899b/CMakeLists.txt#L75-L119

It is also important to make sure that the library installed on the system is compiled with the correct options (ie. `BULLET2_MULTITHREADING=ON`). Those options can then normally also be removed from the `CMakeLists.txt`. The actual library names are set using [`target_link_libraries`](https://cmake.org/cmake/help/v3.16/command/target_link_libraries.html) directives. They might have to be changed too to match the names of those libraries when installed on the system.

`libsquish` is a dependency of [ZenLib](https://github.com/Try/ZenLib) so you'd have to apply the patches mentioned above in its `CMakeLists.txt` as well.

Hope that is helpful :)

**Comment by CReimer** [comment]
Yes. That helped.
I think I figured it out for now. Thanks.
