### ISSUE TITLE
game crashes at startup

### ISSUE THREAD

**Issue by ankorinek** [Try/OpenGothic#347]
Got the following error on Linux Mint:

OpenGothic v1.0 dev
no *.ini file in path - using default settings
no *.ini file in path - using default settings
GPU = Intel(R) HD Graphics 530 (SKL GT2)
Depth format = 14 Shadow format = 14
Info: ZEN: Reading presets...
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x7c00008
  Serial number of failed request:  81
  Current serial number in output stream:  91
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Nindaleth** [comment]
How did you start the game?

**Comment by ankorinek** [comment]
ivy@ivy-XPS-15-9550:~/OpenGothic/build/opengothic$ ./Gothic2Notr.sh -g ~/Downloads/app
OpenGothic v1.0 dev
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

no *.ini file in path - using default settings
no *.ini file in path - using default settings

---crashlog(std::terminate)---
GPU: ?
#1:  - /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2b7) [0x7f1bb5e792b7]
#2: __cxa_rethrow - /lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0x4b) [0x7f1bb5e7956b]
#3: __cxa_rethrow - /home/ivy/OpenGothic/build/opengothic/libTempest.so(+0xe4de9) [0x7f1bb62e1de9]
#4: Tempest::VulkanApi::createSwapchain(Tempest::SystemApi::Window*, Tempest::AbstractGraphicsApi::Device*) - /home/ivy/OpenGothic/build/opengothic/libTempest.so(_ZN7Tempest9VulkanApi15createSwapchainEPNS_9SystemApi6WindowEPNS_19AbstractGraphicsApi6DeviceE+0x2a) [0x7f1bb63834fa]
#5: Tempest::Device::swapchain(Tempest::SystemApi::Window*) const - /home/ivy/OpenGothic/build/opengothic/libTempest.so(_ZNK7Tempest6Device9swapchainEPNS_9SystemApi6WindowE+0x1d) [0x7f1bb6386a6d]
#6: Tempest::Swapchain::Swapchain(Tempest::Device&, Tempest::SystemApi::Window*) - /home/ivy/OpenGothic/build/opengothic/libTempest.so(_ZN7Tempest9SwapchainC1ERNS_6DeviceEPNS_9SystemApi6WindowE+0x39) [0x7f1bb6389579]
#7: MainWindow::MainWindow(Tempest::Device&) - /home/ivy/OpenGothic/build/opengothic/Gothic2Notr(_ZN10MainWindowC2ERN7Tempest6DeviceE+0x67) [0x55772e230e07]
#8: main - /home/ivy/OpenGothic/build/opengothic/Gothic2Notr(main+0x191) [0x55772e12ec31]

Aborted (core dumped)
ivy@ivy-XPS-15-9550:~/OpenGothic/build/opengothic$ sudo sysctl dev.i915.perf_stream_paranoid=0
[sudo] password for ivy:           
dev.i915.perf_stream_paranoid = 0
ivy@ivy-XPS-15-9550:~/OpenGothic/build/opengothic$ ./Gothic2Notr.sh -g ~/Downloads/app
OpenGothic v1.0 dev
no *.ini file in path - using default settings
no *.ini file in path - using default settings
GPU = Intel(R) HD Graphics 530 (SKL GT2)
Depth format = 14 Shadow format = 14
Info: ZEN: Reading presets...
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x6600008
  Serial number of failed request:  81
  Current serial number in output stream:  91
AL lib: (EE) alc_cleanup: 1 device not closed
ivy@ivy-XPS-15-9550:~/OpenGothic/build/opengothic$

**Comment by Nindaleth** [comment]
From the log it seems as if your iGPU does not support some of the features the game engine requires. Do you by any chance have a dGPU in your specific XPS config you could try switching to?
Other than that I can only propose trying a newer Mesa with an updated ANV (Intel Vulkan) driver if you can. XPS 9550 should run a Skylake iGPU which continues to be supported in current ANV.

**Comment by ankorinek** [comment]
Using the Nvidia GPU has resolved this issue
