### ISSUE TITLE
Beliar's Claw - receiving multiple runes

### ISSUE THREAD

**Issue by sirsteve1** [Try/OpenGothic#353]
Dear @Try

As a mage, when I exchange the claw of beliar against runes, I always have to select all rune-options one by one, giving me all available runes at once. The dialog should quit when selecting the first rune, yet does continue until no option (rune to select) is left. By this I can run around with all available beliar runes at once.

Original Game behavior is only one rune at once.

**Comment by Try** [comment]
Hi, @sirsteve1 and thanks for reporting!

Can you please attach save-game file (before receiving runes), for me to test locally?

**Comment by sirsteve1** [comment]
I'm sorry, I checked against with a new save-state using a characterhelper in G2 without mods. There the problem does not appear, thus it is a Mod-based problem.
