### ISSUE TITLE
Spell issues

### ISSUE THREAD

**Issue by sirsteve1** [Try/OpenGothic#355]
Dear @Try 

Some problems regarding the use of runes and spell scrolls:

- [ ] __Radius damage hardly works:__ When using a radius damage spell like small or large firestorm, the spell will hit the enemy but won't hit surrounding enemies except they are __very close__. I tested this also by inserting some molerats. They have been so close that all should die immediately, but I had to kill them all one by one. Only once a molerate standing practically at the same spot died as well. This does not affect area spells, they work normally.
- [ ] __Charging min / max spells won't work:__ When trying to charge a spell like windfirst or large firestorm, the spell immediately get cast in _min-mode_ without charging. Charging seems to have a problem.  
- [ ] __Using min / max spells more than once won't work:__ When using a chargable spell, I cannot use another chargable spell, independent of using the same or another chargable spell. Probably this is connected to the not-charging problem above. I can have enough mana, yet the spell won't get cast at all - the hero waves with the hands as if he has not enough mana. Other spells work are not affected.
- [ ] __Using fear crashes the game:__ When using fear next to orcs, the game crashes immediately. When using fear close to some mercaneries (teleported to onars farm and used it next to Cord) I was still able to walk some steps and then the game crashed.

**Comment by Try** [comment]
Hi, @sirsteve1 !

I've tested last case;
> When using fear next to orcs, the game crashes immediately. 

So far no reproduction on MinGW/debug. No mods on my side. Can you share a callstack of crash?

**Comment by sirsteve1** [comment]
> > When using fear next to orcs, the game crashes immediately.
> 
> So far no reproduction on MinGW/debug. No mods on my side. Can you share a callstack of crash?

So I've retestet this, it leaves me somehow with some questions
- Tested it beforehand and multiple times in using fear the game crashed, but not always
- Tested it again now, mostly in the same spot where I've tested it beforehand but also with other places. Now the spell works but the game crashes probably due to another reason, probably the fear spell triggered the other event as well occasionally.

Here is the actual crashlog:
```
---crashlog(SIGSEGV)---
GPU: NVIDIA GeForce GTX 960M
#1:  - /lib/x86_64-linux-gnu/libc.so.6(+0x19d97d) [0x7fabed6a997d]
#2:  - /lib/x86_64-linux-gnu/libc.so.6(+0x76db1) [0x7fabed582db1]
#3:  - /lib/x86_64-linux-gnu/libc.so.6(+0x8851a) [0x7fabed59451a]
#4: __snprintf_chk - /lib/x86_64-linux-gnu/libc.so.6(__snprintf_chk+0xa5) [0x7fabed640ce5]
#5: AnimationSolver::solveFrm(std::basic_string_view<char, std::char_traits<char> >, WeaponState) const - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZNK15AnimationSolver8solveFrmESt17basic_string_viewIcSt11char_traitsIcEE11WeaponState+0x1a1) [0x559fec884601]
#6: MdlVisual::startAnim(Npc&, WeaponState) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN9MdlVisual9startAnimER3Npc11WeaponState+0x54) [0x559fec872f44]
#7: Npc::closeWeapon(bool) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN3Npc11closeWeaponEb+0x3a) [0x559fec92295a]
#8: Npc::nextAiAction(AiQueue&, unsigned long) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN3Npc12nextAiActionER7AiQueuem+0x2ee) [0x559fec929b5e]
#9: Npc::implAiTick(unsigned long) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN3Npc10implAiTickEm+0xeb) [0x559fec92c09b]
#10: WorldObjects::tick(unsigned long, unsigned long) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN12WorldObjects4tickEmm+0x237) [0x559fec951467]
#11: World::tick(unsigned long) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN5World4tickEm+0x1f) [0x559fec944a8f]
#12: GameSession::tick(unsigned long) - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN11GameSession4tickEm+0x75) [0x559fec830505]
#13: MainWindow::tick() - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN10MainWindow4tickEv+0x10c) [0x559fec8c9cbc]
#14: MainWindow::render() - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(_ZN10MainWindow6renderEv+0x93) [0x559fec8ccc73]
#15: Tempest::X11Api::implProcessEvents(Tempest::SystemApi::AppCallBack&) - /home/steve/Software/games/OpenGothic/game/libTempest.so(_ZN7Tempest6X11Api17implProcessEventsERNS_9SystemApi11AppCallBackE+0x7e) [0x7fabedc3da4e]
#16: Tempest::X11Api::implExec(Tempest::SystemApi::AppCallBack&) - /home/steve/Software/games/OpenGothic/game/libTempest.so(_ZN7Tempest6X11Api8implExecERNS_9SystemApi11AppCallBackE+0x24) [0x7fabedc3d194]
#17: main - /home/steve/Software/games/OpenGothic/game/Gothic2Notr(main+0x1d7) [0x559fec78c437]
```

The situation happened when running through the orc group at the new world pass, mostly after casting fear. I don't know what actually happens, maybe when an orc is putting back his weapon...

So this is probably not a spell / fear issue.

**Comment by sirsteve1** [comment]
> * [ ]  **Radius damage hardly works:** When using a radius damage spell like small or large firestorm, the spell will hit the enemy but won't hit surrounding enemies except they are **very close**. I tested this also by inserting some molerats. They have been so close that all should die immediately, but I had to kill them all one by one. Only once a molerate standing practically at the same spot died as well. This does not affect area spells, they work normally.
> * [ ]  **Charging min / max spells won't work:** When trying to charge a spell like windfirst or large firestorm, the spell immediately get cast in _min-mode_ without charging. Charging seems to have a problem.
> * [ ]  **Using min / max spells more than once won't work:** When using a chargable spell, I cannot use another chargable spell, independent of using the same or another chargable spell. Probably this is connected to the not-charging problem above. I can have enough mana, yet the spell won't get cast at all - the hero waves with the hands as if he has not enough mana. Other spells work are not affected.

I forgot to test these spells without mod. Retested withouth mod, there everything works. Thus the problem seems mod-related. I will try to investigate it further.
