### ISSUE TITLE
[gothic1] Default keyboard setting does not work

### ISSUE THREAD

**Issue by sirsteve1** [Try/OpenGothic#356]
Dear @Try 

When opening Gothic 1 (original game, no mod), the keyboard setting is empty for me. Trying to restore either default or alternative keyset won't do anything.

Investigated a bit, the problem is with the `preset`  loaded from `Gothic.ini` as used in this function:
https://github.com/Try/OpenGothic/blob/7a027dcfa8756c66e538780329e416b7355bdc01/game/utils/keycodec.cpp#L156-L162

The preset comes from the gamemenu class:
https://github.com/Try/OpenGothic/blob/7a027dcfa8756c66e538780329e416b7355bdc01/game/ui/gamemenu.cpp#L897-L903

Now within the G2 ini file, the two given presets `KEYSDEFAULT0` and `KEYSDEFAULT1` are there, in G1 ini they don't exist. Thus the default keys won't work. I recompiled using `KEYS` as preset, as this does exist in G1 ini - just for testing purpose, but this does not work, so undid changes and compiled again.

What did work was copying out the `[KEYSDEFAULT0]` section from G2 ini to G1 ini, then starting the game and setting the default keyset.

I tried to find out where the original game stores the default and alternative keyset, might be somewhere hardcoded. Had no luck to find the settings so far...

**Comment by Try** [comment]
Added a hard-coded preset that matches my Steam install for now
