### ISSUE TITLE
Fails to run on mac (libTempest.dylib not found)

### ISSUE THREAD

**Issue by efossvold** [Try/OpenGothic#358]
I'm having trouble running OpenGothic on mac, not sure if I built it correctly. Getting this error when trying to run it:
_~/Downloads/OpenGothic/build/opengothic [master]$ ./Gothic2Notr.sh
dyld[18079]: Library not loaded: @rpath/libTempest.dylib
  Referenced from: <D88202E2-14DE-316D-975D-9D60308106A6> /Users/xxxxx/Downloads/OpenGothic/build/opengothic/Gothic2Notr
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libTempest.dylib' (no such file), '/usr/local/lib/libTempest.dylib' (no such file), '/usr/lib/libTempest.dylib' (no such file, not in dyld cache)
fish: Job 1, './Gothic2Notr.sh' terminated by signal SIGABRT (Abort)_

The steps I did to build: 
`git clone --recurse-submodules https://github.com/Try/OpenGothic.git`
`brew install cmake glslang vulkan-headers alsa-lib libx11 libxcursor`
`cmake -H. -Bbuild -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`
`cmake --build ./build --target Gothic2Notr`

Then running (with GK2 Notr located in the gk2_data folder)
`cd build/opengothic`
`./Gothic2Notr -g2 -g ../../gk2_data`

I see that **libTempest.dylib** is located in the **build/opengothic** dir. I tried symlinking it to **/usr/local/lib/** where the executable is looking for it, but I had no effect, still same error.

Am I missing something?

**Comment by Try** [comment]
Hi, @efossvold and thanks for reporting!
Problem was: I've forgot to use `DYLD_LIBRARY_PATH` in script, should work now

**Comment by efossvold** [comment]
Perfect, thanks @Try, works now. However, performance is rather low. I'm only getting 25-30 in Xarda's tower, and 15-25 outside. On an earlier build some months ago I was getting around 60 fps. I verified in Activity Monitor that the build is arm64 (got an Air M1). Other than running Ventura 13.0, I don't believe anything in my setup's changed since last time. Was no sound back then though.

**Comment by Try** [comment]
>  Air M1

Hm, I have a few suggestions:
Can you check roughly CPU vs GPU performance, by pausing game?
Check settings in `Extended configurations` page? "Cloud shadows" and "Radial fog" are most impactful there.

**Comment by efossvold** [comment]
"Cloud shadows" was it. Turning it off immediately upped fps to around 55, then switching off "Radial fog" got it to 60. Sweet! Thank you. Is MetalFX being used, or if not, any plans on supporting it?

**Comment by Try** [comment]
>  Is MetalFX being used, or if not, any plans on supporting it?

No, not in use. As far as I know MetalFX has only TAA and upscale algorithm to offer, both has no value to Gothic:
* Upscale(1080p -> 4k) is slower than straight 4k rendering
* TAA can be implemented as compute shader not only for metal, but for every platform. Also MSAA is more promising

**Comment by efossvold** [comment]
> No, not in use. As far as I know MetalFX has only TAA and upscale algorithm to offer, both has no value to Gothic

I understand, makes sense.

>For metal current plans are:
Update to Metal3
GPU-VA, for better ray-tracing
Mesh shader, for invisible geometry removal

Awesome, looking forward. Amazing work, @Try. Gothic II has been one of my all time favourite games ever since I first played it when it came out. Being able to play it like this on modern hardware with updated graphics is such a joy. Thank you for the incredible effort you're putting into this.

**Comment by lectricas** [comment]
got the same error here
