### ISSUE TITLE
Multiple invocation of 'enter_di_firsttime_trigger'

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#36]
This function invoked by TriggerScript. 
If players dexterity is bellow 15, script gonna spam dexPotion endlessly.
It' unclear to me: is it game-script bug or opengothic-engine bug?
```c++
func void enter_di_firsttime_trigger()
{
	if(Npc_HasItems(hero,ItKe_Ship_Levelchange_MIS))
	{
		Npc_RemoveInvItems(hero,ItKe_Ship_Levelchange_MIS,1);
	};
	if(hero.attribute[ATR_DEXTERITY] < 15)
	{
		Wld_InsertItem(ItPo_Perm_DEX,"FP_ITEM_DI_ENTER_05");
	};
	if(EnterDI_Kapitel6 == FALSE) // run_once guard
...
	};
};
```

**Comment by dosinabox** [comment]
It's the script bug. Yes, you can spam these potions endlessly in original game. Transform into sheep if you have more than 15 dex.

**Comment by Try** [comment]
Perfect, thanks!
Now OpenGothic can even reproduce bugs from original game :)
