### ISSUE TITLE
linux: openal: file collision with system files

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#360]
I observed a collision with files installed by system package `media-libs/openal-1.22.2-r1:0::gentoo`

```
 * Detected file collision(s):
 * 
 * 	/usr/share/openal/alsoftrc.sample
 * 	/usr/share/openal/presets/3D7.1.ambdec
 * 	/usr/share/openal/presets/hexagon.ambdec
 * 	/usr/share/openal/presets/itu5.1-nocenter.ambdec
 * 	/usr/share/openal/presets/itu5.1.ambdec
 * 	/usr/share/openal/presets/presets.txt
 * 	/usr/share/openal/presets/rectangle.ambdec
 * 	/usr/share/openal/presets/square.ambdec
 * 	/usr/share/openal/hrtf/Default HRTF.mhr
 * 	/usr/lib64/pkgconfig/openal.pc
 * 	/usr/lib64/cmake/OpenAL/OpenALConfig.cmake
 * 	/usr/lib64/cmake/OpenAL/OpenALTargets.cmake
 * 	/usr/include/AL/al.h
 * 	/usr/include/AL/alc.h
 * 	/usr/include/AL/alext.h
 * 	/usr/include/AL/efx-creative.h
 * 	/usr/include/AL/efx-presets.h
 * 	/usr/include/AL/efx.h
 * 
 * Searching all installed packages for file collisions...
 * 
 * media-libs/openal-1.22.2-r1:0::gentoo
 * 	/usr/include/AL/al.h
 * 	/usr/include/AL/alc.h
 * 	/usr/include/AL/alext.h
 * 	/usr/include/AL/efx-creative.h
 * 	/usr/include/AL/efx-presets.h
 * 	/usr/include/AL/efx.h
 * 	/usr/lib64/cmake/OpenAL/OpenALConfig.cmake
 * 	/usr/lib64/cmake/OpenAL/OpenALTargets.cmake
 * 	/usr/lib64/pkgconfig/openal.pc
 * 	/usr/share/openal/alsoftrc.sample
 * 	/usr/share/openal/hrtf/Default HRTF.mhr
 * 	/usr/share/openal/presets/3D7.1.ambdec
 * 	/usr/share/openal/presets/hexagon.ambdec
 * 	/usr/share/openal/presets/itu5.1-nocenter.ambdec
 * 	/usr/share/openal/presets/itu5.1.ambdec
 * 	/usr/share/openal/presets/presets.txt
 * 	/usr/share/openal/presets/rectangle.ambdec
 * 	/usr/share/openal/presets/square.ambdec
```

**Comment by AlexJakeGreen** [comment]
First appears in 95b23ded9058564145e49b9b6944666910085c6e

**Comment by Try** [comment]
Hi, @AlexJakeGreen !

To be clear: I'm windows user, and opengothic designed as windows-app like, with all libraries on board. `openal-1.22.2` is new sound backed introduced in https://github.com/Try/OpenGothic/commit/95b23ded9058564145e49b9b6944666910085c6e

Can you please provide more details about why this is a problem and what is desired solution for linux? Thanks!

**Comment by AlexJakeGreen** [comment]
I build the master branch every week for a half a year, and everything was so smooth so I thought the project is being developed on linux platform :D

In Linux OS the software is installed via a package manager. One of the functions of a package manager - is to track which files are installed by a package, and check that another package will not overwrite them.
Example: I installed `games-simulation/flightgear` which in turn called installation of dependency library `media-libs/openal` - they are distributed as separate packages. Now, if I run the install command for OpenGothic, the original `openal` package files will be overwritten, which may cause `flightgear` not working.

Maybe, it is possible to tell `cmake` to use the system openal library? Maybe, there is some switch in cmake files? I'm not skilled in cmake unfortunately. I can share my ebuild recipe I use to build a package on my Gentoo laptop (`"${PV}" == 9999` is `true`):
```
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit cmake

MY_PN="OpenGothic"

if [[ "${PV}" == 9999 ]]; then
    inherit git-r3

    EGIT_CLONE_TYPE=mirror
    EGIT_REPO_URI="https://github.com/Try/${MY_PN}.git"

    EGIT_SUBMODULES=(
	lib/Tempest
	lib/bullet3
	lib/TinySoundFont
	lib/phoenix
        lib/phoenix/vendor/glm
	lib/phoenix/vendor/libsquish
	lib/phoenix/vendor/fmt
	lib/phoenix/vendor/lexy
	lib/phoenix/vendor/mio
	lib/phoenix/vendor/doctest
  )
else
    OPENGOTHIC_COMMIT_SHA="c9c807936e95292b47e1667964be2243439d25c3" # 0.52
    Tempest="16a9f590294657c4ea75b8fd8c924d31227114f6"
    TinySoundFont="d4ffcdc8a34d3f61f22e4b283b4c100f5adf4b82"
    ZenLib="8ac4d2c385fe2fabfe8aa060f5bfbb69cbf922ea"
    bullet3="e7e46154bb2f4be77ad79657bcdc2675305b69a4"
    libsquish="f5e44a360fd8b456b1291a2eaba61871c64d6288"
    SRC_URI="
    https://github.com/Try/${MY_PN}/archive/${OPENGOTHIC_COMMIT_SHA}.tar.gz -> ${P}.tar.gz
    https://github.com/Try/Tempest/archive/${Tempest}.tar.gz -> ${P}-lib_Tempest.tar.gz
    https://github.com/schellingb/TinySoundFont/archive/${TinySoundFont}.tar.gz -> ${P}-lib_TinySoundFont.tar.gz
    https://github.com/Try/ZenLib/archive/${ZenLib}.tar.gz -> ${P}-lib_ZenLib.tar.gz
    https://github.com/bulletphysics/bullet3/archive/${bullet3}.tar.gz -> ${P}-lib_bullet3.tar.gz
    https://github.com/tito/libsquish/archive/${libsquish}.tar.gz -> ${P}-lib_ZenLib_lib_libsquish.tar.gz
  "
    S="${WORKDIR}/${MY_PN}-${OPENGOTHIC_COMMIT_SHA}"
fi

DESCRIPTION="Reimplementation of Gothic 2 Notr"
HOMEPAGE="https://github.com/Try/OpenGothic"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="
    media-libs/mesa[vulkan]
    dev-util/glslang
    dev-util/vulkan-headers
    media-libs/vulkan-loader
    dev-util/cmake
    >=dev-util/vulkan-headers-1.3.231
"
RDEPEND="${DEPEND}"

src_unpack() {
    if [[ "${PV}" == "9999" ]]; then
	git-r3_src_unpack
    else
	unpack "${P}.tar.gz"

	cd "${S}" || die
	local i list=(
	    lib_Tempest
	    lib_TinySoundFont
	    lib_ZenLib
	    lib_bullet3
	    lib_ZenLib_lib_libsquish
	)


	for i in "${list[@]}"; do
	    tar xf "${DISTDIR}/${P}-${i}.tar.gz" --strip-components 1 -C "${i//_//}" || die "Failed to unpack ${P}-${i}.tar.gz"
	done

    fi
}

src_configure() {
    local mycmakeargs=(
	-DBUILD_SHARED_LIBS=OFF
	-DOpenGL_GL_PREFERENCE=GLVND
	-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
    )

    cmake_src_configure
}

src_compile() {
    cmake_src_compile
}

src_install() {
    cmake_src_install

    # Do not violate multilib strict
    mv "${ED}/usr/lib/libTempest.so" "${ED}/usr/$(get_libdir)" || die "mv failed"
}
```

**Comment by Nindaleth** [comment]
Usually when just building locally on Linux, the vendored subprojects aren't an issue because they aren't installed into system paths; thus no file conflicts happen. This issue is about (be it in internal/personal capacity, or officially) packaging OpenGothic for Gentoo.

Are you creating a full Gentoo package with everything (Tempest, Phoenix, OpenAL, Bullet, ...) in it? Since the OpenAl itself doesn't seem patched, could you try omitting the OpenAL sources from the output and add the OpenAL package as a dependency into the package metadata?

**Comment by AlexJakeGreen** [comment]
Hi @Nindaleth @Try 
The OpenAL is configured to be linked statically, so I think it is ok to exclude it from the 'all' target. It will be built and linked, but no 'install' target will be run.
Pull request https://github.com/Try/Tempest/pull/41

**Comment by CReimer** [comment]
I ran into similar problems with Arch Linux. I "fixed" it by compiling everything statically and only packaging the finished binary. My fixed PKGBUILD is not yet on AUR, because I already adapted it for phoenix which is not yet in a tagged release.

From a Linux standpoint it's actually quite tedious to build and package opengothic.

Run cmake with -DBUILD_SHARED_LIBS=off -DTEMPEST_BUILD_SHARED=off and delete everything except /usr/bin in your DESTDIR

At first, I attempted to build everything shared (as it should be done on Linux) and even packaged various parts of opengothic, such as phoenix. But since there are specific commits required, I opted for static linking.

**Comment by Try** [comment]
@AlexJakeGreen 
> The OpenAL is configured to be linked statically, so I think it is ok to exclude it from the 'all' target

LGTM, probably should exclude everything else as well (libpng, spirv-cross). One of the reasons to have smaller libraries as statically backed is to stick had to versions that engine is tested against. Not to mention micro pathes on top of stbimage/openal/spirv-cross

Basically should be something like: `/lib/libTempest.so`+`/bin/Gothic2Notr`.

**Comment by Try** [comment]
> Pull request https://github.com/Try/Tempest/pull/41

Merged!

**Comment by AlexJakeGreen** [comment]
Thank you.
I would ask to keep the issue opened for a few days, I want to make a final test after the submodule reference is updated to the point which contains the change. Just to make sure everything is clean. I will close the ticket then.
