### ISSUE TITLE
MoveTrigger: wrong rotation

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#362]
https://user-images.githubusercontent.com/122894/202909801-d606c39c-4507-46fd-8dc1-90d20c477cbf.mp4

Possibly due to move from ZenLib to phenix, but I haven't check it
FYI: @lmichaelis

**Comment by lmichaelis** [comment]
Sure I can take a look at it :)

**Comment by lmichaelis** [comment]
Fixed in [529137d](https://github.com/lmichaelis/phoenix/commit/529137d516615d1a2e62fe380e5690f8cf078a7c).

**Comment by Try** [comment]
Fix doesn't seem to be correct:
![изображение](https://user-images.githubusercontent.com/122894/202930233-f02a2296-1041-4908-8d8c-a3052ed8dec2.png)

While rotation stays consistent, axis, that been taken to rotate around is not correct

**Comment by lmichaelis** [comment]
I'm invoking undefined behaviour again, aren't I. I've double and triple checked with ZenLib and now it has to be correct on phoenix' side

**Comment by Try** [comment]
Yep, now fixed. Thanks!
