### ISSUE TITLE
Crash in the tomb behind Onar's farm

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#365]
Steps to reproduce:
1 Load save
2 Shoot an arrow into a skeleton standing in front

Observed: application crashed
[save_slot_5.sav.gz](https://github.com/Try/OpenGothic/files/10090427/save_slot_5.sav.gz)

[crash.log](https://github.com/Try/OpenGothic/files/10090419/crash.log)

**Comment by Try** [comment]
Hi, @AlexJakeGreen ! 
Thanks for report - fixed.
