### ISSUE TITLE
Build instructions on mac

### ISSUE THREAD

**Issue by audiocrush** [Try/OpenGothic#366]
Hi,

I wonder if someone could add some build instructions for mac.
I could repliace the instructions for linux on a ubuntu laptop, but I don't know what is required to perform this on my m1 pro macbook.
Would be awesome if someone could point me in the right direction, especially which dependencies I need to install using brew or something.

**Comment by Try** [comment]
Hi, @audiocrush !

> which dependencies I need to install using brew or something.

Only `glslang` is required.

I've added minimalistic instructions to Readme:
```
brew install glslang
git clone --recurse-submodules https://github.com/Try/OpenGothic.git
cd OpenGothic
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
cmake --build ./build --target Gothic2Notr

# locate the executables at OpenGothic/build/opengothic
```
