### ISSUE TITLE
"lost device!" on startup

### ISSUE THREAD

**Issue by laenion** [Try/OpenGothic#37]
I compiled OpenGothic on Linux and - after some fiddling with the files - I managed to get the game into a state where _strace_ doesn't report any obvious _file not found_ errors any more. However the game is now stuck with the following output:

```
no *.ini file in path - using default settnigs
no *.ini file in path - using default settnigs
GPU = GeForce GTX 960
Depth format = 6 Shadow format = 4
lost device!
```

I assume this has something to do with Vulkan, but I have no experience with it. I can only tell that other Vulkan games are running perfectly fine.

Is the game supposed to at least start on Linux, or is this expected?

**Comment by Try** [comment]
Hi, @laenion! Thanks for report.
> Is the game supposed to at least start on Linux, or is this expected?

No, at this moment it is possible only to build OpenGothic for Linux.

> I assume this has something to do with Vulkan, but I have no experience with it

Yes - lost device is basically critical error in vulkan world.
However, if you fill brave enough, then you can run the game with '-validation' flag to get detailed error message. If you can provide output of './Gothic2Notr -v' it will help me a lot, thanks!

**Comment by laenion** [comment]
I'm sorry for the late reply - I just checked out today's master before reporting - and the game is starting now! Thanks a lot for all your work!

`-v` doesn't generate any output any more, tough.
