### ISSUE TITLE
alt+tab traps mouse

### ISSUE THREAD

**Issue by Reveares** [Try/OpenGothic#374]
alt+tab focuses another window and overlays it on top of OpenGothic, a normal behavior for Windows. But moving the mouse outside the focused window always moves the mouse to the center of the screen.
It seems that OpenGothic processes mouse movements even when it is not in focus. This makes it harder to do anything else while playing OpenGothic.

I would suggest ignoring mouse input while OpenGothic is out of focus.

**Comment by Try** [comment]
Hi, @Reveares, and thanks for report !

> I would suggest ignoring mouse input while OpenGothic is out of focus.

Yes, that would be good change. Unfortunately `SystemApi` layer has no support for focus events at this point, so need to go deep there.
