### ISSUE TITLE
extremely high damage on the weak bow

### ISSUE THREAD

**Issue by M1sh2** [Try/OpenGothic#378]
Using the latest version: opengothic-v1.0.1705
I have encountered many different bugs, but this one surprised me. I was unable to reproduce the error, I am attaching the save just in case. Damage remains high even when changing bows.
With a bow that has a dmg of 30/dex of 25, I outlasted most of the orcs.

[save_slot_7.zip](https://github.com/Try/OpenGothic/files/10278028/save_slot_7.zip)

**Comment by Try** [comment]
Hi, @M1sh2 and thanks for reporting!

We use to have similar issue (fixed only on `master`).  Could your case be related to: https://github.com/Try/OpenGothic/pull/323 ?

**Comment by Try** [comment]
Tested the save. Yep `hnpc::damage` is poluted. 
![изображение](https://user-images.githubusercontent.com/122894/209002580-4032c260-8836-4bbd-b464-d16b9793347c.png)
That has been fixed, but not yet published. Also, unfortunately, since error is accumulative it wont be fully fixed until new game

**Comment by Try** [comment]
fix is shipped in opengothic-v1.0.1878
