### ISSUE TITLE
-rambo parameter seems to be non functional

### ISSUE THREAD

**Issue by dreimer1986** [Try/OpenGothic#381]
I have no clue since when though. I started another playthrough for fun and realized that the damage calulation is the same with and without -rambo parameter. GII NoR German Steam version.

**Comment by lmichaelis** [comment]
Hi there! `-rambo` was removed in 9a0984bcac5424eedaadbc6596aedec74364b49f. Not sure if that was intentional though since the commit message seems to be unrelated.

**Comment by Try** [comment]
Hi, @dreimer1986 !

Yes, this command line option been an old relic, and fully removed now. Original motivation to remove was Marvin support, and I didn't know, that anyone actually uses it 😅

**Comment by dreimer1986** [comment]
Ahaaa, OK, that explains it ^^ Yeah I used it as what you call a old relic to test around without dying every 10 seconds. But of course you are right, this thing served well and has no real use anymore. Thanks for explaining.
