### ISSUE TITLE
Main character's movement is jittering/stuttering when turning slightly

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#382]
When running and making very gentle turns using a mouse, the main character is vibrating. See in the video, I switch between running in a completely straight line vs turning a little bit.

https://user-images.githubusercontent.com/6383928/211672330-9045f4e1-42d4-44f7-afa7-89f22044ea19.mp4

On sharper rotation the problem either does not happen, or is much less obvious.

**Comment by Try** [comment]
Hi @Nindaleth !

I think there are 2 main sources of stutters;
1. Camera follow is not perfect. Should be negated by 6febda61, 903bb350 
2. Tilting character to side - I don't really know how to achieve look-and-fill of original game here

For tilting relevant code is in `PlayerControl::assignRunAngle` - you can experiment with that, if you want

**Comment by Try** [comment]
Hi, @Nindaleth !

Can you check bdf8ac0, if it works better for you?

**Comment by Nindaleth** [comment]
Hi @Try!

This is much better, thanks! Combined with the two camera commits and the shadow flickering commit, this is a very visible improvement. I know it's neither a top line of the next release notes nor a source for screenshots, but I appreciate this upgrade in the user experience.
