### ISSUE TITLE
MacOS: need help testing Metal3 mesh shaders

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#401]
Followup to talk in #142.
Need some help on testing, gathering data on how mesh shader run on different MacOS devices.
In principle non-mac devices are also interesting ;)

### Context:
OpenGothic has 2 types of rendering pipelines:
1. Index-driven geometry (aka brute force)
2. `GL_EXT_mesh_shader` based, with programmable removal of hidden geometry 

Naturally v2 is way faster, at least on PC, but not on Mac:
@Civil
> In the same scene on M2 Max I get 32-45 FPS, so that's much better than before, but still far from ~120 without Mesh.

@Try 
> 35-40 fps on M1 versus 60 without Mesh

### Implementation details:
Engine doesn't have Metal(or DX12) shaders, relaying on cross-compiling Vulkan shaders at load-time. Our local copy of spirv-cross is capable of translating Vulkan mesh shader to MSL, with some caveats.

Translation details:
```c++
// entry-point wrapper
[[mesh]] void main0(..., spvMesh_t spvMesh)
{
  threadgroup gl_MeshPerVertexEXT gl_MeshVerticesEXT[64]; // Vulkan build-in emulated with threadgroup-array
  ...
  // call for original main
  _4(...);
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if(spv_primitive_count==0)
  {
    return; // early-out, for empty(culled) meshlet
  }
  spvMesh.set_primitive_count(spv_primitive_count);
  // Ugly copy-pass
  for (uint spvI = gl_LocalInvocationIndex, spvThreadCount = (gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z); spvI < 64; spvI += spvThreadCount)
  {
    spvPerVertex spvV = {}; // pack Vulkan vertex-outputs into this struct
    ...
    spvMesh.set_vertex(spvI, spvV); // real store of per-vertex attributes
  }
}
``` 
Ugly pass is required to emulate Vulkan semantics on top of Metal. Metal require to provide all outputs in one call, but it's not the case for Vulkan.

Note: task/object shader is not implemented - we missing even more middle-ware here.

### Testing

Make sure that you on latest Tempest revision (some quick fixes are there)
Open `mtdevice.cpp` and un-comment :
```
  if(dev.supportsFamily(MTL::GPUFamilyMetal3)) {
    //prop.meshlets.meshShader = true;   <----
    prop.meshlets.maxGroups = prop.compute.maxGroups;
    prop.meshlets.maxGroupSize = prop.compute.maxGroupSize;
    }
```
Run game with `-ms 1` flag to enable and `-ms 0` to disable mesh shading.
Post FPS, and other relevant info into this ticket.

Also optimization ideas are welcome. 
If you happen to know how Mesh is implemented in Metal3 - also interesting. Maybe we just hit a slow-path somewhere.

**Comment by shinra-electric** [comment]
If you ask in [Mac Source Port's](https://macsourceports.com) Discord server, I'm sure you'll get some volunteers. 

They've been doing some testing of OpenGothic in the beta release channel.

**Comment by Try** [comment]
@shinra-electric thanks for pointing out!

I joined their discord today, and noted that someone already posted request for Mesh-shader testing.

**Comment by Try** [comment]
Meanwhile searching for info on how-to for Metal3, unfortunately almost nothing useful.

From semi-useful:
https://developer.apple.com/videos/play/wwdc2016/606/
(slide 44 in pdf version)
Compute shader has high startup cost. That is one way to kill our renderer, since 95% of groups will quit immediately after frustum culling stage.
Potentially(lots of work) fixable with task-shader.

**Comment by Try** [comment]
Implemented first version if task(object) shader cross-compiler.
Also can be tested now on main branch with startup key `-ms 1` 

Unfortunately, subjectively become even worse FPS-wise.
