### ISSUE TITLE
A bed can't be selected

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#411]
Observed:
Click on a bed – nothing happens
Expected: 
A dialog with options how long to sleep

Current git version.

p.s. May be related, Lothar stopped telling the rules of the town at the start of the game

**Comment by Try** [comment]
Hi, @AlexJakeGreen !

Tested on latest master - can't reproduce beds issue. Any particular bed need to be used or else?
Issue might be related to `134a6096` - this is last time MOBSI code was changed.

> Lothar stopped telling the rules of the town at the start of the game

Did he stopped completely? I mean: there might be delay, but not full stop. Might be related to `B_AssessQuietSound ` processing (d393c890)

**Comment by thokkat** [comment]
The problem with bed is that this line 
https://github.com/Try/OpenGothic/blob/134a6096ac1fd2c0e9852b4fc85412a8b09a6454/game/world/objects/interactive.cpp#L960

sets `point` back to `""`.  Using a string as temp save makes bed behave correctly.

```c++
@@ -937,6 +937,7 @@ const Animation::Sequence* Interactive::animNpc(const AnimationSolver &solver, A
   string_frm<12>   ss[2]    = {};
   string_frm       pointBuf = {};
   std::string_view point    = "";
+  std::string point2        = "";
 
   if(t==Anim::FromStand) {
     st[0] = -1;
@@ -949,9 +950,10 @@ const Animation::Sequence* Interactive::animNpc(const AnimationSolver &solver, A
 
   for(auto& i:attPos)
     if(i.user!=nullptr) {
-      point = string_frm("_",i.posTag());
+      point2 = string_frm("_",i.posTag());
       }
 
+  point = point2;
   st[1] = std::max(-1,std::min(st[1],stateNum));

```

**Comment by Try** [comment]
@thokkat  thanks for investigating!

@AlexJakeGreen should be fixed now

**Comment by AlexJakeGreen** [comment]
Bed works, thanks!
