### ISSUE TITLE
Friendly Fire

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#419]
Observed:
The quest with Diego extraction from Minnental.
Diego shoots arrows, but he always stands behind the Hero.
Almost each shot hits the Hero, making the quest a bit hard to complete.

Not sure if a friendly fire must be present here, but the quest is a mission impossible without F8.

**Comment by Try** [comment]
How Friendly Fire works in vanilla? On my side wasn't able to confirm what exact behavior should be.

In OpenGothic, for now npc checks if there an friendly character (or obstacle) on a straight line before firing

**Comment by AlexJakeGreen** [comment]
Unfortunately I'm not able to run the vanilla too :(
[save_slot_2.sav.gz](https://github.com/Try/OpenGothic/files/10892080/save_slot_2.sav.gz)
I have prepared the steps to reproduce:
1 Load the save
2 Don't move
3 Shot only 1 fireball into ork
4 Do nothing
Observed: the Hero is killed by Diego

 
![diegosfriendlyfire](https://user-images.githubusercontent.com/3207095/222968002-5d958e61-5f9b-4260-9036-f57849be4cba.png)

**Comment by Try** [comment]
Thanks for *.sav file. Should be fixed now.

**Comment by AlexJakeGreen** [comment]
Thanks for the fix. Now Diego does not shoot the Hero. Much appreciated.
