### ISSUE TITLE
Implement lock-picking minigame

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#42]

**Comment by Fabiosek** [comment]
Hmm... What do that? It could be a fun mini game and I understand you're doing a "remake" but cool if it would be optional.

**Comment by Try** [comment]
> Hmm... What do that? 

There was such minigame in original gothic: when player tries to open a locked chest, he need to guest a sequence of `<-` and `->` moves. If move sequence is correct - chest is open, if not - player losing one lock pick.

To start the game a lock-picking skill is required and at least one lock pick in inventory
