### ISSUE TITLE
Intel Arc crash

### ISSUE THREAD

**Issue by Nebulavenus** [Try/OpenGothic#426]
Intel Arc A750 crashes right after the game loading screen and intro movie. It works alright in game menu. Tested both on the old and the newest version of gothic. After searching a bit on the web, some point to freeing descriptor pool after descriptor layout was already freed. Some about incorrect descriptor layout, like image_count = 0 (I don't remember exactly). This may be correct, because I think intel vulkan drivers are stricter, newer and immature. Intel Arc Drivers are 4146. Windows 10.

[log-1891.txt](https://github.com/Try/OpenGothic/files/10930722/log-1891.txt)
[crash-1891.log](https://github.com/Try/OpenGothic/files/10930723/crash-1891.log)
[crash-1527.log](https://github.com/Try/OpenGothic/files/10930724/crash-1527.log)
[log-1527.txt](https://github.com/Try/OpenGothic/files/10930725/log-1527.txt)

**Comment by Try** [comment]
Hi, @Nebulavenus , thanks for report!

By look of crash, in both cases it's bindless set, so disabling(`-rt 0`) ray-tracing can be a temporarily solution.

**Comment by Nebulavenus** [comment]
Disabling ray tracing did the trick! Framerate was stable and high, game is playable. I did also install LunarG Vulkan SDK and tried to run it with -rt 1 and -v. It still crashes and has no clear visible errors in the logs. The -rt 0 mode works, and there are also no visible errors of vulkan validation layers. The other versions behave same. I was using prebuilt versions from CI.

[log_1966_-rt_0.txt](https://github.com/Try/OpenGothic/files/10936552/log_1966_-rt_0.txt)
[log_1966_.txt](https://github.com/Try/OpenGothic/files/10936553/log_1966_.txt)
[crash_1966.log](https://github.com/Try/OpenGothic/files/10936554/crash_1966.log)

**Comment by Try** [comment]
I've posted issue on Intel forum:
https://community.intel.com/t5/Intel-ARC-Graphics/IntelARC-OpenGothic-Vulkan-driver-crash/m-p/1464708#M2280

Looking forward for their response

**Comment by Nebulavenus** [comment]
I followed the thread and created a report using ssu at their request. If you have time, please post this on the Intel forum.
[report (1).txt](https://github.com/Try/OpenGothic/files/10995475/report.1.txt)

**Comment by Try** [comment]
@Nebulavenus 
From Intel forum:
> The latest version available at the moment is 19045. Could you advise the affected person to install all the necessary Windows Updates on their system?

Also please don;t hesitate to jump directly to conversation there)

**Comment by Nebulavenus** [comment]
I followed all advices, updated windows to latest, reinstalled drivers. Still crashing. The issue can be closed. I will test -rt with newer drivers from time to time. I also tried to test -dx12 with raytracing enabled, but it was still launching vulkan and crashing.

**Comment by Try** [comment]
I've reworked how bindless with on this week, you can check it out, if you have time: 9f24ca2d
