### ISSUE TITLE
Npc_CanSeeNpc returns wrong value, when npc sitting on a bench.

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#43]
Seem like Npc_CanSeeNpc should use BIP01 rotation, to calculate eye-dir vector.
B_AssessTalk :
```
		if(Npc_CanSeeNpc(self,other))
		{
			AI_StartState(self,ZS_Talk,0,"");
		}
		else
		{
			if(Npc_IsInState(self,ZS_ObservePlayer))
			{
				AI_Standup(self);
			};
			AI_StartState(self,ZS_Talk,1,"");
		};
```

**Comment by ErrorFlexXx** [comment]
Where is this code ? Is it a daedalus script ? Is this issue related with npcs  standing up and not turning to the hero before starting the talk ?

**Comment by Try** [comment]
The code above is in daedalus script.

Npc_CanSeeNpc itself is in gamescript.cpp:2012:
```c++
void GameScript::npc_canseenpc(Daedalus::DaedalusVM &vm) {
  ...
```

>  Is this issue related with npcs standing up and not turning to the hero before starting the talk ?

Yes, related. In fact npc behaves in sort-of reverse way: if player in from of npc -> standup, in not -> continue sitting.
