### ISSUE TITLE
cannot execute opengothic

### ISSUE THREAD

**Issue by YacineDeghaies** [Try/OpenGothic#432]
After build is complete, I cannot execute Gothic2Notr and i get this error in my terminal
I'm on macbook air M1 under macOS Ventura 13

Last login: Mon Mar 20 03:36:35 on ttys001
/Users/yasinedeghaies/Desktop/aa/simplegit-progit/OpenGothic/build/opengothic/Gothic2Notr ; exit;
(base) yasinedeghaies@YacinesMac ~ % /Users/yasinedeghaies/Desktop/aa/simplegit-progit/OpenGothic/build/opengothic/Gothic2Notr ; exit;
dyld[41845]: Library not loaded: @rpath/libTempest.dylib
  Referenced from: <03620126-608C-3ED3-81E0-70C5364C2D2A> /Users/yasinedeghaies/Desktop/aa/simplegit-progit/OpenGothic/build/opengothic/Gothic2Notr
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libTempest.dylib' (no such file), '/usr/local/lib/libTempest.dylib' (no such file), '/usr/lib/libTempest.dylib' (no such file, not in dyld cache)
zsh: abort      

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by ezamelczyk** [comment]
or you can just copy libTempest.dylib into /usr/local/lib. That's what I do but you gotta remember to update it anytime you build a new version.
