### ISSUE TITLE
[G1] Nek's body is missing

### ISSUE THREAD

**Issue by ezamelczyk** [Try/OpenGothic#433]
I'm including the save. When you go to the cave near the old camp where nek's body is supposed to be it's not there.

[save_slot_4.sav.zip](https://github.com/Try/OpenGothic/files/11052877/save_slot_4.sav.zip)

**Comment by Try** [comment]
Hi, @ezamelczyk !

We do not support G1 officially, but I'll take a look eventually.

**Comment by DragonSWDev** [comment]
@Try Out of curiosity - are there any plans to support Gothic 1 officially?

**Comment by Try** [comment]
No, no such plans. Support for G1 would mean 2x amount of testing on every significant change

**Comment by DragonSWDev** [comment]
Thanks for answer.

**Comment by thokkat** [comment]
In `wld_insertnpc`  in gamescript file `spawnpoint` parameter is empty. If the emptyness check is removed the npc is spawned correctly because the waypoint is taken from the daily routine later on when `resetPositionToTA` is called in `addNpc`.

**Comment by Try** [comment]
Fixed:
![изображение](https://github.com/Try/OpenGothic/assets/122894/6832b1ef-e299-4325-ad90-660983b4b548)
