### ISSUE TITLE
Gothic 2 NoR: Cooking meat does not remove raw meat form inventory

### ISSUE THREAD

**Issue by Gryxx** [Try/OpenGothic#438]
Tested in Xardas tower, cooking 12 pieces of raw meat resulted in 12 cooked pieces and 12 still raw. I can cook further, raw meat seems to be still a valid item that i can use.

**Comment by Try** [comment]
Hi, @Gryxx !

Thanks for reporting, this case is fixed.
yet it still not 100% how exactly items should behave, hopefully rest stuff wont break)
