### ISSUE TITLE
Compilation error with Xcode 14.3

### ISSUE THREAD

**Issue by sjavora** [Try/OpenGothic#439]
Hello again, I tried updating OpenGothic after some time and now compilation fails:
```
[  0%] Building CXX object lib/bullet3/src/LinearMath/CMakeFiles/LinearMath.dir/btAlignedAllocator.o
In file included from /Users/<name>/Downloads/OpenGothic/lib/bullet3/src/LinearMath/btAlignedAllocator.cpp:16:
In file included from /Users/<name>/Downloads/OpenGothic/lib/bullet3/src/LinearMath/btAlignedAllocator.h:23:
In file included from /Users/<name>/Downloads/OpenGothic/lib/bullet3/src/LinearMath/btScalar.h:23:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:300:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make[3]: *** [lib/bullet3/src/LinearMath/CMakeFiles/LinearMath.dir/btAlignedAllocator.o] Error 1
make[2]: *** [lib/bullet3/src/LinearMath/CMakeFiles/LinearMath.dir/all] Error 2
make[1]: *** [CMakeFiles/Gothic2Notr.dir/rule] Error 2
make: *** [Gothic2Notr] Error 2
```

This seems to be caused by Xcode 14.3 because if I `xcode-select` the older Xcode 14.2, everything works OK. Not sure what to do about it, so just raising the issue, since Xcode 14.3 is now the latest version and other people might start experiencing this..

**Comment by Try** [comment]
Hi, @sjavora !

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:300:15: fatal error: 'math.h' file not found
`
This is not related to OpenGothic code, most likely path to c++ tool-chain was changed, when you install XCode update - just regenerate project with cmake, that should be enough.

**Comment by sjavora** [comment]
Huh. it does work. I don't understand why though since I'm pretty sure I already tried rerunning all the cmake commands previously. But yep, builds now 🤔 

Thanks, have a good day!
