### ISSUE TITLE
This project deserves a Discord server

### ISSUE THREAD

**Issue by PoetaKodu** [Try/OpenGothic#442]
Just like in the title. This project has a huge potential and I think real-time discussions will greatly increase the productivity. I have many questions myself and would like to discuss many topics.

**Comment by PoetaKodu** [comment]
Thank you, I'll join it. I still think this sole project should have its own DC server, because I'm 100% sure it will blow up really soon.

**Comment by Try** [comment]
For now Gothic-Modding-Community is probably good enough. Even there not a lot of activity at this point.

**Comment by CReimer** [comment]
> Discord imposes management costs and censorship liability that IRC does not. An IRC chat channel, say on libera, quakenet, oftc can be instantiated in seconds.

The 90s called. They want their chat protocol back.
Do you want to go full retro and add a mailinglist to the mix?

**Comment by dreimer1986** [comment]
IRC is way too outdated in almost any aspect. Here some points that immediately come to mind:
- No multimedia features at all, no image inclusion, video links, or audio/video chats.
- No history when logged out (A bouncer is no solution, but a terrible hackfix if anything)
- No references to specific postings allowing separate discussions in the same room easily.
- Complicated for the Discord generation to even join. Discored can be used in browser, IRC only with other service's help.

If you want to be less commercial, then look at Mattermost. It's quite powerful and can be self hosted.

Anyways, regarding the idea at all. I am quite sure that the Chatroom at Gothic Modding community is enough right now. If things become more known, then maybe it's a good idea, but right now it's more than enough IMO.
