### ISSUE TITLE
Anyone has this working on MacOS ARM?

### ISSUE THREAD

**Issue by developer239** [Try/OpenGothic#462]
Looks great thank you for the effort! 🚀

I was unable to make this work on MacOS:

```
---crashlog(std::logic_error(gothic not found!))---
GPU: ?

invalid gothic path: ""
```

so I am wondering does anyone actually has this working on ARM?

**Comment by Try** [comment]
Hi, @developer239 !

Error in command line means, that path to gothic2 game assets is not correct.
How does your command line to run opengothic look like?

**Comment by marioyohanes** [comment]
I got it working on Apple Silicon by compiling it manually, simply follow the build guide. Note my homebrew is running on Rosetta (x86-64) mode while compiling, haven't tried in native ARM.
I also need to copy `libTempest.dylib` to `/usr/local/lib`.
If you are using binary from Mac source port, just replace `Gothic2Notr` file inside the bundle.

**Comment by divadretlaw** [comment]
Sadly not, it worked on previous builds

Followed the instructions on the README on Commit 16fff0e63df6a00e9801b64c8c72557dbeecb7f7 and it builds successfully, but when trying to run the game it instantly crashes. Both `Gothic II` and `Gothic`

```
❯ sh Gothic2Notr.sh -g "Gothic II" 
OpenGothic v1.0 dev
GPU = Apple M2 Pro
Depth format = Depth32F Shadow format = Depth16
swapchain is outdated - reset renderer
-[_MTLCommandEncoder dealloc]:131: failed assertion `Command encoder released without endEncoding'

---crashlog(SIGABRT)---
GPU: Apple M2 Pro

[1]    82785 abort      sh Gothic2Notr.sh -g "Gothic II"
```

**Comment by Try** [comment]
Hi, @divadretlaw !

There were no changes in command encoding for very long time. Can issue be related to SDK/XCode version you using?

**Comment by divadretlaw** [comment]
Using `macOS 13.4.1` & `Xcode 14.3.1`

Interestingly it works when using the built-in monitor, just seems to crash when using the external monitor 🤔

**Comment by Try** [comment]
>  just seems to crash when using the external monitor 🤔
> swapchain is outdated - reset renderer

Cool, with log message picture is more clear now. Probably in swapchain-reset is broken and was never tested, as I do not have extra monitor for testing

**Comment by PawelPerek** [comment]
Also got this error, here is the crash log with call stack in case it's useful
```Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1932cc724 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x193303c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x193211ae8 abort + 180
3   libsystem_c.dylib             	       0x193210e44 __assert_rtn + 272
4   Metal                         	       0x19c88e7a4 MTLReportFailure.cold.1 + 48
5   Metal                         	       0x19c86b348 MTLReportFailure + 464
6   Metal                         	       0x19c76c08c -[_MTLCommandEncoder dealloc] + 128
7   AGXMetalG14X                  	       0x1f9447b9c -[AGXG14XFamilyBlitContext dealloc] + 84
8   libobjc.A.dylib               	       0x192f700b4 AutoreleasePoolPage::releaseUntil(objc_object**) + 196
9   libobjc.A.dylib               	       0x192f6cb7c objc_autoreleasePoolPop + 256
10  libTempest.dylib              	       0x10404f4f8 Tempest::Detail::ImplMacOSApi::onDisplayLink(void*) + 24 (macosapi.mm:115) [inlined]
11  libTempest.dylib              	       0x10404f4f8 -[TempestWindowDelegate dispatchRenderer] + 48 (macosapi.mm:204)
12  libdispatch.dylib             	       0x193152874 _dispatch_call_block_and_release + 32
13  libdispatch.dylib             	       0x193154400 _dispatch_client_callout + 20
14  libdispatch.dylib             	       0x193162bf8 _dispatch_main_queue_drain + 928
15  libdispatch.dylib             	       0x193162848 _dispatch_main_queue_callback_4CF + 44
16  CoreFoundation                	       0x193423c54 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
17  CoreFoundation                	       0x1933e13d4 __CFRunLoopRun + 1992
18  CoreFoundation                	       0x1933e04b8 CFRunLoopRunSpecific + 612
19  HIToolbox                     	       0x19cc2ac40 RunCurrentEventLoopInMode + 292
20  HIToolbox                     	       0x19cc2aa7c ReceiveNextEventCommon + 648
21  HIToolbox                     	       0x19cc2a7d4 _BlockUntilNextEventMatchingListInModeWithFilter + 76
22  AppKit                        	       0x196601d44 _DPSNextEvent + 636
23  AppKit                        	       0x196600ee0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
24  libTempest.dylib              	       0x10404fae8 Tempest::MacOSApi::implProcessEvents(Tempest::SystemApi::AppCallBack&) + 68 (macosapi.mm:398)
25  libTempest.dylib              	       0x10404fa84 Tempest::MacOSApi::implExec(Tempest::SystemApi::AppCallBack&) + 64 (macosapi.mm:390)
26  Gothic2Notr                   	       0x102faf328 main + 496 (main.cpp:115)
27  dyld                          	       0x192fabf28 start + 2236
```

**Comment by Try** [comment]
> Interestingly it works when using the built-in monitor, just seems to crash when using the external monitor 🤔

Should be fixed now

**Comment by PawelPerek** [comment]
I can confirm that on my environment after recompilation it doesn't crash anymore, but it does show white screen indefinitely

**Comment by pashura** [comment]
just tested the latest version on M1 Max. Works good, good picture, good performance

**Comment by PawelPerek** [comment]
> just tested the latest version on M1 Max. Works good, good picture, good performance

That's interesting, are you using external monitor?

**Comment by pashura** [comment]
> > just tested the latest version on M1 Max. Works good, good picture, good performance
> 
> That's interesting, are you using external monitor?

nope, internal, 14"

**Comment by developer239** [comment]
Thank you for the swift support. I will make sure to try it today or tomorrow and I will let you know how it goes. It is possible that the crash was due to me using external monitor. Other than that I followed the instructions in the documentation step by step.

**Comment by audiocrush** [comment]
Hi,
I also get a beachball and application not responding when I try to launch the game on an external monitor.
On internal monitor it works just fine.
Unfortunately it does not write any error messages into log.txt.

My system is a M1 pro.

Otherwise it feels so awesome to finally play this game on a mac after almost 20 years :D
I remember playing this back then on my way to slow PC every day when I came back from school :D

**Comment by PawelPerek** [comment]
Unfortunately there is no way to attach internal monitor to m2 pro mac mini so I'm in a pickle

**Comment by developer239** [comment]
@audiocrush Can you please share how did you manage to run the game?

**Comment by audiocrush** [comment]
Well I just compiled it per the instructions on the main page and after some failed start attempts on my external monitor, i decided to open my macbook and started it again, and there it started up just fine without the external screen connected.
