### ISSUE TITLE
Vulkan error while compiling.

### ISSUE THREAD

**Issue by Roever1** [Try/OpenGothic#465]
When trying to compile I am getting this error:

```
$/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vulkan_sdk.h:4:10: fatal error: vulkan/vulkan.h: No such file or directory
    4 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

```

Vulkan should be installed, do I have to direct the compiler to the path?

System is POP!OS, GeForce 970
Thanks

**Comment by Try** [comment]
> Vulkan should be installed, do I have to direct the compiler to the path?

CMake should locate vulkan automatically, by using `VK_SDK_PATH` env-variable

**Comment by Roever1** [comment]
ok thanks! any idea what the problem might be? should I uninstall vulkan and try again? Do i need more than vulkan? I dont comletely understand the first dependency entry to be honest

**Comment by Roever1** [comment]
apparently Vulkan was not properly installed, this did the trick:

```
wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
sudo apt update
sudo apt install vulkan-sdk

```

Dont really see the difference to your commands though. Compiling worked for now. However, Gothic 2 Stats fast and really nice, thanks a lot!!!
