### ISSUE TITLE
ZMAXFPS limiting frame rate lower than desired value

### ISSUE THREAD

**Issue by mundifex** [Try/OpenGothic#467]
OpenGothic v1.0.1891 running on Windows 10 64-bit. Gothic 2 installation from GOG.com.

I have added the following to the Gothic.ini file in my OpenGothic folder:
```
[ENGINE]
zMaxFPS=165
```

Game is limiting frame rate to 95 FPS instead of the desired value of 165. Without ZMAXFPS, I was getting 300+ FPS. I have tried other values (e.g. 200) but the frame rate is always limited to 95.

**Comment by Try** [comment]
Hi, @mundifex !

Can confirm that setting `zMaxFPS` to 165, doesn't result in this exact frame rate (~120 on my machine, from baseline of 300)
I've double checked this today: there is no obvious problems with engine here, so probably it's related to V-sync or sleep granularity.

**Comment by mundifex** [comment]
Sleep granularity would be my (mostly uneducated) guess. 

I tried NVIDIA's Control Panel option for limiting an application's Max Frame Rate and however they're doing it successfully limits the rate to 165 (or whatever arbitrary limit the user wants).

**Comment by Try** [comment]
Hi, I've reworked `Application::sleep`, so now it uses spin-based sleep approach, that way game reaches exact FPS almost perfectly.

Almost, because wait period is still in milliseconds, so `165fps`, becomes `166.6`

**Comment by mundifex** [comment]
I built Windows binaries and tested the fix locally and it works as expected now. CPU usage goes up a bit but is comparable to NVIDIA's Max Frame Rate feature. Thanks for the improvement!
