### ISSUE TITLE
G2 classic mod - language selection doesn't work

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#473]
G2 classic mod allows playing NOTR as if it was the original non-expansion G2. v1.1 download link: https://www.worldofgothic.de/dl/download_230.htm

Running via `./Gothic2Notr.sh -g ~/Games/gothic-ii-gold-edition/drive_c/GOG\ Games/Gothic\ 2\ Gold/ -game:G2_Classic.ini` the in-game texts are in German despite the ini containing `_EN` suffixes by default. In the original the default results in English, removing the `_EN` suffixes does the switch to German.

Other than being in German, the mod appeared to work during a very short test (different main menu background, Cavalorn and Greg not present on their NOTR start points).

**Comment by Nindaleth** [comment]
The mod contents can be switched between German (no suffix) and English (`_EN` suffix) in these two places of INI:

```
[FILES]
VDF=G2_Classic.mod

Game=GOTHIC_EN
FightAI=
Menu=
Camera=
Music=
SoundEffects=
ParticleEffects=
VisualEffects=
OutputUnits=OU_EN
```

And here it is in the VDF:

![Screenshot from 2023-06-30 22-08-43](https://github.com/Try/OpenGothic/assets/6383928/c80de859-8ddd-41b6-8733-a5d574f80baa)
![Screenshot from 2023-06-30 22-08-58](https://github.com/Try/OpenGothic/assets/6383928/4b2f777f-fbfa-4173-b35b-14ddc8ce455e)

**Comment by Try** [comment]
opengothic uses "OU" files from actual file-system, not from VDF - most likely this is the problem.
relevant place is `GameScript::loadDialogOU`.

Probably also `OutputUnits=OU_EN` are relevant.

**Comment by Nindaleth** [comment]
Thanks for the pointer, I can now also see that `GameScript::GameScript` loads a hardcoded `GOTHIC.DAT` which is the other part that's variable in this mod (`Game=GOTHIC_EN`).
