### ISSUE TITLE
Using modifications

### ISSUE THREAD

**Issue by CriticalGoose** [Try/OpenGothic#483]
Hi

First of all: the project is **amazing** and I am at awe how smooth and nice it works. I salute the author and much respect for them for creating the project.

I would love to play Gothic 1/2 again, but it would be even better to play with my favorite modifications. Unfortunately I had very little success in launching the mods.

I use Linux and the vanilla game launches without any issues. I copied all necessary modification files to Gothic 1 Data/ModVDF and tried using -game: argument, pointing to the mod *.ini file. Main menu is changed as expected (so I assume that the mod *.ini file has been recognized and loaded), but the "New Game" does not launch.

This is the specific command I used and game engine response:

$ ./Gothic2Notr.sh -g1 -g ~/Games/gothic/drive_c/GOG\ Games/Gothic/ -game:~/Games/gothic/drive_c/GOG\ Games/Gothic/System/EdycjaRozszerzona+.ini
OpenGothic v1.0 dev
no *.ini file in path - using default settings
GPU = NVIDIA GeForce GTX 1660 SUPER
Depth format = Depth32F Shadow format = Depth16
loading error: unable to open file

I wonder what does it mean that the engine was "unable to open file"? Is it mod-specific problem or I do something wrong?

I will be thankful for any suggestions.

**Comment by Nindaleth** [comment]
Hi @CriticalGoose! Can you list the specific version of your mod, ideally provide a download link?

**Comment by Try** [comment]
Hi, @CriticalGoose , thanks for reporting!


@Nindaleth 
I think this issue is related to 8fa4c41904e25493779170a441bd0c8f07c1c47b. If mod had no custom *.dat file, this will result in `gameDatDef = ".DAT"`, and then rest falls apart

**Comment by Nindaleth** [comment]
@Try good catch, that was silly of me. Sent a PR that hopefully fixes it.

@CriticalGoose can you check if patch from https://github.com/Try/OpenGothic/pull/484 helps?

**Comment by CriticalGoose** [comment]
Hey,

Thanks for the response, @Try @Nindaleth .

This is the mod I try to play: https://bractwospolszczenia.pl/showthread.php?tid=1285
This is the exact download link: https://drive.google.com/file/d/1MfSqE7B7gNOpvyRou3Rl9MASCtp91r1L/view

I tried patching with #484 like this:
git pull #484
make -C build -j $(nproc)

Then I launched the game with same command as before:
$ ./Gothic2Notr.sh -g1 -g /Games/gothic/drive_c/GOG\ Games/Gothic/ -game:/Games/gothic/drive_c/GOG\ Games/Gothic/System/EdycjaRozszerzona+.ini

Unfortunatelly the issues persists.

I'm not 100% sure I do it the correct way. Please let me know if I made a mistake!

**Comment by CriticalGoose** [comment]
I apologize, after checking again I found out that the response is different now:

OpenGothic v1.0 dev
no *.ini file in path - using default settings
GPU = NVIDIA GeForce GTX 1660 SUPER
Depth format = Depth32F Shadow format = Depth16
loading error: buffer underflow at byte 7718676 while reading 482164992 additional bytes [context: slicing]

**Comment by Try** [comment]
Got up until loading screen with help of [ce4b78d](https://github.com/Try/OpenGothic/commit/ce4b78d40a16730e16c5806abd923137fc5bbfdd)

Then script-loading throws exception, due to `.text` section is smaller, than it should be.
quick workaround to phoenix, is enough to reach loading screen, yet then VM screams with error, and crashes shortly after.
```
[phoenix] vm: internal exception: pushv: no symbol found for index
[phoenix] vm: internal exception: popping instance from empty stack
[phoenix] vm: internal exception: vm: division by zero
[phoenix] vm: internal exception: tried to pop_instance but frame does not contain am instance.
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: illegal access of type 7 on symbol LOOP_CONTINUE which is another type (2)
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: illegal access of type 2 on symbol SELF which is another type (7)
[phoenix] vm: internal exception: tried to pop_reference but frame does not contain a reference.
[phoenix] vm: internal exception: illegal access of type 2 on symbol $11133 which is another type (3)
[phoenix] vm: internal exception: vm: division by zero
[phoenix] vm: internal exception: illegal access of type 2 on symbol BOSSOWIE which is another type (3)
[phoenix] vm: internal exception: tried to pop_instance but frame does not contain am instance.
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: vm: division by zero
not implemented call [NPC_HASREADIEDRANGEDWEAPON]
[phoenix] vm: internal exception: vm: division by zero
[phoenix] vm: internal exception: tried to pop_instance but frame does not contain am instance.
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: Popping instance of wrong type: N7phoenix7c_spellE, expected N7phoenix5c_npcE
[phoenix] vm: internal exception: tried to pop_reference but frame does not contain a reference.
 (  crash with infinite recursion here )
```

CC @lmichaelis 
mod download link: https://drive.google.com/file/d/1MfSqE7B7gNOpvyRou3Rl9MASCtp91r1L/view?usp=sharing
```
./Gothic2Notr.sh -g1 -g /Games/gothic/drive_c/GOG\ Games/Gothic/ -game:/Games/gothic/drive_c/GOG\ Games/Gothic/System/EdycjaRozszerzona+.ini
```

**Comment by lmichaelis** [comment]
Hm I'm not sure what's happening here. There seems to be lots of broken instructions everywhere and the VM is just trying its best. For example, `SPELL_LIGHT`:

The definition looks fine ...
```
00004bc7 <SPELL_LIGHT>
	Name: SPELL_LIGHT
	Address: b9ec2
	Size: 0
	Type: instance
	Generated: No
	Flags:
		Const: Yes
		Return: No
		Member: No
		Extern: No
		Merged: No
	File Index: 458
	Line Start: 289
	Line Count: 9
	Char Start: 8734
	Char Count: 225
	Parent: C_SPELL_PROTO (54b)
	Definition:
		instance SPELL_LIGHT(C_SPELL_PROTO)
```
but the actual bytecode is very broken:
```
000b9ec2 <SPELL_LIGHT>:
   b9ec2:	3d 01 ce 0b 00     BL 000bce01 ; <B_STOPMAGICSLEEP2>
   b9ec7:	43 ee 04 00 00     PUSHVI 000004ee ; <SELF>
   b9ecc:	40 00 00 80 3f     PUSHI 1065353216
   b9ed1:	3e 1c 01 00 00     BE 0000011c ; <AI_WAIT>
   b9ed6:	3c                 RSR
```

I would expect this to (1) call `C_SPELL_PROTO`, (2) initialize the fields of `C_SPELL` and (3) return. Calling those external AI-functions in here is not the correct behavior since they aren't even available at this time because the engine is still initializing.

This prompted me to look at the Ikarus code and it too looks like it's broken:
```
luis:_COMPILED/ $ zscript -f GOTHIC.DAT -d -s MEM_INITALL | head -n 30
00007ecd <MEM_INITALL>:
    7ecd:	09                 MOVI
    7ece:	41 98 21 00 00     PUSHV 00002198 ; <_BIN_STREAMLEN.LEN>
    7ed3:	41 97 21 00 00     PUSHV 00002197 ; <_BIN_STREAMLEN.NLEN>
    7ed8:	12                 GTE
    7ed9:	4c 3d b0 00 00     BZ 0000b03d
    7ede:	40 01 00 00 00     PUSHI 1
    7ee3:	41 98 21 00 00     PUSHV 00002198 ; <_BIN_STREAMLEN.LEN>
    7ee8:	0d                 LSL
    7ee9:	41 98 21 00 00     PUSHV 00002198 ; <_BIN_STREAMLEN.LEN>
    7eee:	09                 MOVI
    7eef:	50 d8 1a 00 00     GMOVI 00001ad8 ; <MEM_STACKPOS>
    7ef4:	41 d7 1a 00 00     PUSHV 00001ad7 ; <MEMINT_STACKPOS.POSITION>
    7ef9:	41 99 21 00 00     PUSHV 00002199 ; <_BIN_STREAMLEN.POS>
    7efe:	09                 MOVI
    7eff:	41 8d 21 00 00     PUSHV 0000218d ; <_BIN_CCNT> = 0
    7f04:	41 8e 21 00 00     PUSHV 0000218e ; <_BIN_CLEN> = 0
    7f09:	41 98 21 00 00     PUSHV 00002198 ; <_BIN_STREAMLEN.LEN>
    7f0e:	3d f0 1f 00 00     BL 00001ff0 ; <MEM_REALLOC>
    7f13:	41 8d 21 00 00     PUSHV 0000218d ; <_BIN_CCNT> = 0
    7f18:	09                 MOVI
    7f19:	41 98 21 00 00     PUSHV 00002198 ; <_BIN_STREAMLEN.LEN>
    7f1e:	41 8e 21 00 00     PUSHV 0000218e ; <_BIN_CLEN> = 0
    7f23:	09                 MOVI
    7f24:	3c                 RSR
    7f25:	41 9b 21 00 00     PUSHV 0000219b ; <_BIN_EOF.LEN>
    7f2a:	09                 MOVI
    7f2b:	41 8e 21 00 00     PUSHV 0000218e ; <_BIN_CLEN> = 0
    7f30:	41 9b 21 00 00     PUSHV 0000219b ; <_BIN_EOF.LEN>
    7f35:	41 8b 21 00 00     PUSHV 0000218b ; <_BIN_CRSR>
luis:_COMPILED/ $ zscript -f GOTHIC.DAT -d -s MEM_INITALL | wc -l
33340
```
As you can see, the first weird thing that stands out is the `BZ 0000b03d`. This makes no sense since we're at `7ecd` and the code are between `7f24` and `b03d` can never be executed anyways because of the `RSR` at `7f24`. `b03d` just contains:
```
    b03d:       40 00 00 00 00     PUSHI 0
    b042:       3c                 RSR
```
You can also see my disassembler getting confused because it outputs way too many lines.

Also this thing with the text size seems weird. Its not something like an off-by-one or rounding error since it's declared as >400MB too large. Also, the symbol table is broken shows broken entries after index `19bd7` which points to an invalid symbol count being stored in the binary.

Maybe this is some sort of obfuscation? Maybe the compression algorithm did something weird? Maybe it points to even more Ikarus/LeGo trickery? I am not sure. All I can say is: The bytecode looks very broken everywhere I look.

**Comment by CriticalGoose** [comment]
Hello @lmichaelis 
The original game launches and I managed to play it for 2-3 hours. The issue happens only while launching the modification.

**Comment by Try** [comment]
@lmichaelis 
Testing locally: game hangs at loading. context:
```c++
// model_script.cc : make_event_tag
	case mds::event_tag_type::window: {
		auto frames = a.value_or(""); // "1.0"
		std::istringstream stream {frames};

		int32_t fr = 0;
        	while (!stream.eof()) { // fails to parse string, before eof
			stream >> fr;
			evt.frames.push_back(fr);
		}
```

**Comment by Try** [comment]
After adding `.fail()` check to stream, loading fails in `model_script_dsl.cc` with multiple different `syntax_error` exceptions.

**Comment by Try** [comment]
With [8d1b9dc](https://github.com/Try/OpenGothic/commit/8d1b9dc3396684b0b7466bf821d8568170236c58) and quick-fixes for `dam_multiply`/`stringstream`/`model_script_dsl`, manage to get it running locally
(except million errors caused by ikarus)
![изображение](https://github.com/Try/OpenGothic/assets/122894/cf6ba06f-18bd-4d35-bc6b-0c94d4a17886)

Nice looking mod btw :)

**Comment by Nindaleth** [comment]
I can see something here: https://www.moddb.com/mods/gothic-edycja-rozszerzona-104-english-version

**Comment by CriticalGoose** [comment]
> Nice looking mod btw :) Curious: is there English translation ?
 
@Try This specific modification is the unofficial extension to "Edycja Rozszerzona" and it doesn't have the support of the original author. As far as I know, there is no English translation of the original, but you can try English version of "Edycja Rozszerzona+" provided by Nindaleth. I cannot recommend it to you, though, as I didn't play it before and I've read mixed opinions on this one. I hoped to try it with OpenGothic and judge it myself.

I'm happy to see that there is some progress on the technical side of things. I regret not being able to help, since my experience with programming is **very** limited. I will be happy to help any way I can and I'm glad I've learned a few things in the process here (:

I tried launching Gothic 2 with this engine without any mods and it runs even better than the first one, but I wonder why you cannot make more than one step back (blocking) at a time? Is this a conscious decision or a bug?

**Comment by Try** [comment]
> I tried launching Gothic 2 with this engine without any mods and it runs even better than the first one, but I wonder why you cannot make more than one step back (blocking) at a time? Is this a conscious decision or a bug?

no sure, I need to check it ( currently my local copy in semi-broken state :D )

> [revert "read string symbols with skipped whitespace"](https://github.com/GothicKit/phoenix/commit/72a6c42b73457f7b97b67428ee7dbde03f8a94f0)

In Gothic2 problematic symbol is `TXT_GUILDS` array:
```
const string TXT_GUILDS[66] =
{
	"Guildless",
	"Paladin",
	"Militia",
	"Citizen",
	"Magician",
	"Novice",
	"Dragon Hunter",
	"Mercenary",
	"Farmer",
	"Bandit",
	"Convict",
	"Seeker",
	"Land Dweller",
	"Pirate",
	"Water Mage",
	"D",
	"",
	"Meatbug",
...
```

"D" followed by "", represented as "D\n\n" in file, so skipping white-space symbols after string is not suppose to work.

In case of mod it's also `TXT_GUILDS`; buffer appears to be:
 "Agresor\n\nJaszczur\n". - so possibly white-space skip only hides issue.

**Comment by lmichaelis** [comment]
> so possibly white-space skip only hides issue.

Yes and no. I did implement it incorrectly but in the mod script there is a string symbol which has a count of `1`, meaning it's not an array, and a value of `<some text here>\n\n` where phoenix leaves the last `\n` untouched which causes all subsequent symbols to be read incorrectly.

**Comment by lmichaelis** [comment]
I've tested this latest patch with G1, G2 and G1 modded. The mod now loads up correctly and only Ikarus related need fixing. Those syntax errors should be considered as warnings only.

**Comment by Try** [comment]
> I tried launching Gothic 2 with this engine without any mods and it runs even better than the first one, but I wonder why you cannot make more than one step back (blocking) at a time? Is this a conscious decision or a bug?

Fixed in 6fa3f941

**Comment by CriticalGoose** [comment]
> I've tested this latest patch with G1, G2 and G1 modded. The mod now loads up correctly and only Ikarus related need fixing. Those syntax errors should be considered as warnings only.

That's amazing, @lmichaelis! For some reason it is not the case for me.

I pulled the updates:
> git pull --recurse-submodules
> make -C build -j $(nproc)

Then I launched the game to test the engine:
> ./Gothic2Notr.sh -g ~/Games/gothic

It was a success, so I tried a mod:
> ./Gothic2Notr.sh -g \~/Games/gothic -game:\~/Games/gothic/System/EdycjaRozszerzona+.ini

After choosing the "New Game" entry, I received the following error:

> OpenGothic v1.0 dev
> no *.ini file in path - using default settings
> no *.ini file in path - using default settings
> no *.ini file in path - using default settings
> GPU = NVIDIA GeForce GTX 1660 SUPER
> Depth format = Depth32F Shadow format = Depth16
> loading error: buffer underflow at byte 7718676 while reading 482164992 additional bytes [context: slicing]

I thought that maybe I didn't pull one of the updates for some reason, so I made a backup, downloaded and compiled the engine as instructed on the main git page, installed Gothic 1 again, copied mod files and nothing changed. Nothing's changed...

Am I missing something?

**Comment by lmichaelis** [comment]
Try cd-ing into `lib/phoenix` and running `git checkout main` and then `git pull` to get the latest patches of phoenix if Try hasn't updated the dependency in OpenGothic yet. Then rebuild.

**Comment by Nindaleth** [comment]
I suggest renaming the issue to contain the mod name, for better discoverability and also just in case someone wanted to pile up another mod issues in here. Not sure if @Try wants to handle the Ikarus issues in this one too?
