### ISSUE TITLE
Unit immunities

### ISSUE THREAD

**Issue by Tate39** [Try/OpenGothic#489]
Some units are supposed to be immune but aren't. 
I'm playing on opengothic-v1.0.2207 using the Gothic 2 Classic Mod provided by the Steam installation.

- The Magic Golem can be killed without the hammer from the monastery. I've done it with one of those swords that require dexterity to use.

I'm not sure about the following ones. Will check and remove/add if necessary:
- Skeletons take dmg from arrows but shouldn't?
- Elemental Golems and Magic?
- Dragons and (fire) spells?

**Comment by Try** [comment]
Hi, @Tate39 and thanks for reporting!

There was an issue with immune filter - should be fixed now
