### ISSUE TITLE
No resoltuion choice available on integrated graphics

### ISSUE THREAD

**Issue by VitalyPetrov** [Try/OpenGothic#512]
**OS:** Ubuntu 22.04
**Build:** [latest stable](https://ci.appveyor.com/project/Try/opengothic/builds/47846555)

**CPU:** Intel Core i5-1240P
**GPU:** Intel Iris Xe Graphics G7 80EUs
**RAM:** 16 Gb 

I use my OS with Xorg and  4k (3840 x 2160) resolution with fractional scaling of 1.5x factor.
The default gameplay looks super glitchy with avg 10-15 FPS (`-rt 0`).

However, if I manually switch the system resolution to 1080p the game become quite smooth. The point is -- is it possible to switch the internal game resolution without changing the system one?

**Comment by Try** [comment]
Hi, @VitalyPetrov !

Unfortunately it's not yet possible to change rendering resolution yet, but this is high priority feature, so should be implemented in next update.

**Comment by VitalyPetrov** [comment]
Great!
Thank you for your job!

I have another minor issue concerning some sound bugs (its like minor sound duplication). Should I open the separate issue for that?

**Comment by Try** [comment]
> its like minor sound duplication

Hm, can't recall any similar issues... can you describe it with more detail?

**Comment by Nindaleth** [comment]
Hi @VitalyPetrov! My friend has described the exact same issue as you did when he was trying OpenGothic for the first time. We eventually agreed it's actually #117 he's describing.

**Comment by VitalyPetrov** [comment]
Hi @Nindaleth 
Yep, it looks like the same problem

**Comment by Try** [comment]
Resolution selection is done: `full`/`75%`/`half`

Also related to integrated gpu: find -out, that on my IntelHD game is CPU bound, due to bad driver quality - mad some adjustment on how thread pool is used to address that

**Comment by VitalyPetrov** [comment]
Hi @Try 
Thanks a lot for your fix!
I rebuild the OpenGothic engine and the resolution choice is now available on "Graphics settings" section. However if I choose not the default one (`75%` / `half`) it looks like it makes no effect (even after relaunch). Should it be an excepted behavior or not?

**Comment by Try** [comment]
> Should it be an excepted behavior or not?

No, effect should be immediate. Just for clarity: option changes internal resolution of 3d renderer, while monitor-resolution and UI should be full res always

**Comment by Nindaleth** [comment]
@VitalyPetrov the changes should be visible in-game immediately after the option change, it results in a perceived rendering quality decrease - see these scaled-down 1440p screenshots:

Half:
![2023-09-28_11-31_1m](https://github.com/Try/OpenGothic/assets/6383928/4c370449-e319-41b6-8a0c-eb89dceebd0c)

Full:
![2023-09-28_11-31m](https://github.com/Try/OpenGothic/assets/6383928/e8e0d1de-e26c-48d3-b69b-51e3752863b4)
