### ISSUE TITLE
[G1] Talked to Diego in Old Camp at night when the torches switched on... Crash

### ISSUE THREAD

**Issue by dreimer1986** [Try/OpenGothic#528]
G1 German from Steam was used.  OpenGothic MSVC 2022 build of 3e7e30d01c5f367c8e6c4f6aadc6253d0477f7c1 was used.
[save_slot_5.zip](https://github.com/Try/OpenGothic/files/13198187/save_slot_5.zip)

Just walk in that save to Diego and ask about the "Ansehen im Lager" while you are talking to him the torches will activated and then it made boom. Managed to get this twice in a row, so no random crash as it seems.

```
---crashlog(ExceptionFilter)---
GPU: NVIDIA GeForce RTX 2080
0x00007ff6f85c6046: dbg::call_stack<64>::collect in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f85c5952: CrashLog::dumpStack in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f85c5b1e: exceptionHandler in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff88550c70c: UnhandledExceptionFilter in C:\WINDOWS\System32\KERNELBASE.dll
0x00007ff8880d897d: memcpy in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff8880bf027: _C_specific_handler in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff8880d430f: _chkstk in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff88804e456: RtlFindCharInUnicodeString in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff888084465: RtlRaiseException in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff88541535c: RaiseException in C:\WINDOWS\System32\KERNELBASE.dll
0x00007ff87bdeb760: CxxThrowException in C:\WINDOWS\SYSTEM32\VCRUNTIME140D.dll
0x00007fffd85155e1: Tempest::SoundEffect::Impl::Impl in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd85148c9: Tempest::SoundEffect::SoundEffect in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd85123b0: Tempest::SoundDevice::load in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ff6f85928ef: SoundFx::getEffect in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f836b3ad: GameSession::loadSound in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f8692d6a: WorldSound::implAddSound in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f86919ec: WorldSound::tick in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f8655427: World::tick in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f836b645: GameSession::tick in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f83b0233: Gothic::tick in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f85147b0: MainWindow::tick in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f8513ce4: MainWindow::render in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007fffd8521eae: Tempest::EventDispatcher::dispatchRender in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd852afcb: Tempest::SystemApi::dispatchRender in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd8516821: Tempest::WindowsApi::implProcessEvents in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd8516671: Tempest::WindowsApi::implExec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd852b303: Tempest::SystemApi::exec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007fffd851c5c6: Tempest::Application::exec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ff6f850b3d1: main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f88f2229: invoke_main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f88f20ce: __scrt_common_main_seh in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f88f1f8e: __scrt_common_main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6f88f22be: mainCRTStartup in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff886e1257d: BaseThreadInitThunk in C:\WINDOWS\System32\KERNEL32.DLL
0x00007ff88808aa78: RtlUserThreadStart in C:\WINDOWS\SYSTEM32\ntdll.dll
```

**Comment by dreimer1986** [comment]
MSVC Debugger attached:

0x0000020faf225520 {dev=0x0000020f029afb80 {data=unique_ptr {dev=shared_ptr {dev=0x0000020f2c775fe0 {StateLock=unlocked Backend=unique_ptr {mDevice=0x0000020f2c775ff0 {Connected=true Type=Playback (0 '\0') Frequency=48000 ...} } ...} ...} [5 strong refs, 1 weak ref] [make_shared] ...} } ...}

Unhandled exception at 0x00007FF88541535C in Gothic2Notr.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x000000CCBCEF8778.

![image](https://github.com/Try/OpenGothic/assets/29841368/4fbaed3a-bd65-47be-9d0e-92d7c35a522a)

**Comment by Try** [comment]
Hi, @dreimer1986 !

It doesn't crash on my machine. Maybe it due to different OpenAL backends, what is value of `alGetError()` on your side?

**Comment by dreimer1986** [comment]
You really need to wait a bit until the torches are lit when you talk to him. I walk over almost to Mordrag first and then immediately run back through the market.

Well, I am able to get the error when I don't change anything Code wise. I tried adding "Tempest::Log::e(alGetError());" to line 37 of soundeffect.cpp. Funny thing now.... I cannot reproduce it anymore... Yes, I now know of the immediate window:

![image](https://github.com/Try/OpenGothic/assets/29841368/b9c8c478-34df-4439-bad2-48fc36eb14f7)

My former experiment with added logging had other interesting results btw. Most of the time it's 0. Sometimes it's 40965, but never it was 40964 with the added line...

**Comment by Try** [comment]
Manage to reproduce the issue.
OpenAL has internal limit of 256 sound per context, and emits `AL_OUT_OF_MEMORY`, when reached. In that case engine will convert this ret-code to `bad_alloc` exception.

Unfortunately there seen to be not way to truly fix that: no `alGet` function to test limit and no options for dynamic resizing.
Add try-catch for now to avoid crash

**Comment by dreimer1986** [comment]
Confirmed fixed though. All fine after a dozen tests. :D
