### ISSUE TITLE
[G1] Stealing and walking in the sheds of old camp is a piece of cake

### ISSUE THREAD

**Issue by dreimer1986** [Try/OpenGothic#529]
G1 German from Steam was used. OpenGothic MSVC 2022 build of https://github.com/Try/OpenGothic/commit/3e7e30d01c5f367c8e6c4f6aadc6253d0477f7c1 was used.

I almost completely emptied the chests of the lower ring by now. Result. No one cares at all... Well... except one guy living right of Skip's shed (the one with a door) on the market. He was pissed and then did not detect that I left the shed already and attacked me.

**Comment by dreimer1986** [comment]
Is this a general awareness problem? Sometimes it works, but sometimes even if you leave the shed again, they still think you are inside and attack you. Similar to the happening somewhere else. The bar next to the old camp I tried to get by by weapon drawing and they still complained and attecked me even after the did put the wapon away for ages at that time.

**Comment by Try** [comment]
> Is this a general awareness problem?

Yes, in opengothic npc react only if aiQueue is empty and there is no pending waits (aiWait)

**Comment by Try** [comment]
Closing in favor of https://github.com/Try/OpenGothic/issues/604
