### ISSUE TITLE
Black screen Mac M1 (Mac Source Ports)

### ISSUE THREAD

**Issue by lectricas** [Try/OpenGothic#533]
Hi. 
I've downloaded Gothic 2 gold edition from gog(actually I pirated it, but I think it is not the case)
Then I've extracted it using MacSourcePorts extractor tool and got two folders: `app and tmp`.
I've copied the content of the app folder into `~/Library/Application Support/OpenGothic`
Then I downloaded the dmg file from MacSourcePorts and run it. Movies were ok, but when the mage started talking, I got black screen with only mana and hp bars visible. I though it just a glitch, but after restart, I got the same result. Help me guys!

<img width="1280" alt="Screenshot 2023-11-12 at 22 08 51" src="https://github.com/Try/OpenGothic/assets/8782219/c139b582-b260-42c6-a74b-6eaf022147d5">

**Comment by Try** [comment]
Hi, @lectricas and thank for report!

Steam version works on M1, mean GoG files are probably just slight different. Can you show what is in your `log.txt` file? Thanks.

**Comment by lectricas** [comment]
@Try hi! I don't have log.txt file, I only have crash.log file. It says that my graphic card is Apple m1. When I provided wrong game files, it said that gothic was not found.

Can you tell me where to find log.txt or how to enable logging?

**Comment by lectricas** [comment]
Here it states that I need to download a gog copy (they even included the gog link) https://www.macsourceports.com/game/gothic2

**Comment by lectricas** [comment]
`~ % /Applications/OpenGothic.app/Contents/MacOS/Gothic2Notr ; exit;
OpenGothic v1.0 dev
no *.ini file in path - using default settings
no *.ini file in path - using default settings
GPU = Apple M1
Depth format = Depth32F Shadow format = Depth16
[phoenix] world: parsing object [MeshAndBsp % 0 0]
[phoenix] bsp_tree: parsing chunk c000
[phoenix] bsp_tree: parsing chunk c010
[phoenix] bsp_tree: parsing chunk c040
[phoenix] bsp_tree: parsing chunk c045
[phoenix] bsp_tree: parsing chunk c050
[phoenix] bsp_tree: parsing chunk c0ff
[phoenix] mesh: 1 bytes remaining in section b020
[phoenix] world: parsing object [VobTree % 0 0]
[phoenix] world: parsing object [WayNet % 0 0]
[phoenix] world: parsing object [EndMarker % 0 0]
invalid particle system: "INVISIBLE_VOBBOX.3DS"
unable to load sound fx: ENV_NIGHT_TONSOFINSECTS
unable to load sound fx: OW_BIRD11
[phoenix] model_script: unexpected value for event_tag_type: "		"
[phoenix] model_script: 4 bytes remaining in section f5a3`

**Comment by lectricas** [comment]
% /Applications/OpenGothic.app/Contents/MacOS/Gothic2Notr ; exit;
OpenGothic v1.0 dev
no *.ini file in path - using default settings
no *.ini file in path - using default settings
GPU = Apple M1
Depth format = Depth32F Shadow format = Depth16
[phoenix] world: parsing object [MeshAndBsp % 0 0]
[phoenix] bsp_tree: parsing chunk c000
[phoenix] bsp_tree: parsing chunk c010
[phoenix] bsp_tree: parsing chunk c040
[phoenix] bsp_tree: parsing chunk c045
[phoenix] bsp_tree: parsing chunk c050
[phoenix] bsp_tree: parsing chunk c0ff
[phoenix] mesh: 1 bytes remaining in section b020
[phoenix] world: parsing object [VobTree % 0 0]
[phoenix] world: parsing object [WayNet % 0 0]
[phoenix] world: parsing object [EndMarker % 0 0]
invalid particle system: "INVISIBLE_VOBBOX.3DS"
unable to load sound fx: ENV_NIGHT_TONSOFINSECTS
unable to load sound fx: OW_BIRD11
[phoenix] model_script: unexpected value for event_tag_type: "		"
[phoenix] model_script: 4 bytes remaining in section f5a3

**Comment by lectricas** [comment]
The poblem was that gamma settings was too low.

**Comment by Try** [comment]
> The poblem was that gamma settings was too low.

Thanks for looking into this! I've added a default values, that engine will use, if those are absent from .ini file
