### ISSUE TITLE
Only Grey Screen on MacBook M3, works fine with -window Parameter

### ISSUE THREAD

**Issue by yankun** [Try/OpenGothic#540]
Hi, I'm trying to run the game on a MacBook M3. But unfortunately it only starts into a grey screen. I can hear the background music and even blindly start a game, hear the voices etc. but no picture. Only if I start the game with the -window Parameter I can see the menu and the graphics. Following is outputted on the Terminal when running the game in fullscreen:

> opengothic_osx % ./Gothic2Notr.sh -g2 -nomenu
> OpenGothic v
> no *.ini file in path - using default settings
> GPU = Apple M3 Max
> Depth format = Depth32F Shadow format = Depth16
> swapchain is outdated - reset renderer
> not implemented call [PERC_SETRANGE]
> [phoenix] world: parsing object [MeshAndBsp % 0 0]
> [phoenix] bsp_tree: parsing chunk c000
> [phoenix] bsp_tree: parsing chunk c010
> [phoenix] bsp_tree: parsing chunk c040
> [phoenix] bsp_tree: parsing chunk c045
> [phoenix] bsp_tree: parsing chunk c050
> [phoenix] bsp_tree: parsing chunk c0ff
> [phoenix] mesh: 1 bytes remaining in section b020
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> [phoenix] world: parsing object [VobTree % 0 0]
> swapchain is outdated - reset renderer
> [phoenix] world: parsing object [WayNet % 0 0]
> swapchain is outdated - reset renderer
> [phoenix] world: parsing object [EndMarker % 0 0]
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> invalid particle system: "INVISIBLE_VOBBOX.3DS"
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> unable to load sound fx: ENV_NIGHT_TONSOFINSECTS
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> unable to load sound fx: OW_BIRD11
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> [phoenix] model_script: unexpected value for event_tag_type: "		"
> [phoenix] model_script: 4 bytes remaining in section f5a3
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer
> swapchain is outdated - reset renderer

**Comment by Try** [comment]
Hi, @yankun !

Unfortunately wasn't able to reproduce the issue on my M1, so had to relay on code-review. There were a few calls to `[[NSScreen mainScreen]]` with assumption that system can have only one display - this is fixed in [93cf875](https://github.com/Try/OpenGothic/commit/93cf87523e918eb2604d4aee1e0872215bdca205)

Also, if you have some spare time, can you please check if mesh-shader based rendering works well (faster than default) for you on M3? To enable it just use `-ms 1` in commandline. Thanks!

**Comment by yankun** [comment]
Same, the game runs constantly at around 120fps, if I can trust the in game output in Marvin mode with toggle frame.
