### ISSUE TITLE
Fast move movements move camera rapidly

### ISSUE THREAD

**Issue by hellozyemlya** [Try/OpenGothic#541]
Hello. First of all thanks for nice work.

Question - is it possible to remove rapid camera movement when mouse moved fast?

OS is windows 10, e216584d45af3576e46dac6962c56c72397710fd ci build of OpenGothic

**Comment by Try** [comment]
Hi, @hellozyemlya !

I'm not sure, if I do understand you right on what exactly is "rapid movement". Do you want camera to have it's own rotation speed and chaise the character, like in gothic3 ?

**Comment by hellozyemlya** [comment]
Hm, compared to original g2, when you move mouse, rotation speed of character will be limited at some point, while in OpenGothic very fast movement will rotate character super fast, much faster than original g2 engine. That is probably related to rotation speed of character. And no, nothing about g3-like camera.

**Comment by Try** [comment]
Tested original G2-notr today; I see what you mean it seems: mouse driven rotation is allowed at very high speed, yet has a limit.
