### ISSUE TITLE
Weapon should not be usable during dialog

### ISSUE THREAD

**Issue by abelsromero** [Try/OpenGothic#545]
version: git commit https://github.com/Try/OpenGothic/commit/ae841fbf0aa8476a1aef0cc925053a59e004682e
env: Linux

I noticed that you can draw the weapon during dialogs which is not available in the original.

**Comment by Try** [comment]
It's available in vanilla as well ;)
![изображение](https://github.com/Try/OpenGothic/assets/122894/a06bf7b3-bab7-4032-9c92-656acfe07e7d)

**Comment by abelsromero** [comment]
Not in the Vanilla Steam version, I could force it only once with a random NPC during the initial dialog from the NPC. I could draw the weapon, but after that there's no way to hide it again, basically SPACE is ignore and same with all other NPCs, I could for instance not force it with Xardas or Vatras.
But in OpenGothic with Vatras I can draw/hide the weapon constantly, during his dialogs and while he's waiting for ans answer too. It does not seem to affect gameplay, but it seems to me more a bug of the original since it requires some special conditions. Tbh is more an nuisance when you press space accidentally.

**Comment by abelsromero** [comment]
GOG version is different (what a nice rabbit hole), it queues commands :rofl: 
So if you press `1` or `space` it does nothing while you have the dialog options open, but when the dialog closes and conversation audio rolls, the character starts to the weapon animation as many times as you push the buttons.
