### ISSUE TITLE
Objects overflow interior

### ISSUE THREAD

**Issue by abelsromero** [Try/OpenGothic#546]
version: git commit ae841fbf0aa8476a1aef0cc925053a59e004682e
env: Linux

Furniture from Constantino overflows on the outside, as seen in the image, the cabinet protrudes on the outside.

![image](https://github.com/Try/OpenGothic/assets/5781153/7eb1e537-d2f4-49dd-9119-3e9c2a247512)

Not in the original (Steam, default Proton)
![image](https://github.com/Try/OpenGothic/assets/5781153/c526a30c-c412-4679-a000-fe879f804d7b)

**Comment by Try** [comment]
Hi, @abelsromero !

> Furniture from Constantino overflows on the outside, as seen in the image, the cabinet protrudes on the outside.

This is somewhat expected: culling behavior is different across engines. OpenGothic relies on BBox - so furniture is visible.
Vanilla is likely assigns every object to room, and couples it with portal subsystem - we wont to it.

**Comment by abelsromero** [comment]
This is far beyond my knowledge, but would it make sense to keep this open as a "help wanted" or something like that in case someone with the skill sees it? Ot some "known issues" thin, I fear I will come up again.

**Comment by Try** [comment]
This is not about skill. In original game :
* level-designer made some mistake when put this closet into the wall.
* some other bug exists, that make this closet as non-visible, when player is out of room - hide the first issue

While this is common bug for portal/sector based game, there is no intent to replicate it. Also no intent to use portals for visibility.

**Comment by abelsromero** [comment]
> some other bug exists, that make this closet as non-visible, when player is out of room - hide the first issue

Thanks for the explanation, that settles it. I understand this is one of those "not a bug, a feature" things 😄
