### ISSUE TITLE
Running Gothic2Notr.exe does not work

### ISSUE THREAD

**Issue by rokuroo32** [Try/OpenGothic#547]
Ive tried to run the Gothic2Notr.exe and it did not work out. I've got the following crash report: 

0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
OpenGothic v1.0.2207
invalid gothic path: ""

---crashlog(std::logic_error(gothic not found!))---
GPU: ?
0x0000000140259776: dbg::call_stack<64u>::collect(unsigned int) in Z:\home\t\Dow
nloads\Gothic2Notr.exe
0x000000014010480c: CrashLog::dumpStack(char const*) in Z:\home\t\Downloads\Goth
ic2Notr.exe
0x0000000140104d68: terminateHandler() in Z:\home\t\Downloads\Gothic2Notr.exe
0x00000003be975836: [unknown function] in Z:\home\t\Downloads\libstdc++-6.dll
0x00000003bea72183: [unknown function] in Z:\home\t\Downloads\libstdc++-6.dll
0x00000003bea7b396: [unknown function] in Z:\home\t\Downloads\libstdc++-6.dll
0x000000014000fbd1: CommandLine::CommandLine(int, char const**) in Z:\home\t\Dow
nloads\Gothic2Notr.exe
0x000000014031050e: main in Z:\home\t\Downloads\Gothic2Notr.exe
0x00000001400012ee: __tmainCRTStartup in Z:\home\t\Downloads\Gothic2Notr.exe
0x00000001400013e6: WinMainCRTStartup in Z:\home\t\Downloads\Gothic2Notr.exe
0x000000007b629339: BaseThreadInitThunk in C:\windows\system32\kernel32.dll
0x000000017005f573: RtlUserThreadStart in C:\windows\system32\ntdll.dll

My system is Ubuntu 22.04 with 6.2.0-39-generic. My graphic card is a GTX 1650. I also installed the vulkan sdk and followed the installation instructions. What's the problem here?

**Comment by Try** [comment]
Hi @rokuroo32 !

In your log there is a message:
```
 ---crashlog(std::logic_error(gothic not found!))---
```

meaning , that you need to provide path to game directory, for example:
`./Gothic2Notr.exe -g "C:/Program Files (x86)/Steam/steamapps/common/Gothic II"`

> My system is Ubuntu 22.04 with 6.2.0-39-generic

Out of curiosity, what is the reason to not use Linux build? We have them at nightly: 
https://ci.appveyor.com/project/Try/opengothic/build/job/0k16koq6u12rbrnq/artifacts

**Comment by rokuroo32** [comment]
Thanks, that worked for me!
