### ISSUE TITLE
Open Gothic crashes

### ISSUE THREAD

**Issue by rokuroo32** [Try/OpenGothic#549]
Hello, 

 My system is Ubuntu 22.04 with 6.2.0-39-generic. My graphic card is a GTX 1650. I also installed the vulkan sdk and followed the installation instructions. When I use the command  ./Gothic2Notr.sh -g /home/t/Documents/gothic2/ a window opens and then closes. I get the following crash result: 

---crashlog(std::runtime_error())---
GPU: NVIDIA GeForce GTX 1650
#1:  - /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277) [0x7f3460eae277]
#2:  - /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae4d8) [0x7f3460eae4d8]
#3: GothicShader::get(std::basic_string_view<char, std::char_traits<char> >) - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(_ZN12GothicShader3getESt17basic_string_viewIcSt11char_traitsIcEE+0x423f) [0x5604a5c510af]
#4: Shaders::ambientLightShader(std::basic_string_view<char, std::char_traits<char> >) - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(_ZN7Shaders18ambientLightShaderESt17basic_string_viewIcSt11char_traitsIcEE+0x7d) [0x5604a5c46f5d]
#5: Shaders::Shaders() - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(_ZN7ShadersC1Ev+0x2950) [0x5604a5c4aec0]
#6: Renderer::Renderer(Tempest::Swapchain&) - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(_ZN8RendererC2ERN7Tempest9SwapchainE+0x619) [0x5604a5c3f319]
#7: MainWindow::MainWindow(Tempest::Device&) - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(_ZN10MainWindowC1ERN7Tempest6DeviceE+0xe6) [0x5604a5c61bd6]
#8: main - /home/t/Downloads/OpenGothic/build/opengothic/Gothic2Notr(main+0x205) [0x5604a5affcf5]

I also have the GD3D11 Renderer from khiridis installed.

What's the problem here? I just followed the instructions for the OpenGothic build-in.

**Comment by Try** [comment]
Hi, @rokuroo32 and thanks for noticing!

Issues already been reported here and should be already fixed in latest commit: https://github.com/Try/OpenGothic/issues/548
