### ISSUE TITLE
Can't save the game [linux]

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#55]
I tried to debug it some time now, but this seems to be a bit tricky.

So here are the infos I got:
- Terminal output says: "_loading_ error: unable to open file"
- Inside the game, the text is displayed: "unable to write savegame file."
- A savefile is created with filename: save_slot_1.sav and it has 963,7 kB. It's located beneath the Gothic2Notr executable.
- One time I saw, he stopped in bool GameMenu::implUpdateSavThumb(GameMenu::Item& sel)
while reading the SaveGameHeader. He wanted to read 4 but only read 0.
The callstack looked like this was another thread.

Not easy to find, but it smells like a race condition, or ?
I'll continue searching, but maybe you already have an idea.

**Comment by Try** [comment]
There was a similar issue in https://github.com/Try/OpenGothic/issues/16#issuecomment-618555007
On which game revision you saw the issue?
Can you check revision 43ae89b[with submodule update] and verify the it?

**Comment by ErrorFlexXx** [comment]
Just rechecked and yes you're right. 
The issue is already fixed.
I got tricked by github - I "rebased" my fork with a pullrequest and github updated my files but not the submodules.

Thank you!
