### ISSUE TITLE
When walking, Nameless will fall from edge

### ISSUE THREAD

**Issue by KhazAkar** [Try/OpenGothic#550]
Hi,
I've managed to run OpenGothic using original G2:NotR files (polish version) and in few minutes of gameplay, to test something, I've tried old known thing working in original game, where if you walk (not run like default, just slowly walk), Nameless won't fell off the edge. 
In current implementation, hero just falls, but in original, it didn't. Would be great to have it fixed (if it's a bug) or documented (as deviation from original engine)

**Comment by Try** [comment]
This is how it look on my end:


https://github.com/Try/OpenGothic/assets/122894/cb09074e-1767-4a03-a6ea-8a84acb7a56d


Straight fall is prevented, but sliding is allowed.

**Comment by KhazAkar** [comment]
Will show on my end as soon as possible.I'm testing it near Xardas tower, near edge where you have healing weed.

**Comment by KhazAkar** [comment]
https://github.com/Try/OpenGothic/assets/12693890/9e5c4c8d-8eaa-405d-b267-98e91f5a07bb

Near Xardas tower.

**Comment by Try** [comment]
Should be closer to vanilla now([0fa305f](https://github.com/Try/OpenGothic/commit/0fa305fafbf14c4d945ca866be1c5fac3f1df875))
