### ISSUE TITLE
How do I play OpenGothic with the GD3D11 Renderer?

### ISSUE THREAD

**Issue by rokuroo32** [Try/OpenGothic#551]
Hello I've installed the GD3D11 Renderer from Khiridis on my Linux 22.04 System. But it is not detected. I start OpenGothic und nothing happens... I also don't have a mod.ini file.. But that was never importend for the GothicStarter.exe. What did I do wrong?

**Comment by Try** [comment]
Readme:
```
Modifications
...
Gothic2Notr.exe -game:Karibik.ini
What's working?
...
What's not?
...
    DX11 Renderer - same as Union, but don't worry - OpenGothic has nice graphics out of the box
```

Also not clear why downgrade renderer to DX11?

**Comment by rokuroo32** [comment]
GD3D11 has better models + more settings

**Comment by Try** [comment]
Since enabling GD3D11-mod is not possible, can you highlight what 'settings' are missing, so we can implement them?

> has better models

Didn't know they do that... eh just use content mods :D
