### ISSUE TITLE
Scripts and .vdfs

### ISSUE THREAD

**Issue by rokuroo32** [Try/OpenGothic#553]
Hello,
does OpenGothic has a problem with scirpts and .vdfs files? Is there a buildin option for a not secure build in to load .vdfs files? Because most Mods are .vdfs files. 
Am I right that .vdfs fiels and mods like https://www.worldofgothic.de/dl/download_671.htm could not be load?
Is it compatible with Ninja Mods?

**Comment by Try** [comment]
Readme:
```
Modifications
...
What's not?
...
    Union (32 bit and Windows only, https://github.com/Try/OpenGothic/issues/195)
    DX11 Renderer - same as Union, but don't worry - OpenGothic has nice graphics out of the box
    AST sdk
    Ninja
```

PS
if you want to ask question, no need to start a new issue. You can add it to issue where it already discussed: https://github.com/Try/OpenGothic/issues/552
Also, for small questions/chat there is a discord: https://discord.com/channels/989316194148433950/1006242446860107888

**Comment by thokkat** [comment]
Can you add discord link to readme, so people know it exists? Forgot that in the last update.

**Comment by Try** [comment]
> Can you add discord link to readme, so people know it exists? 

Done - added a badge
