### ISSUE TITLE
Playing with Gothic 1 movement style off makes casting spells buggy 

### ISSUE THREAD

**Issue by KhazAkar** [Try/OpenGothic#554]
Tested on newest commit. Pop OS 22.04, R5 4800H + RX 5500M.
When casting spells with gothic 1 movement style set to Off, casting spells can be buggy - like you need multiple mouse clicks to work.

Can't upload video on GitHub (too large file), will be available here (expires in 2 days) : https://streamable.com/z6mhfp

**Comment by Try** [comment]
0:20, when fire-ball doesn't fly, right?

**Comment by KhazAkar** [comment]
@Try exactly. it can happen when shooting with Bow, too. On vanilla, I've seen that some sort of 'auto pointing' happens when using gothic 2 style movement, here it seems that engine struggles between g1 and g2 styles when using ranged attacks.

**Comment by Try** [comment]
Hi, @KhazAkar !

Issue should be fixed now
