### ISSUE TITLE
[Linux] Mouse Camera Move Only Goes Left to Right

### ISSUE THREAD

**Issue by d10sfan** [Try/OpenGothic#56]
This is to track the Linux issue I found where with the X11 improvements (https://github.com/Try/MoltenTempest/pull/8), the mouse camera only goes left and right, instead of along with up and down. You can assign that to me if you'd like, and I'll research what could be happening.

**Comment by Try** [comment]
Moved this issue to OpenGothic repo, most likely it's a game-level issue

**Comment by ErrorFlexXx** [comment]
For me the camera goes only up and down and I have to hold the left mouse button, move the mouse and release the mouse button and after the releasing of the mousebutton the camera position updates. So as a one shot.

My system is a XUbuntu 18.04.4 with NVidia graphic.

**Comment by Try** [comment]
@ErrorFlexXx this is expected behavior for window-mode, but as far as I understand @d10sfan observe this issue, while run game in Fullscreen.

**Comment by d10sfan** [comment]
@ErrorFlexXx There was some code merged in pretty recently that allowed for full screen mode in Linux. Have you tried that? I'm looking into an issue where the mouse will not move up and down for some reason. But I don't have to click any mouse buttons to look around

**Comment by ErrorFlexXx** [comment]
Yes, I started it. In fullscreen mode I don't have to press mouse buttons. 
But with this, there is the problem, that the fullscreen is on monitor 2, while the mouse is on monitor 1. So the camera gets updated if I move the mouse to monitor 2 and then the mouse gets back centered on monitor 1.

I may try to start it with only one monitor activated tomorrow and recheck.

**Comment by ErrorFlexXx** [comment]
Ok, I have rechecked with only one monitor activated.
The mouse is working on both axes.

**Comment by d10sfan** [comment]
Ok I'll try again on mine as well. I'll see if there's a way to pick the monitor the full screen goes to

**Comment by d10sfan** [comment]
I was able to replicate it again (the moving from left to right). I'll see what I can find out.

**Comment by d10sfan** [comment]
I narrowed it down to the following commit: https://github.com/Try/OpenGothic/commit/f62bf0e156293cac92a931d5de1a0dbdb96fcc4d

If I revert that one locally, then the mouse works for panning up and down, as well as left and right, although it's very sensitive. If I put back, I can move left to right well, but up and down is basically stuck.

**Comment by d10sfan** [comment]
@Try Are you able to see this on Windows as well? Or is this something Linux-specific? I noticed that if I hold down the right mouse I can look around normally and then the y-axis somewhat works and then gets stuck again.

**Comment by Try** [comment]
@d10sfan 
Hm, what you describing is very similar to game behavior in **window** mode, while in fullscreen mouse should behave same way as in original gothic2.

**Comment by d10sfan** [comment]
Strange, since it seemed to start doing that after the commit, so at least the low level seems to know it's in full screen mode

**Comment by Try** [comment]
> Once it's in full-screen mode, does the game query the engine's isFullScreen function repeatedly?

Yes, it does, there total 4 places, all of them in `mainwindow.cpp`. Most suspicious to me is:
```c++
void MainWindow::tick() {
  ...
  const bool followCamera=player.isInMove();
  if(player.tickMove(dt)) {
    auto& camera = *pcamera;
    if(auto pl=gothic.player()) {
      camera.setMode(solveCameraMode());
      camera.follow(*pl,dt,followCamera,
                    (!mouseP[Event::ButtonLeft] || currentFocus || SystemApi::isFullscreen(hwnd())) && !inventory.isActive());
      }
    }
  }
```

**Comment by d10sfan** [comment]
@Try Thanks!

I tried the following and that didn't seem to help, mainly trying to avoid the isFullscreen check:

```
void MainWindow::tick() {
  ...
  const bool followCamera=player.isInMove();
  if(player.tickMove(dt)) {
    auto& camera = *pcamera;
    if(auto pl=gothic.player()) {
      camera.setMode(solveCameraMode());
      camera.follow(*pl,dt,followCamera, true);
      }
    }
  }
```
Another interesting point of data, is either mouse button being held down lets me do left-right and up-down. Also opening the inventory made it work both ways as well.

**Comment by ErrorFlexXx** [comment]
@d10sfan which distro/graphic card/driver are you  testing on ? Maybe I can try to reproduce your problem on my machine as well.

**Comment by d10sfan** [comment]
@ErrorFlexXx I am running Manjaro with Nvidia graphics. This was a recent issue, caused by the https://github.com/Try/OpenGothic/commit/f62bf0e156293cac92a931d5de1a0dbdb96fcc4d commit.

**Comment by Try** [comment]
I'm not 100% about it, but probably the key is not in Linux, but in gothic-version.
@d10sfan you runing a steam gothic2-gold, or DVD version, or else?

Offended place:
```c++
    + float shift0 = def.veloRot*dtF;
    ...
    - float shift = def.veloRot*dtF*60.f; // my guess: speed is angle per frame
    + float shift = shift0;
```
Probably interpretation of C_Camera::veloRot is not correct.

**Comment by d10sfan** [comment]
@Try I'm using Gothic 2 from Steam.

**Comment by Try** [comment]
I've decided not just rollback the commit, but add a proper script-driven implementation of camera instead.
Reason: old implementation was a very primitive approximation of gothic camera - fixing it won't do much.

**Comment by d10sfan** [comment]
Thanks, that's looking alot better. I believe this one can be closed then.
