### ISSUE TITLE
NPC behaviour curiosities, maybe due to full map life simulation?

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#565]
- escorting NPCs like Lares do not wait for player to follow (unless there is a dialog to be triggered). The NPC will continue to run even if out of viewable distance. My suspicion is this could be due to the full life simulation on the map.

- Grimbald the hunter: When I first arrived there, only one snapper was there. My suspicion is that Grimbald killed them already over time but I am not sure. I found no snapper corpses.

**Comment by Nindaleth** [comment]
@Abendlied Yes, you're right about the full simulation cauing both of these.

However, if Lares in original stops for the player to catch him (even within visible range), he still should do that in OpenGothic. Is there such issue?

**Comment by Try** [comment]
Hi @Abendlied !

> escorting NPCs like Lares do not wait for player to follow 

Hm, sort of yes and no. In game-scripts of original game npc suppose to wait for you, but it not always - it just doesn't work well.
When it doesn't - in vanilla npc teleport it the finishing point, in opengothic it walks there.
Lares script is different and he programed to wait for you (this is why he has dummy dialogs along the way) - this should be similar in opengothic.

> My suspicion is that Grimbald killed them already over time but I am not sure. I found no snapper corpses.

I've seen such issue a few times, yet it hard to catch it in action. My theory snappers scudded on a nearest cliff  and issue is might be related to https://github.com/Try/OpenGothic/issues/542

**Comment by Abendlied** [comment]
Thanks for the replies.

> However, if Lares in original stops for the player to catch him (even within visible range), he still should do that in OpenGothic. Is there such issue?

>Lares script is different and he programed to wait for you (this is why he has dummy dialogs along the way) - this should be similar in opengothic.

I can confirm, Lares dummy dialogues work and Lares will be waiting there. But he will run uninterrupted to the next dummy dialog spot and does not wait inbetween if player does not catch up.

I noticed that 
- Mika does not wait for you if he escorts you to Akils, he will only stop at Akils.
- If I let Lares guide me to the forest stone ring and trigger the escort to Onars from there, he has no intermediate script and will walk the whole way only to stop at Orlans, his final destination with a dialog.

**Comment by Abendlied** [comment]
> I've seen such issue a few times, yet it hard to catch it in action. My theory snappers scudded on a nearest cliff and issue is might be related to https://github.com/Try/OpenGothic/issues/542
@Try You might be right. I went to Grimbald again and used F8 and K to see if monsters were clipping through somewhere. I actually found two snappers swimming in the lake just next to the cliff.

![image](https://github.com/Try/OpenGothic/assets/86957596/b0344f0a-6e85-4533-978c-ef081a62eadd)

**Comment by thokkat** [comment]
> escorting NPCs like Lares do not wait for player to follow

Reverting https://github.com/Try/OpenGothic/commit/8716db0b2e4ce5e5baa893ac1433b8b209c8d5ef makes it work. 

Script loop is not executed because Lares is in goto mode, so `PERC_ASSESSPLAYER`'s function  `B_AssessGuidePlayer()` was used as replacement loop that checks distance. Commit prevented that perc trigger.

They used sense smell as bypass to get the trigger. Script comment says sense smell is required for Lares because otherwise player can't be seen.
`self.senses			= SENSE_SEE|SENSE_HEAR|SENSE_SMELL;		//Sense_Smell erforderlich, da der Sc sonst nicht "gesehen wird)!!	`

**Comment by Try** [comment]
> Reverting https://github.com/Try/OpenGothic/commit/8716db0b2e4ce5e5baa893ac1433b8b209c8d5ef

Hm, I remember this was done, to fix case when the seeker can notice player from behind

**Comment by thokkat** [comment]
I tested a bit more.  If npc has senses smell `ASSESSPLAYER` is triggered if within perc distance without any further conditions. So either senses see + visibility or senses smell. 

This would explain `ZS_GolemDown` start function:

```C
func void ZS_GolemDown ()
{
	self.senses			=	SENSE_SMELL ;
	self.senses_range	=	2000;	
	Npc_SetPercTime		(self, 1);	
	Npc_PercEnable  	(self, 	PERC_ASSESSPLAYER	, 	B_GolemRise	); 

	self.aivar[AIV_TAPOSITION] = NOTINPOS;
};
```

**Comment by hwnde** [comment]
> > Reverting [8716db0](https://github.com/Try/OpenGothic/commit/8716db0b2e4ce5e5baa893ac1433b8b209c8d5ef)
> 
> Hm, I remember this was done, to fix case when the seeker can notice player from behind

Notice as in attack or trigger dialogue?
I did some testing in OpenGothic and vanilla and there seems to be a difference in behavior when I approach a seeker from behind. In vanilla it triggers the dialogue. In OpenGothic the seeker starts attacking me.

**Comment by hwnde** [comment]
@Try would you agree, based on the above comments, to revert the change?

**Comment by Try** [comment]
Reverted, thanks everyone for testing it and thanks @hwnde for reminding - I've forgot about this ticket :)

**Comment by thokkat** [comment]
There are two kinds of seeker's. Some wanna talk, some attack. I pushed a pr for the Lares case but seekers should behave as expected too. https://github.com/Try/OpenGothic/pull/589

**Comment by Try** [comment]
> There are two kinds of seeker's.

It's not 2 completely different. Seeker behavior is controlled by `aivar[AIV_EnemyOverride] = TRUE` line, and there a few minor variations for the very first one and some on dragon-island.

> This fixes Lares not stopping if guiding the player and shattered golem not attacking

Lares work on current master as-is. I'm sorry, but I can't quite see what this PR is about

**Comment by Try** [comment]
> escorting NPCs like Lares

Fixed.

> found two snappers swimming in the lake just next to the cliff.

Snappers can be part of: https://github.com/Try/OpenGothic/issues/657

Perc related side-topic seem to be already tracked in:
https://github.com/Try/OpenGothic/issues/639
