### ISSUE TITLE
minor problem: cannot focus+loot clipped NPC corpse

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#566]
![image](https://github.com/Try/OpenGothic/assets/86957596/208a0c37-bdfc-44cc-8e27-ea4e27c588d9)
Cannot loot clipped corpse because I cannot focus on NPC corpse (bandit bridge near Akils).

Of course this is a minor problem, maybe no fix needed. I am reporting mainly so it can be found out if this is intended/by design.

**Comment by Try** [comment]
Hi @Abendlied and thank for report!

Do you have a save-file with depicted issue by any chance ? Thanks!

**Comment by Abendlied** [comment]
@Try Sorry, I have overwritten it already, it was on the quicksave and I did not think about storing this for debugging. I will do next time.

Out of curiosity I tried to clip through the textures as well using K and was able to "stand" within the texture of the bridge wall. From there I could focus the corpse and was able to take control using O to move the corpse out there.

**Comment by thokkat** [comment]
Maybe related as a meatbug or golem you can't focus hero to get back. I also remember focusing some of the meatbugs for the clean quest in oldworld's castle wasn't possible, but couldn't reproduce with some marvin spawned one's.

**Comment by Try** [comment]
> Maybe related as a meatbug

To loot npc, player need to be able to "see" it. `Npc::canSeeNpc` check head visibility, for humans; midPoint for others.

**Comment by Try** [comment]
While I wasn't able to reproduce the case, decide to add an extra check for physical center of npc. Should work as physical center can't be inside the wall/obstacle
