### ISSUE TITLE
Wielding holy hammer instead of Rods 2h

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#567]
At Onars, speaking with Mercenary Rod. I chose the dialog to brag about being able to wield his 2h sword.
![Screenshot_2024-01-11_00-07-36](https://github.com/Try/OpenGothic/assets/86957596/333b11a2-cb6b-4323-a01f-f527ce044146)

After Rod gave me his 2h sword, the hero equipped the holy hammer from the monastery instead of Rods 2h. Quest succeeded.
![Screenshot_2024-01-11_00-08-53](https://github.com/Try/OpenGothic/assets/86957596/30fd3d32-6051-4b9e-a991-6273449147e0)

I had the holy hammer already in my inventory. It was not the weapon I had initially equipped before.
Happened in chapter 1, guildless, 44 strength (strength >= 30 is the quest pass criterion).

**Comment by Abendlied** [comment]
I think I know why. I found this in decompiled g2 scripts, it literally is scripted so that the player equips the best melee weapon which in my case happened to be the holy hammer.


> 
> func void DIA_Rod_Wette_Yes()
> {
> 	AI_Output(other,self,"DIA_Rod_Wette_Yes_15_00");
> 	AI_Output(self,other,"DIA_Rod_Wette_Yes_06_01");
> 	if(B_GiveInvItems(other,self,ItMi_Gold,30))
> 	{
> 		Rod_WetteAngenommen = TRUE;
> 		AI_Output(other,self,"DIA_Rod_Wette_Yes_15_02");	
> 		AI_Output(self,other,"DIA_Rod_Wette_Yes_06_03");	
> 		B_GiveInvItems(self,other,ItMw_2h_Rod,1);
> 		if(other.attribute[ATR_STRENGTH] >= Condition_Rod)
> 		{
> 			AI_UnequipWeapons(other);
> 			**AI_EquipBestMeleeWeapon(other);**
> 			AI_ReadyMeleeWeapon(other);
> 			AI_Output(other,self,"DIA_Rod_Wette_Yes_15_04");
> 			AI_Output(self,other,"DIA_Rod_Wette_Yes_06_05");
> 			AI_Output(self,other,"DIA_Rod_Wette_Yes_06_06");	
> 			AI_Output(self,other,"DIA_Rod_Wette_Yes_06_07");	
> 			B_GiveInvItems(self,other,ItMi_Gold,60);
> 			Rod_WetteGewonnen = TRUE;
> 			B_GivePlayerXP(XP_Rod);
> 		}
> 		else
> 		{
> 			AI_Output(other,self,"DIA_Rod_Wette_Yes_15_08");	
> 			AI_Output(self,other,"DIA_Rod_Wette_Yes_06_09");	
> 		};
> 		AI_Output(self,other,"DIA_Rod_Wette_Yes_06_10");
> 		Info_ClearChoices(DIA_Rod_Wette);
> 		Info_AddChoice(DIA_Rod_Wette,"Äóìàþ, ÷òî íåò...",DIA_Rod_Wette_KeepIt);
> 		Info_AddChoice(DIA_Rod_Wette,"Âîò äåðæè.",DIA_Rod_Wette_GiveBack);
> 	}
> 	else
> 	{
> 		AI_Output(other,self,"DIA_Rod_Wette_Yes_15_11");
> 		AI_Output(self,other,"DIA_Rod_Wette_Yes_06_12");
> 		Info_ClearChoices(DIA_Rod_Wette);
> 	};
> };

**Comment by Try** [comment]
Hi, @Abendlied and thanks for investigating!

Yes, this is indeed script misuse of  `AI_EquipBestMeleeWeapon`.
