### ISSUE TITLE
Random Segmentation fault on Game save [linux]

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#57]
If the game is saved, theres a ~25 % chance to get a segmentation fault.

File: MoltenTempest/Engine/gapi/vulkan/vframebufferlayout.cpp
On current master line 38
```cpp
bool VFramebufferLayout::isCompatible(const VFramebufferLayout &other) const {
  if(this==&other)
    return true;
  if(attCount!=other.attCount) //SIGSEGV on game save
    return false;
  for(size_t i=0;i<attCount;++i)
    if(frm[i]!=other.frm[i])
      return false;
  return true;
  }
```

It can be reproduced with starting a game and saving it ~3-4 times.

**Comment by Try** [comment]
Thanks - I think, real issue with saves now found!
The issue was:
WorldView caches framebuffer layout
save-game uses a temporary Fbo, for screenshoot

Layout of already destroyed Fbo was cached.

**Comment by ErrorFlexXx** [comment]
Retested with latest master. No segmentations faults so far.
Thank you!
