### ISSUE TITLE
Too small interface on FullHD

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#590]
Too small text size on FullHD resolution. It's hard to read. Is there any way scale interface or increase font size ?
![2024-03-10_00-32](https://github.com/Try/OpenGothic/assets/84655481/b15b8daa-2654-49f3-95eb-8a65ce8ee13e)

**Comment by Try** [comment]
Hi, @YALdysse !

There is a interface scaling option in `SystemPack.ini` : 
```
[INTERFACE]
Scale = 1.5
```

**Comment by YALdysse** [comment]
@Try, Do you plan to make it possible to change the interface scaling and edit other parameters in the menu? I mean, so that the user does not have to change the settings through a file, but can do it conveniently using the settings menu or the configurator. It would be very convenient.
For example, to make it possible to change the scaling of the interface in the video settings.

**Comment by YALdysse** [comment]
> Hi, @YALdysse !
> 
> There is a interface scaling option in `SystemPack.ini` :
> 
> ```
> [INTERFACE]
> Scale = 1.5
> ```

Could you write in README.md about that.

**Comment by YALdysse** [comment]
I created the SystemPack.ini file in the same directory as Gothic2Notr.sh. I launched the game and nothing changed. Please tell me what I did wrong.
My `SystemPack.ini`
```
[INTERFACE]
Scale = 2.5
```

**Comment by YALdysse** [comment]
> > Do you plan to make it possible to change the interface scaling and edit other parameters in the menu?
> 
> This is out of scope of what engine does. When it comes to UI, OpenGothic simply runs script, from the game-files, that tell engine what buttons/sliders to draw. Only relevant change in plan would be to support native dpi factor. In that case, when `Scale` is not set in config, engine can ask OS for preferred UI scale.
> 
> > Could you write in README.md about that ?
> 
> Maybe wiki is better option here

It seems to me, it's hard to edit config file manually for users. I believe, you'll get a lot of issues like "how to change the scale of the interface" if it can only be changed by editing the configuration file. 
I am sure it will be convenient if there is a configurator like in OpenMW.

**Comment by Try** [comment]
> I created the SystemPack.ini file in the same directory as Gothic2Notr.sh

Need to be in `/system` diectory of original game. This is because this is compatibility feature with system-pack.

**Comment by YALdysse** [comment]
> > I created the SystemPack.ini file in the same directory as Gothic2Notr.sh
> 
> Need to be in `/system` diectory of original game. This is because this is compatibility feature with system-pack.

Nothing happens.

**Comment by Try** [comment]
Can you please show me `log.txt` and file-manager screenshot?

**Comment by YALdysse** [comment]
> Can you please show me `log.txt` and file-manager screenshot?

Of course.

[log.txt](https://github.com/Try/OpenGothic/files/14564810/log.txt)
[tree.txt](https://github.com/Try/OpenGothic/files/14564839/tree.txt)

**Comment by YALdysse** [comment]
>! OpenGothic v
no *.ini file in path - using default settings
GPU = AMD Radeon Graphics (RADV RENOIR)
Depth format = Depth32F Shadow format = Depth16
[phoenix] World: Parsing object [MeshAndBsp % 0 0]
[phoenix] BspTree: Parsing chunk c000
[phoenix] BspTree: Parsing chunk c010
[phoenix] BspTree: Parsing chunk c040
[phoenix] BspTree: Parsing chunk c045
[phoenix] BspTree: Parsing chunk c050
[phoenix] BspTree: Parsing chunk c0ff
[phoenix] Mesh: 1 bytes remaining in section b020
[phoenix] World: Parsing object [VobTree % 0 0]
[phoenix] World: Parsing object [WayNet % 0 0]
[phoenix] World: Parsing object [EndMarker % 0 0]
invalid particle system: "INVISIBLE_VOBBOX.3DS"
unable to load sound fx: ENV_NIGHT_TONSOFINSECTS
unable to load sound fx: OW_BIRD11
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript: Unexpected value for MdsEventType: "		"
[phoenix] ModelScript.Binary: 4 bytes remaining in section f5a3
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590
[phoenix] ModelScript.Binary: 1 bytes overflowed in section f590


fsdfsdf

**Comment by Try** [comment]
@YALdysse 

I think, that I've found the issue:
```
[INTERFACE]
Scale = 2.5
```

OpenGothic doesn't quite respect white spaces, so only `Scale=2.5` would to be valid. Fixed with f3cefe1a commit - now white-space is allowed

**Comment by YALdysse** [comment]
@Try, it works. You're amazing. Big thanks.

**Comment by Try** [comment]
Hi @Lalusch !

Last time I've player on Mac scale been working fine. What build of the game are you using?

**Comment by Lalusch** [comment]
Using the raw Steam Version of Night of the Raven I think its Version 2.6

**Comment by Try** [comment]
> Using the raw Steam Version of Night of the Raven I think its Version 2.6

I mean, version/build of OpenGothic? If you playing something else, vanilla for example - naturally it wont be related to this project

**Comment by creffect** [comment]
> On M1 does not work with the Scale what am I doing wrong? Would love to play Gothic but the Interface is just to small.
Hi @Lalusch , i tried it on my M2 with https://www.macsourceports.com/game/gothic2 this version (0.75), but it didn't work (placed 

``ìni
[DEBUG]
Show_FPS_Counter=1

[INTERFACE]
Scale=4
```

in system/SystemPack.ini, and the fps counter was shown, but the ui not scaled.

So i tried to build OpenGothic from source 

```bash
brew install cmake
brew install glslang
 git clone --recurse-submodules https://github.com/Try/OpenGothic.git
 cd OpenGothic
 cmake -H. -Bbuild -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
cmake --build ./build --target Gothic2Notr
build/opengothic/Gothic2Notr.sh
```

and not wit works :)
