### ISSUE TITLE
NPC label bug

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#591]
The mark of a dead NPC is visible even after a loot. So, when there are a lot of corpses nearby, it will be difficult to loot the right one. Could you implement hiding the character's label after all items are taken from his inventory ?
![2024-03-12_23-49](https://github.com/Try/OpenGothic/assets/84655481/513b91f6-c6d8-425e-986b-a552012d7014)

There is also a bug where the text overlaps with the health bar of NPC (see screenshot). I use 1.3 point scaling. Thanks.

**Comment by Try** [comment]
> Could you implement hiding the character's label after all items are taken from his inventory ?

There is similar feature in system pack, that already implemented:
```
[PARAMETERS]
HideFocus=1
```

**Comment by YALdysse** [comment]
> > Could you implement hiding the character's label after all items are taken from his inventory ?
> 
> There is similar feature in system pack, that already implemented:
> 
> ```
> [PARAMETERS]
> HideFocus=1
> ```

It works. Thank you. Could you write about that feature in wiki or Readme.md, please, because it is useful feature  ?

**Comment by Try** [comment]
Moved wiki-related work to https://github.com/Try/OpenGothic/issues/594 (as I don't really have time/enthusiasm to do documentation work :) )
And rest is complete - closing
