### ISSUE TITLE
Installing dependencies (and then make) fails on Linux Mint

### ISSUE THREAD

**Issue by Xenoshell** [Try/OpenGothic#596]
Installing dependencies:

an error when using sudo apt update:
```
W: GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6224F9941A8AA6D1
E: The repository 'http://repository.spotify.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://packages.lunarg.com/vulkan/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
and when trying to install vulkan-sdk:

```
The following packages have unmet dependencies:
 lunarg-via : Depends: libjsoncpp1 (>= 1.7.4) but it is not installable
 vulkan-profiles : Depends: libjsoncpp1 (>= 1.7.4) but it is not installable
 vulkancapsviewer : Depends: qt5-default but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This is the make error:
```
In file included from /home/../Documents/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vaccelerationstructure.h:5,
                 from /home/../Documents/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vaccelerationstructure.cpp:3:
/home/../Documents/OpenGothic/lib/Tempest/Engine/gapi/vulkan/vulkan_sdk.h:4:10: fatal error: vulkan/vulkan.h: No such file or directory
    4 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib/Tempest/Engine/CMakeFiles/Tempest.dir/build.make:858: lib/Tempest/Engine/CMakeFiles/Tempest.dir/gapi/vulkan/vaccelerationstructure.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/../Documents/OpenGothic/build'
make[1]: *** [CMakeFiles/Makefile2:711: lib/Tempest/Engine/CMakeFiles/Tempest.dir/all] Error 2
make[1]: Leaving directory '/home/../Documents/OpenGothic/build'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/../Documents/OpenGothic/build'
```
This is my system (i deleted some stuff to make it more readable):

```
System:
  Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: TOSHIBA product: SATELLITE L50-C v: PSKW2E-036008GR
    serial: <superuser required>
  Mobo: FF50 model: 06F3 v: Type2 - Board Version serial: <superuser required> UEFI: INSYDE
    v: 1.70 date: 07/05/2017
CPU:
  Info: dual core model: Intel Core i5-6200U bits: 64 type: MT MCP smt: enabled arch: Skylake
    rev: 3 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 2278 high: 2354 min/max: 400/2800 cores: 1: 2291 2: 2354 3: 2180 4: 2289
    bogomips: 19200
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Toshiba driver: i915 v: kernel ports:
    active: eDP-1 empty: HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:1916 class-ID: 0300
  Device-2: NVIDIA GM108M [GeForce 930M] vendor: Toshiba driver: nvidia v: 535.129.03 pcie:
    speed: 2.5 GT/s lanes: 4 bus-ID: 01:00.0 chip-ID: 10de:1346 class-ID: 0302
  Device-3: IMC Networks TOSHIBA Web Camera - HD type: USB driver: uvcvideo bus-ID: 1-7:15
    chip-ID: 13d3:5652 class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 98 s-size: 499x280mm (19.6x11.0") s-diag: 572mm (22.5")
  Monitor-1: eDP-1 model: LG res: 1920x1080 hz: 60 dpi: 141 size: 345x194mm (13.6x7.6")
    diag: 396mm (15.6") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
```
Anything i could do? Every suggestion is appreciated. I read in the README that you can download a build [here](https://ci.appveyor.com/project/Try/opengothic/history) but tbh i dont know how.

**Comment by Try** [comment]
> Anything i could do? Every suggestion is appreciated. 

Hi @Xenoshell , I'm not a linux user, but it seem like an issue on a side of your package-manager.
What happen:
* `apt update` didn't work - idk, something off with our system
* as consequence, you wasn't able to install vulkan-sdk, that is needed for the engine
* game doesn't build because vulkan headers, which are part of vulkan-sdk were not found/installed.

**Comment by Xenoshell** [comment]
Hello @Try , Ok i will try to focus on the update error and maybe i can find something. If i do, i will report back. I'm not a linux know it all so if someone else has more knowledge on what to do i would appreciate it :)

**Comment by Nindaleth** [comment]
@Xenoshell I can see these issues:
* `E: The repository 'http://repository.spotify.com stable InRelease' is not signed.` - this error is not related to OPG build process
* `W: https://packages.lunarg.com/vulkan/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.` - this is related, but it's only a warning and since you can install the lunarg package, can be ignored
* `libjsoncpp1 ... qt5-default ... not installable` - these packages are not available in your distro, you can try to get them via other means or build them yourself... however, I can see one more clue in your inxi output (nice! that actually helped)
* `Distro: Linux Mint 21.3 Virginia ... base: Ubuntu 22.04 jammy` - the README step tells you to import a **Focal** repo list (which is Ubuntu 20.04), but your Mint distro version is based on **Jammy** (Ubuntu 22.04)

To fix this, I suggest removing `/etc/apt/sources.list.d/lunarg-vulkan-focal.list` and doing this:
`sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list`
and the `sudo apt update` and the `sudo apt install vulkan-sdk` again; there's a higher probability it will contain (and require) the packages that your distro knows.

**Comment by Xenoshell** [comment]
Thank you @Nindaleth your comment helped a lot. I was able to install vulkan-sdk and then OpenGothic. I would consider this closed but now, for some reason, i have a problem with executing the .sh script.
My error is simple:
`./Gothic2Notr.sh: line 8: /home/../Documents/OpenGothic/scripts/Gothic2Notr: No such file or directory
`
I changed the line 8 to  `exec "$DIR/Gothic2Notr" "$@" -g "~/.steam/debian-installation/steamapps/common/Gothic II` and obviously the directory is existing. What could i do to fix this problem?

**Comment by Nindaleth** [comment]
I don't know, can you share the command line you use to run OpenGothic and what's the path you run it from?

**Comment by Xenoshell** [comment]
`./Gothic2Notr.sh` i also tried this command with sudo but it didnt change anything. 

Open gothic is in ~/Documents/OpenGothic

**Comment by Nindaleth** [comment]
Are you trying to run it from `~/Documents/OpenGothic/scripts/`? The error implies that Gothic2Notr (the binary) is supposed to be present next to Gothic2Notr.sh (the Bash wrapper), which doesn't hold for the scripts.

Here's how I run it, OpenGothic is in `~/src/OpenGothic`:

```
cd ~/src/OpenGothic
./build/opengothic/Gothic2Notr.sh -g ~/Games/gothic-ii-gold-edition/drive_c/GOG\ Games/Gothic\ 2\ Gold/
```

Does that work for you? In that path the binary and the bash wrapper are guaranteed to be both present as long as the build passes.

**Comment by Xenoshell** [comment]
@Nindaleth Thank you very much that solved my problem. I just thought that the Gothic2Notr.sh i have to execute is in the scripts directory and didn't think that there is another one somewhere floating around. Nowhere did it state differently. 

I was able to start OpenGothic and play it too. Looks pretty amazing. Is there a way to use my old save files?

**Comment by Nindaleth** [comment]
Happy to help.

In the README the compilation section does state that "Executables can be located at `OpenGothic/build/opengothic`."

> If i have some old save files, where can i put them so OpenGothic can load them?

OpenGothic at the moment [does not support](https://github.com/Try/OpenGothic/issues/410) loading the original saves.

**Comment by Xenoshell** [comment]
Ah ok, thats sad but thanks anyway. Now that you mentioned it, i saw that line with `executables can be located at OpenGothic...` but i after bulding it i only looked at the How To Play section and not at the Build section anymore. 
Thanks again for all the help with my various problems, now i think i have to go do all the quests again to be a novice ^^
