### ISSUE TITLE
Game crashes 

### ISSUE THREAD

**Issue by r4shpro** [Try/OpenGothic#607]
Hey @Try,

I have come across a permanent crashing when trying to end dialog with Malet (Lobart's farm) on the last build. 

Thanks a lot for the great work and support.

PS. The build runs on Macbook Pro m1 16 Gb, Sonoma

[crash.log](https://github.com/Try/OpenGothic/files/15068871/crash.log)
[save_slot_1.sav.zip](https://github.com/Try/OpenGothic/files/15068876/save_slot_1.sav.zip)

**Update:**

the fix resolved the issue

**Comment by Try** [comment]
Hi, @r4shpro and thanks for report!

Game crashes from `std::__1::__function::__func<zenkit::DaedalusVm::register_default_external`. 
Should be fixed by: ZenKit commit [713480bf401e3e455805780d822ddac924ed1fba](https://github.com/GothicKit/ZenKit/commit/713480bf401e3e455805780d822ddac924ed1fba)
