### ISSUE TITLE
Torch disappear bug

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#608]
There is a torch bug in version `1.0.2668` (commit `39d2dbfc`). If you use torch from inventory and press action button to hide it, the torch will disappear from inventory. So if you have three torches, you can use them three times. After that, they will not be left in the inventory, as each torch disappears from the inventory after it is used.
Please, fix this bug. Thanks.

**Comment by Try** [comment]
Hi, @YALdysse !

What you describing is basically regular consumable mechanic. Otherwise player can use only a single torch for entire game

**Comment by YALdysse** [comment]
> Hi, @YALdysse !
> 
> What you describing is basically regular consumable mechanic. Otherwise player can use only a single torch for entire game

Sorry, I didn't think of that.
Thank you for your reply.
