### ISSUE TITLE
Clear key binding not working

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#609]
Backspace and delete not clear key bind slot in settings.
![gothic2_keybinding_clear](https://github.com/Try/OpenGothic/assets/84655481/1e7805ee-b5b5-461f-8521-ad3affe7ef80)

**Comment by Try** [comment]
Hi, @YALdysse and thanks for report!

Issue should be fixed now - 'Del' key is allowed. Regards Backspace - tested vanilla, apparently Backspace doesn't resets key-bindings

**Comment by YALdysse** [comment]
@Try , Thank you very much.
