### ISSUE TITLE
Vanilla graphics ?

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#610]
I'd like to play OpenGothic  with vanilla graphics, that is, without new lighting and shadows. Is there a switch responsible for this? How can I get the old graphics back?
![newBr](https://github.com/Try/OpenGothic/assets/84655481/3accb01a-7369-47f2-9820-37bbcd359f29)

I don't like the new graphics because of the dark lighting and poor performance on my laptop. While I can ignore the slow performance, I can't ignore the too dark environment. Please could you add an option to play with vanilla graphics. That is, to be able to choose between modern and classic options, for example, using the menu or some other way. Please, I really need it.

**Comment by Try** [comment]
Hi, @YALdysse !

> , I can't ignore the too dark environment

This is actually regression, introduced today, fixed at 63b78e8b

> That is, to be able to choose between modern and classic options, for example, using the menu or some other way. Please, I really need it.

Unfortunately no. Maintaining 2 completely different rendering backends simultaneously, is not realistic.
Btw, what GPU is it? 40 FPS is quite a potato :)

**Comment by YALdysse** [comment]
> Btw, what GPU is it? 40 FPS is quite a potato :)

AMD Radeon RX Vega 7 (CPU - AMD Ryzen 5 5500U)

> This is actually regression, introduced today, fixed at https://github.com/Try/OpenGothic/commit/63b78e8bcf650c8a691b814bdbf1ce0349263da2

I will try new version.

**Comment by YALdysse** [comment]
@Try , new version better.
![newBr_fix](https://github.com/Try/OpenGothic/assets/84655481/68e7cb33-da17-41ca-80fa-e5a9b71e6d8c)

**Comment by YALdysse** [comment]
@Try , Can you improve the lighting even further ?

**Comment by Try** [comment]
> @Try , Can you improve the lighting even further ?

What is definition of improval here? Currently I'm working on secondary bounces and iradiance cache, for RT, yet this is probably not what you asking, right?)
If you need brightness - there is a menu option for gamma/brightness, hopefully this can help.
