### ISSUE TITLE
Spell animation transitions, from walk state

### ISSUE THREAD

**Issue by Try** [Try/OpenGothic#621]
When casting, for example 'fire rain' animation sequence runs as follows:
```
"S_MAGRUN"            // idle animation
"T_MAGRUN_2_FEASHOOT" // step1
"S_FEASHOOT"          // one-frame
"T_FEASHOOT_2_STAND"  // back from casting to stand
```

In case of walk-state, there is no transition `"T_MAGWALK_2_FEASHOOT"`, causing immediate skip toward `"S_FEASHOOT"`

**Comment by Try** [comment]
Need to checkup with vanilla, unfortunately it [again] suddenly stop working on my machine.

**Comment by thokkat** [comment]
Vanilla doesn't allow spell drawing in walk mode. Drawing in run mode and switching to walk mode before casting shows it's just using same transition as in run mode.

![Screenshot_20240512_172641](https://github.com/Try/OpenGothic/assets/100468436/b36e31fc-814b-4e58-a096-aaf31ee667b6)

**Comment by Try** [comment]
> Vanilla doesn't allow spell drawing in walk mode. 

I've manage to test it now; drawing spell in walk mode works (as well as anything else). I'm assuming you misspoke, and mean to say, that no `T_MAGWALK_2_*` exists in animation system; only `T_MAGRUN_2_*` for anycase

**Comment by thokkat** [comment]
I used caps lock to lock walk mode. Keys 1,2 and 3 still work but  >=4 for spells do not, hence the misassumption it wouldn't be possible.
