### ISSUE TITLE
Monsters lay on the floor after falling off a cliff

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#627]
**Game:**
Gothic II NotR

**Short Description/Observation:**
Monsters lay on the floor after falling off a cliff, taking damage from the fall. They only stand up after being attacked.
Laying down prevents monsters from attacking approaching player.

**Expectation:**
 Monsters should stand up or stay up after the fall and be aggressive towards approaching player.

**Steps to reproduce:**
Can be observed on cliffs with monsters above, e.g.
- Khorinis north coast (between Jack's Lighthouse and Vino's wine cave).
- Jharkendar southwest area near hermit's house

**Additional Info:**
![image](https://github.com/Try/OpenGothic/assets/86957596/01c9c4d5-058b-4224-9437-20c1de12a86b)

**Comment by Abendlied** [comment]
savegame: 
[save_slot_20.sav.tar.gz](https://github.com/Try/OpenGothic/files/15392220/save_slot_20.sav.tar.gz)

video (4 sec, 1.4MiB):
 Uploading 2024-05-21 17-40-49.mp4…

**Comment by Try** [comment]
Hi, @Abendlied !

After investigating a testing vanilla a bit, can say it's probably doesn't have "standup" mechanic in place, but instead npc switches to some routine.
In case of combat: snapper fall -> resets ai-state -> sees player immediately -> starts attacking. And start of stack is what triggers npc to stanup.
In case of 'random' fall: snapper(or other monster) returns back to `ZS_MM_Rtn_Rest` and returns to spawn point.

Also vanilla carefully assign C_Npc::wp for any npc, except the hero.

So I fix wp assignment and restarting AI-routine. Rest seem to work fine already.  However note, that changes will be effective, when npc will fall next time, and won't affect npc's in saved games.
