### ISSUE TITLE
[Linux] Missing Keyboard functions

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#63]
While digging for the reason, why my space key doesn't work in the game, I discovered the following:

- Setting keys in the menu doesn't work, but I saw several things in the code, that looked very complete. Is this a linux issue ?

- Player controls do work for me on linux if caps lock isn't activated. I placed a debug output in system/api/x11api in function `X11Api::implProcessEvents` in the cases
```cpp
case KeyPress:
case KeyRelease:
```
```cpp
[...]
auto key = SystemApi::translateKey(*ksym);
uint32_t scan = xev.xkey.keycode;
std::cout << "X11 api KeyCode: " << scan << " key: " << key << std::endl;
[...]
```
and get the following output:
```
for 'a' without caps lock: X11 api KeyCode: 38 key: 44 ksym: 97
for 'a' with caps lock: `X11 api KeyCode: 38 key: 0 ksym: 65`
for spacebar with or without caps lock: X11 api KeyCode: 65 key: 0 ksym: 32
```

I'm not entirely sure how `SystemApi::translateKey` is meant to work and don't want to break stuff for other operating systems.
Therefore I wanted to ask: Is there something missing here and is it fully working on windows ?

**Comment by Try** [comment]
Implementation of keyboard input was incomplete on linux - fixed
Add missing key-codes for X11 backend

> Setting keys in the menu doesn't work

Not a linux related issue - settings are mostly in view-only mode for now

**Comment by ErrorFlexXx** [comment]
Thank you for the support :+1:
