### ISSUE TITLE
[Gothic 1] Crash on loading screen entering sleeper temple

### ISSUE THREAD

**Issue by Abendlied** [Try/OpenGothic#632]
**Game:**
Gothic I

**Describe the bug**
Cannot enter sleeper temple, game crashes during loading screen. 
I am using latest master branch.
I know it worked at one point, so I was reverting to an older version 1.0.2324-1 (AUR package by CRreimer) and in this older version, world transition works.
Game relevant preconditions fulfilled: Ulu-Mulu and statuette in inventory, lever used and gate to sleeper temple opened.

**Save-game/Log-file/Screenshots/Video**
savegame: [save_slot_4.sav.tar.gz](https://github.com/Try/OpenGothic/files/15389426/save_slot_4.sav.tar.gz)

**Application log**
crash.log: [crash.log](https://github.com/Try/OpenGothic/files/15389414/crash.log)

**Comment by Try** [comment]
Should be fixed now
