### ISSUE TITLE
[Question] How to handle Issues

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#67]
Hello,

I got a question about how to use the issues tracker inside this project.
Currently I have a local text file, where I collect bugs (11), unimplemented things (10), unclassified things (2) and nice to have things (2).
I didn't want to annoy anyone with tons of issues without having been told to do so.
Therefore here my question about how to handle issues:

**Way 1:** Creating an issue, if I start working on it.
\- This way, there isn't an opportunity to discuss the topic beforehand,
to talk about possible reasons and solutions.
\- Prior prioritization of bugs and next features would'nt be possible to do, too.
\- Other devs. would'nt see the issues / upcoming tasks and can't pick a task,
which they may like to work on.
\+ The clarity of the issue tracker would be better, because there would'nt be that much issues listed.

**Way 2:** Create issues for every bug / unimplemented feature immediately after finding out.
All arguments from above, only the other way around.

What do you think, @Try ?
You're the owner of the project here so I guess it's up to you to take a decision :)

**Comment by Try** [comment]
Hi, @ErrorFlexXx !

I think, we need some middle ground solution between 'Way1' and 'Way2':

* Unimplemented features. There are lots of them at this moment - not much reason to create a flood of issues. Simple checklist is going to be enough. Right now I'm fine with checklist in Readme, but if needed I can move it to wiki and add more details.

* Unimplemented API. In general - there is a [wiki page](https://github.com/Try/OpenGothic/wiki/Daedalus-scripts) for it.

* Bugs in already implemented stuff - ticket

* Bug in partially implemented feature(for example: particles, magic) - ticket, only if it crashes, or make game unplayable somehow.

* Renderer - ticket, only if it crashes/report bad stuff in log. I'm looking forward to rewrite renderer anyway.

* > unclassified things (2) and nice to have things (2).
Hard to have a guideline for 'unclassified things' - if think it requires, then create one.

That is my view on how-to go about tickets. Critic is welcome :)

**Comment by ErrorFlexXx** [comment]
Sounds reasonable to me. :+1: 
Regarding the renderer rewrite: So implementing Light Vobs to get indoor lighting from Torches and so on isn't worth it at the moment ? Or a weather implementation ?
