### ISSUE TITLE
Can't compile under macos.

### ISSUE THREAD

**Issue by yuriytaranov** [Try/OpenGothic#670]
In file included from /Users/appveyor/projects/opengothic/game/graphics/lightgroup.cpp:1:
/Users/appveyor/projects/opengothic/game/graphics/lightgroup.h:60:18: error: private field 'staticMask' is not used [-Werror,-Wunused-private-field]
    const size_t staticMask = (size_t(1) << (sizeof(size_t)*8-1));
                 ^
1 error generated.
make[3]: *** [CMakeFiles/Gothic2Notr.dir/game/graphics/lightgroup.cpp.o] Error 1
make[2]: *** [CMakeFiles/Gothic2Notr.dir/all] Error 2
make[1]: *** [CMakeFiles/Gothic2Notr.dir/rule] Error 2
make: *** [Gothic2Notr] Error 2
Command exited with code 2

https://ci.appveyor.com/project/Try/opengothic/builds/50427213/job/ldfme8ut6y7ta4vk

**Comment by Try** [comment]
fixed in [7b29f149](https://github.com/Try/OpenGothic/commit/7b29f1499239248580c4fcb5c1353216f40e3bd1)
