### ISSUE TITLE
Game version in main menu

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#675]
Could you please add display version number in the main menu for builds from AppVeyor ?

**Comment by Try** [comment]
Hi, @YALdysse !

Version should be there. for example build `2852` :
![изображение](https://github.com/user-attachments/assets/9e6146d9-f686-4df9-92b8-d4e747abb126)

**Comment by YALdysse** [comment]
I can't see it. Build from AppVeyor.

![opengothic_v_mainmenu](https://github.com/user-attachments/assets/6e3864b9-d59a-49b6-8b5c-8d80262a5225)

**Comment by Try** [comment]
Hm, interesting. Do you have any mods installed? It appears, as if, digits do not render with that font

**Comment by YALdysse** [comment]
> Hm, interesting. Do you have any mods installed? It appears, as if, digits do not render with that font

No. I am using only russian version GOG assets.

**Comment by Try** [comment]
I've tested Russian version today, but from Steam, not from GoG:
![изображение](https://github.com/user-attachments/assets/a1a46c18-d45a-4f00-a750-2722d6039fec)

**Comment by YALdysse** [comment]
@Try, could you try please use build from [AppVeyor](https://ci.appveyor.com/project/Try/opengothic/history?branch=master) with Steam assets of Gothic 2 ?

**Comment by YALdysse** [comment]
This is not a problem with GOG's resources, because when I compiled the project myself, the current version of OpenGothic was displayed in the main menu. Although I was using GOG resources.

**Comment by Try** [comment]
> @Try, could you try please use build from [AppVeyor](https://ci.appveyor.com/project/Try/opengothic/history?branch=master) with Steam assets of Gothic 2 ?

The build I've tested is that one:
https://ci.appveyor.com/project/Try/opengothic/builds/50470057/job/lxhfbglayvvcgta0/artifacts

**Comment by YALdysse** [comment]
> The build I've tested is that one:
> https://ci.appveyor.com/project/Try/opengothic/builds/50470057/job/lxhfbglayvvcgta0/artifacts


I just downloaded the Linux build of this commit and checked the version in the menu. It is not displayed.
It seems to me that the problem is in the Linux builds from AppVeyor.

**Comment by Try** [comment]
@YALdysse 

According to VERSION file in opengothic_linux.zip version been written correctly. Can you confirm that on Linux main menu also can show correct build number?

**Comment by YALdysse** [comment]
![OpenGothic_version_in_main_menu](https://github.com/user-attachments/assets/23dd7d8f-f8ba-447b-be3c-5e1736f16b4f)

@Try.
It is amazing. It works. Thank you very much.
