### ISSUE TITLE
Swampsharks are not damaged with bow

### ISSUE THREAD

**Issue by YALdysse** [Try/OpenGothic#678]
**Describe the bug**
**OS:** `Linux Mint 21.3`
**OpenGothic:** `v1.0.2860`

Swampsharks in Yarkendar are not damaged when the hero shoots at them with a bow.
Help me with that, please.

**Save-game/Log-file/Screenshots/Video**
[save](https://drive.google.com/file/d/1ecfrOP_Ei7-VCyqOK78QEHbQjs7YrZx7/view?usp=sharing)
[video](https://drive.google.com/file/d/1v7BuK4OpgBUILXTsZg6lOk7esCuu6Zf5/view?usp=sharing)

**Application log**
[log.txt](https://github.com/user-attachments/files/16839891/log.txt)

**Comment by YALdysse** [comment]
Maybe this is due to the fact that my saves were made before commit 7fda9f9? I have now updated OpenGothic to the current version, but my saves were made on `v1.0.2769`.

**Comment by Try** [comment]
Hi, @YALdysse and thanks for report!

I've put a simple fix for now; and proper solution will require https://github.com/Try/OpenGothic/issues/605 to be implemented first

**Comment by YALdysse** [comment]
@Try, thanks for the commit.
Unfortunately, not working.
[video](https://drive.google.com/file/d/1b9aG7CNRmxqxrbhtdknBVfTyHafdFrWT/view?usp=sharing)

**Comment by Domarion** [comment]
Tried to play with this fix (not original Notr, but mod) and got no damage from bow, icelance.Tried to attack goblins, bandits, shadowbeast near pirates.

**Comment by Try** [comment]
Second attempt: 8832d7f8

Should be foxed now

**Comment by YALdysse** [comment]
> Second attempt: https://github.com/Try/OpenGothic/commit/8832d7f8015ab1cd323416dbbaacb7b580a3efd2

Yoohooo! It works! Thank you very much, @Try.

[video](https://drive.google.com/file/d/1b7jwPbbjDJ6FwbEL7pOTScG_Z_wytSfX/view?usp=sharing)

**Comment by Domarion** [comment]
> Tried to play with this fix (not original Notr, but mod) and got no damage from bow, icelance.Tried to attack goblins, bandits, shadowbeast near pirates.

Tested that case. It works like expected too.
