### ISSUE TITLE
Can't compile on Gentoo amd64

### ISSUE THREAD

**Issue by scodens** [Try/OpenGothic#687]
When i am trying to run: `cmake -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`
appears tons of errors
[log.txt](https://github.com/user-attachments/files/17103945/log.txt)

**Comment by Nindaleth** [comment]
Hey @scodens, what was wrong? I presume you initially missed the `--recurse-submodules` flag during the git clone?
