### ISSUE TITLE
After some time game freezes up on input

### ISSUE THREAD

**Issue by lizard123137** [Try/OpenGothic#699]
**Describe the bug**
When playing the game for around 30 minutes the game starts to freeze up when receiving user input. Restarting the game doesn't fix the issue. Each time it happens you have to reboot.

Pressing any of the movement keys causes the game to freeze up and pressing another key makes it unfreeze.

OS: `Fedora Linux 40 (Workstation Edition)`
GPU: `GPU: NVIDIA GeForce GTX 1660 SUPER`

**Application log**
[log.txt](https://github.com/user-attachments/files/17848250/log.txt)

**Comment by Try** [comment]
Hi, @lizard123137 !

Based on you description, specifically 
> Restarting the game doesn't fix the issue.

it seem to be issue, related to OS/driver setup, as application-related bugs cannot persists across different launches (except save files).

**Comment by lizard123137** [comment]
Hi, @Try!

In response to your suggestion I checked my `dmesg`, but there doesn't seem to be anything related.

Also this time i measured the time it took for the issue to start happening and it was about 50 minutes. In my previous comment I approximated it to be about 30 and I was wrong.

I have attached the logs before and after restarting the game. 
[log_before.txt](https://github.com/user-attachments/files/17852912/log_before.txt)
[log_after.txt](https://github.com/user-attachments/files/17852911/log_after.txt)

The `swapchain is outdated - reset renderer` log started appearing around the time the issue started happening. After restarting, it also appeared pretty much instantly and the issue persisted. Another thing i noticed is that the freezing seems to happen only when holding a key down, as soon as I release it or press another key It unfreezes.

If you need any additional information please let me know.

**Comment by Try** [comment]
> swapchain is outdated - reset renderer

This message is triggered by `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR`. Usually it happens on Linux, when you resizing the window, as rendering resolution becomes out of sync with actual window size. Maybe alt+tab can also be the case.
If driver spams this errors persistently, that explains lags, however it still seems as some kind of external problem.

**Comment by lizard123137** [comment]
Ok the alt + tab explains it.

I must have triggered those messages when checking dmesg, while the error was happening. 

In that case, as you said it's probably something external that is specific to my system. Should i close the issue?

I will do some research on the topic and follow up on it if i find anything.

**Comment by Try** [comment]
> Should i close the issue?

Feel free to reopen  or comment, if new some facts will come in.
