### ISSUE TITLE
[Bug] Jumping into the water freezes hero controls and movealgo.

### ISSUE THREAD

**Issue by ErrorFlexXx** [Try/OpenGothic#70]
If the hero jumps into the water, the jump animation somehow collides with the water and the hero gets uncontrollable (except rotating):
![HeroWaterFreezeS](https://user-images.githubusercontent.com/6613215/80696957-83fa2800-8ad8-11ea-8528-8c3a29d53c0c.png)

May be related to a misbehaviour, if walking backward into the water. In this case the hero moves in the water with his knees and if the water is deep enaugh, he is set for 1 Frame on top of the water and one frame after that he gets set correctly into the water.

**Comment by Try** [comment]
I've reproduced it once.
Symptoms:
- isInAir = false
- isSwim = true
- animation = S_JUMP
