### ISSUE TITLE
Change resolution

### ISSUE THREAD

**Issue by frootloop88** [Try/OpenGothic#700]
I can't change the resolution in game. The text is way too small to. Tried the .ini file but it's already set to 1024 which is not what is displayed. Using apple silicon

**Comment by Try** [comment]
Hi, @frootloop88 !

As been described here: https://github.com/Try/OpenGothic/issues/590 interface scale and resolution are independent. What are you looking for is a parameter in `SystemPack.ini`:
```
[INTERFACE]
Scale = 1.5
```
