### ISSUE TITLE
Running on Manjaro

### ISSUE THREAD

**Issue by Sebbestune** [Try/OpenGothic#78]
## Running on Manjaro

Recently I tried to get this to work on Manjaro Linux. I used pacman -Ss (search) to find most of the Linux dependencies listed in the "for Ubuntu" section. After some fixing (basically [this](https://cgit.freedesktop.org/mesa/mesa/commit/?id=c4d11ea3c43447da5add84bdd2e0c91786d9af9b) issue which I will more than happily commit to the code after I have a confirmed run), I get it to build with apparently no issues. When I want to test it I run and get:

`sudo ./opengothic/Gothic2Notr.sh -g "/run/media/sebastian/4212589A125894AF/Program Files (x86)/Steam/steamapps/common/Gothic II/"`
`
/home/sebastian/Dokument/OpenGothic/build/opengothic/Gothic2Notr: error while loading shared libraries: libMoltenTempest.so: cannot open shared object file: No such file or directory`

(Same error message comes if I run the file and not script.) To get this to work I first had to change the paths in Gothic2Notr.sh and remove /bin/ since the build does not result in such a structure. 

Do you have any insights of why I see this message and how I could get it to work? 

I think a nice addition to the docs would be how to run it in Linux as well. And maybe how to build on some other Linux flavors. But these are just some ideas.

**Comment by Try** [comment]
Hi, @Sebbestune!

> `libMoltenTempest.so: cannot open shared object file: No such file or directory` 

libMoltenTempest.so is a library, which represents a graphics engine, this file suppose to be located in 'bin' directory alongside with game executable.

To run the game, I suggest to use LD_LIBRARY_PATH:
```
cd bin
LD_LIBRARY_PATH=.
./Gothic2Notr -g <...>
```
Gothic2Noth.sh was suppose to deal with library-path, but seem to become outdated.

**Comment by Sebbestune** [comment]
Okay this helped!

I got it to work by creating a bin folder in the root of the openGothic folder structure, move the compiled files to there and revert the Gothic2Notr.sh to its initial state. I guess this made the PATH valid since:
`LINE 3: export LD_LIBRARY_PATH="$DIR/lib:$LD_LIBRARY_PATH"` now got valid.

I'll start to look a bit into if I can remedy the LD_LIBRARY_PATH. :)
