### ISSUE TITLE
Cannot attack when not moving

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#89]
Environment: Linux Fedora 32, X11, using Mesa 20.1.9 (AMD RADV), built from commit f96ce75.

It seems I have to be moving to be able to attack. In the original it's possible to attack (including bare hands) even when standing still.

**Comment by Try** [comment]
Attack, while standing works for me just fine.
Just asking: you pressing action+arrow button to attack, right?

**Comment by Nindaleth** [comment]
I found that in the official* TNOTR I can click to attack even without a movement button pressed.

* by official I mean GOG version of G2 Gold 2.7 + gothic2_fix-2.6.0.0-rev2 + PlayerKit 2.8 + SystemPack 1.8 patches running on my LInux via Lutris. But I think that this was the case on all versions, even the original Gothic 2 sometimes around 2005.

**Comment by Try** [comment]
> But I think that this was the case on all versions, even the original Gothic 2 that I first played some time around 2005.

Over years I had a DVD-disk and steam versions. No packs, no player-kits.
In each case attack was a direction_button+action_button.

I guess we can leave ticket open and continue investigation

**Comment by Nindaleth** [comment]
I tried the GOG version on a Windows 10 laptop and after the initial crash, it's still a user-unfriendly experience without the SystemPack, even the 1366x768 resolution is not supported by the game and switching to 1024x768 on the testing laptop breaks drawing completely.

However, you're right that the original behaviour does require click+movement to work. I'm sorry for misremembering previously. While the LMB-attack and RMB-block from the community patches feel very natural and in line with modern gaming expectations, I don't know how it would chain with the other movements and thus I'm not sure whether you'd want to support it. 

I noticed two differences in OpenGothic compared to the original, both with bare hands:
* original doesn't allow action+side movement with fists, nothing happens then, while OpenGothic allows to actually run to the picked side
* keeping the action button pressed and pressing backward movement once, original will block and retreat once, while OpenGothic will keep backing indefinitely as long as the action button is still held

I have one more related question - I suppose "1" and "2" should allow me to draw the respective melee and ranged weapons (and "3" for scrolls), but nothing happens, the only way for me to draw a weapon is pressing space for a melee weapon or fists, cannot pull out a bow. Not even switching my keyboard layout to US (so that instead of having to press shift+1 to "type" 1 I can just press button 1) helps, numpad also didn't help. Is this some kind of another Linux-specific issue or just not yet fully implemented in general?

**Comment by Try** [comment]
> Is this some kind of another Linux-specific issue or just not yet fully implemented in general?

Look like a unique issue: 
on Windows 1-2-3-...-9 just works;
and no such issue has ever been reported so far for Linux

**Comment by Nindaleth** [comment]
I've never had such an issue with other games, that's interesting. I'm using Czech keyboard layout. On that layout, if you press the key labeled `1`, you get `+`. To get `1`, you have to press shift+the key. If I print the code value in `KeyCodec::tr`, both `e.key` and `keyToCode(e.key)` are 0 for the number row of my layout.

I can confirm that after switching from Czech to US layout, I can draw weapons normally. This looks like either a misdetection somewhere, or possibly an effect of using virtual codes (\`) instead of scan codes (the key below escape key).

I don't mind the implementation details, though, my point is - this will affect anyone using keyboard layouts with this feature - other than US, Russian and more where pressing key `1` will output `1`. And that will likely include also users on Windows. I don't have a Windows machine on hand right now to confirm, but I strongly suspect so.

**Comment by Nindaleth** [comment]
I wanted to check whether this works on Windows (with Czech keyboard layout). However, the only Windows PC I have is a laptop with both iGPU and dGPU. Tha model is several years old and neither of those GPUs supports Vulkan or ever had updated drivers released that would support it.

For now, I agree the original problem is invalid/doesn't exist and this issue can be closed. If I get to a Windows system with Vulkan support later, I'll be sure to reproduce the 1-2-3- problem and I could log a proper issue then.
