### ISSUE TITLE
"conversion may change the value [-Werror=conversion" compilation errors on MCST lcc compiler

### ISSUE THREAD

**Issue by r-a-sattarov** [Try/OpenGothic#91]
I get such errors when compiling on **MCST lcc compiler**:

lcc: "/root/dev/r-a-sattarov/OpenGothic/Game/bink/video.cpp", line 803: error #2463:
          conversion may change the value [-Werror=conversion]
      return v64 & uint32_t(-1);

lcc: "/root/dev/r-a-sattarov/OpenGothic/lib/TinySoundFont/tsf.h", line 742: error #2463:
          conversion may change the value [-Werror=conversion]
        samplesLeft = *fontSampleCount = chunkSmpl->size / sizeof(short);

lcc: "/root/dev/r-a-sattarov/OpenGothic/lib/TinySoundFont/tsf.h", line 748: error #2463:
          conversion may change the value [-Werror=conversion]
                stream->read(stream->data, sampleBuffer, samplesToRead * sizeof(short));

lcc: "/root/dev/r-a-sattarov/OpenGothic/lib/TinySoundFont/tsf.h", line 1361: error #2463:
          conversion may change the value [-Werror=conversion]
        int channelSamples = (f->outputmode == TSF_MONO ? 1 : 2) * samples, floatBufferSize = channelSamples * sizeof(float);

lcc: "/root/dev/r-a-sattarov/OpenGothic/Game/bink/video.cpp", line 2055: error #2463:
          conversion may change the value [-Werror=conversion]
    float signConvention    = negativeSign ? -1 :  1;

lcc: "/root/dev/r-a-sattarov/OpenGothic/Game/bink/video.cpp", line 2056: error #2463:
          conversion may change the value [-Werror=conversion]
    float signConventionInv = negativeSign ?  1 : -1;

3 errors detected in the compilation of "/root/dev/r-a-sattarov/OpenGothic/Game/bink/video.cpp".
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:76: CMakeFiles/Gothic2Notr.dir/Game/bink/video.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 errors detected in the compilation of "/root/dev/r-a-sattarov/OpenGothic/Game/dmusic/hydra.cpp".
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:141: CMakeFiles/Gothic2Notr.dir/Game/dmusic/hydra.cpp.o] Error 1
lcc: "/root/dev/r-a-sattarov/OpenGothic/Game/world/item.h", line 20: error #997:
          function "Vob::save(Serialize &) const" is hidden by "Item::save" --
          virtual function override intended? [-Werror=overloaded-virtual]
      void save(Serialize& fout);

1 error detected in the compilation of "/root/dev/r-a-sattarov/OpenGothic/Game/camera.cpp".
make[2]: *** [CMakeFiles/Gothic2Notr.dir/build.make:89: CMakeFiles/Gothic2Notr.dir/Game/camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: CMakeFiles/Gothic2Notr.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:130: all] Error 2

full log:
[OpenGothic_lcc_compile_err.log](https://github.com/Try/OpenGothic/files/5410881/OpenGothic_lcc_compile_err.log)

**Comment by Try** [comment]
Hi, @r-a-sattarov and thanks for report!

> function "Vob::save(Serialize &) const" is hidden by "Item::save" 

This warning is a nice catch, so I fixed it and warning in video.cpp as well.
For `TinySoundFont/tsf.h`, I want to avoid changes for this file, since it's a third-party library header.
Looking at Wconversion warnings for this compiler, maybe it's better to just disable this warning for lcc. Say do you know, how to detect this compiler in cmake?

**PS**
Nice to see Kazan people here ;)

**Comment by r-a-sattarov** [comment]
> > function "Vob::save(Serialize &) const" is hidden by "Item::save"
> 
> This warning is a nice catch, so I fixed it and warning in video.cpp as well.

Yes, these bugs have been fixed 👍 

> For `TinySoundFont/tsf.h`, I want to avoid changes for this file, since it's a third-party library header.

I wrote to the author of this library about compilation errors.
> Say do you know, how to detect this compiler in cmake?

This can be a little tricky 😃, because this compiler is gcc compatible (current MCST lcc compiler version 1.25 is gcc 7.3.0 compatible) and when checked for `CMAKE_<LANG>_COMPILER_ID` it will answer `GNU`.
But can try to use self-written macros to define the compiler. For example, can use macro check_native_define from the Urho3D project (https://github.com/urho3d/Urho3D)
- https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/CheckCompilerToolchain.cmake#L71

And do something like this:
`check_native_define ("__LCC__" LCC)`
`if (LCC AND (CMAKE_SYSTEM_PROCESSOR MATCHES "e2k"))`
`do something with Wconversion warnings`
`endif()`

P.S. I try to compile the OpenGothic on the MCST **e2k** (Elbrus 2000) CPU architecture 😉

**Comment by Try** [comment]
>  I try to compile the OpenGothic on the MCST e2k (Elbrus 2000) CPU architecture

Well, if you just want to compile, than removal of Werror can be enough for you. In CMakeLists.txt:
```cmake
if(NOT MSVC)
  # remove next line
  target_compile_options(${PROJECT_NAME} PRIVATE -Wall -Wconversion -Wno-strict-aliasing -Werror)
endif()
```

**Comment by r-a-sattarov** [comment]
> > I try to compile the OpenGothic on the MCST e2k (Elbrus 2000) CPU architecture
> 
> Well, if you just want to compile, than removal of Werror can be enough for you. In CMakeLists.txt:

Is there a way in CMake to remove warning `-Wconversion` only for one specific folder (`lib/TinySoundFont`)? I would like to compile with all turned on warnings  to be able to help find bugs in your code.
I'm interested not only in compiling, but also in trying to run this game on the e2k architecture 😉

**Comment by Try** [comment]
I've disable warning with `pragma diagnostic`
Can you please check this fix on your side?

**Comment by r-a-sattarov** [comment]
> I've disable warning with `pragma diagnostic`
> Can you please check this fix on your side?

No, unfortunately it didn't help - same bug.
- [OpenGothic_e2k_compile_err.log](https://github.com/Try/OpenGothic/files/5435624/OpenGothic_e2k_compile_err.log)

**Comment by Try** [comment]
> No, unfortunately it didn't help - same bug.

It's not the same - it complains now about bullet :)
Since warning are so big problem for lcc, maybe you can try solution mentioned above in https://github.com/Try/OpenGothic/issues/91#issuecomment-713839479 :
>And do something like this:
>check_native_define ("__LCC__" LCC)
>if (LCC AND (CMAKE_SYSTEM_PROCESSOR MATCHES "e2k"))
>do something with Wconversion warnings
>endif()

**Comment by r-a-sattarov** [comment]
Temporarily removed `-Wconversion` option and found another bug:

lcc: "/root/dev/r-a-sattarov/OpenGothic/Game/dmusic/wave.cpp", line 85: error #1873:
          comparison of signed and unsigned operands [-Werror=sign-compare]
      `for(size_t i=0; i<2*nCoefs; i++) {`

**Comment by Try** [comment]
> for(size_t i=0; i<2*nCoefs; i++) {

Fixed, also: do not hesitate to make a pull-request, if it's something easy or one-line change.

**Comment by r-a-sattarov** [comment]
> Fixed, also: do not hesitate to make a pull-request, if it's something easy or one-line change.

Now (after removing `-Wconversion` option) the OpenGothic is compiled without critical errors. Therefore, I close this issue.

[OpenGothic-e2k_compile_err.log](https://github.com/Try/OpenGothic/files/5505435/OpenGothic-e2k_compile_err.log)
