### ISSUE TITLE
Miss-handling of DEF_EXCHANGE_ITEM 

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#93]
This may have a common root cause, maybe it's two separate issues:

1. Cooking raw meat on the frying pan will keep the "pan with cooked meat" item instead of returning an empty pan and a cooked meat
2. Equipping and unequipping a torch results in it disappearing from the inventory

**Comment by Try** [comment]
This is 2 different cases:
1. First one is miss-handling of DEF_EXCHANGE_ITEM animation tag - I have a very hard time reproducing this
2. Torch is a special case in gothic: it requires DEF_DRAWTORCH, DEF_INV_TORCH, DEF_DROP_TORCH to be implemented.

**Comment by Nindaleth** [comment]
I can create another issue so that these can be tracked separately if you'd like.

Is there a way we can help with the pan issue reproduction? I'm not sure I understand what kind of reproduction you mean.

**Comment by Try** [comment]
> I'm not sure I understand what kind of reproduction you mean.

I'm aware that pan problem is there, and some-times I can find a pan in other npc inventory.
But unfortunately this bug never happen to main-hero, on my machine - that's my problem.

**Comment by Try** [comment]
>I can create another issue so that these can be tracked separately if you'd like.

Rename this one is enough, I think.
(No ticket for torch-issue, since it's not a bug, but a feature)

**Comment by Try** [comment]
Update my investigation on a subject:
Here is animation tags for cooking:
```c++
ani	("t_Pan_Stand_2_S0"			1	"s_Pan_S0"		0.1	0.0	M.	"Hum_CookForMe_M01.asc"		F	0	24)
ani	("s_Pan_S0"					1	"s_Pan_S0"		0.0	0.0	M.	"Hum_CookForMe_M01.asc"		F	25	25)
aniAlias("t_Pan_S0_2_Stand"			1	""				0.0	0.2	M.	"t_Pan_Stand_2_S0"			R)

ani	("t_Pan_S0_2_S1"			1	"s_Pan_S1"		0.0	0.0	M.	"Hum_CookForMe_M01.asc"		F	26	34)
{
	*eventTag	(26	"DEF_INSERT_ITEM"	"ZS_RIGHTHAND")
}
ani	("s_Pan_S1"					1	"s_Pan_S1"		0.0	0.0	M.	"Hum_CookForMe_M01.asc"		F	35	84)
ani	("t_Pan_S1_2_S0"			1	"s_Pan_S0"		0.0	0.0	M.	"Hum_CookForMe_M01.asc"		R	26	34)
{
	*eventTag	(33	"DEF_EXCHANGE_ITEM"	"ZS_LEFTHAND"	"ItFoMutton") // bug
	*eventTag	(26	"DEF_REMOVE_ITEM")
}
```
Animation script inserts pan into right hand, and than replaces content of left hand for meat, so what is going on is not exactly OpenGothic bug after all.

Current idea to solve the problem: if slot in `DEF_EXCHANGE_ITEM` is invalid, than replace content of any non-empty slot.
