### ISSUE TITLE
Key interpretation

### ISSUE THREAD

**Issue by hama3254** [Try/OpenGothic#97]
I noticed that the game does use the left and right rotate keys not as the original.

You can not use the rotate keys `RotateL` and `RotateR` (from `keyLeft` and `keyRight`) to navigate in the inventor and they are also do not work for fighting.
Both works fine with the `Left` and `Right` (from `keyStrafeLeft` and `keyStrafeRight`) 

Should it be that way?

**Comment by Try** [comment]
Hi, @hama3254 !

> Should it be that way?

As far as I know vanilla gothic2 behaves exactly same way, isn't it?

**Comment by Kirides** [comment]
> As far as I know vanilla gothic2 behaves exactly same way, isn't it?

yes. it does.
By default in G2 the arrow keys map to up, down, rotate left, rotate right and do not allow you to move cells left/right if pressing left or right arrow key.

**Comment by hama3254** [comment]
> > As far as I know vanilla gothic2 behaves exactly same way, isn't it?
> 
> yes. it does.
> By default in G2 the arrow keys map to up, down, rotate left, rotate right and do not allow you to move cells left/right if pressing left or right arrow key.

For me this was never the case, if i take a look at my German Steam Version from Notr this is how it acts : [YouTube](https://www.youtube.com/watch?v=p5UAdOXaGDk)
i used A and D to turn for ever since mouse support in Gothic was not great and i can move the inventory with that exact keys.

**Comment by okkindel** [comment]
I think, we can close now this issue, fixed in 6be4ca17f9e6b3bd89e02ccb1a953e3e311370c9.
