### ISSUE TITLE
addition to the manual for linux

### ISSUE THREAD

**Issue by redrootmin** [Try/OpenGothic#98]
Hello, thank you for your work, I do not know English well, so I translate with the help of google translator, I myself am from Russia and a big fan of gothic and Linux)
I noticed that in your instructions, there is no information about working on Linux through a Vulkan and that you need to use a similar command to start:/home/gamer/OpenGothic/build/opengothic/Gothic2Notr.sh -g "/mnt/game-data1/gog_games/Gothic"
 I tested my version from Gog Games with out mods, but so far everything works without mods!
my system:
ubuntu 20.04.1
Xanmod 5.9.8
mesa 20.2
r5 2600
vega 56
![Снимок экрана от 2020-11-16 09-44-09](https://user-images.githubusercontent.com/2938188/99221526-cde6f900-27f1-11eb-9e0b-5ff5e26b47f7.png)

**Comment by M1sh2** [comment]
Я страшные известия писать, Try from Russia. He wrote news about project on ru site world of players.
https://worldofplayers.ru/threads/41765/

**Comment by Try** [comment]
Hi, @redrootmin and welcome!

>  there is no information about working on Linux

Right, there is no such info in README. But do we really need it? I mean running on Linux is pretty straight forward anyways.

**Comment by 10JML01** [comment]
> Hi, @redrootmin and welcome!
> 
> > there is no information about working on Linux
> 
> Right, there is no such info in README. But do we really need it? I mean running on Linux is pretty straight forward anyways.

Yes, please.
